(asdf/parse-defsystem:defsystem :protobuf-grpc-example
  :version
  "0.1.0"
  :description
  "Protobuf and gRPC example generated by cl-cl-generator"
  :depends-on
  (:usocket :flexi-streams)
  :serial
  t
  :components
  ((:file "package") (:file "messages") (:file "network")))