;;;; p04_collections --- vec, push, aref, length, maps with sorted keys,
;;;; clone (the copy changes, the original stays) and move (E5, E15)

(in-package :polyglot-user)
(in-dsl)

(defmodule collections (:entry t)
           (defun sum-all (v)
             (declare (type (vec :i64) v) (values :i64))
             (let ((s 0))
               (dolist (x v)
                 (incf s x))
               s))

           (defun main ()
             (let ((v (vec-of :i64 5 3 8)))
               (push 1 v)
               (print-line (format-string "len={} first={} last={}" (length v) (aref v 0) (aref v (- (length v) 1))))
               (let ((copy (clone v)))
                 (push 100 copy)
                 (setf (aref copy 0) -5)
                 (print-line (format-string "original sum={} len={}" (sum-all v) (length v)))
                 (print-line (format-string "copy sum={} len={}" (sum-all copy) (length copy))))
               (let ((moved (move v)))
                 (print-line (format-string "moved len={}" (length moved)))))
             (let ((ages (map-of :string :i64)))
               (map-set ages "carol" 35)
               (map-set ages "alice" 30)
               (map-set ages "bob" 25)
               (dolist (name (map-keys-sorted ages))
                 (if-let (age (map-get ages name))
                     (print-line (format-string "{} is {}" name age))
                   (print-line "missing")))
               (print-line (format-string "has dave: {}" (if (map-contains ages "dave") "yes" "no")))
               (print-line (format-string "count={}" (length ages))))))

(defproject collections (:modules collections) (:entry collections))
