;; Code generated by polyglot-generator. DO NOT EDIT.
;; Source: project.lisp (git blob f2715e5101)
(defpackage :shapes-demo.app
  (:use :cl)
  (:import-from :shapes-demo.polyglot-rt #:pg-vec)
  (:import-from :shapes-demo.shapes #:circle #:rect #:total-area)
  (:shadowing-import-from :shapes-demo.shapes #:describe))

(in-package :shapes-demo.app)

(defclass widget ()
  ((x :initarg :x :initform 0.0d0 :accessor widget-x)
   (y :initarg :y :initform 0.0d0 :accessor widget-y)))

(defgeneric width (w))

(defmethod width ((w widget))
  1.0d0)

(defgeneric kind (w))

(defmethod kind ((w widget))
  "widget")

(defgeneric render (w))

(defmethod render ((w widget))
  (format nil "~a at (~,1f, ~,1f) width ~,1f" (kind w) (widget-x w)
          (widget-y w) (width w)))

(defgeneric move-to (w nx ny))

(defmethod move-to ((w widget) nx ny)
  (setf (widget-x w) nx)
  (setf (widget-y w) ny))

(defclass button (widget)
  ((caption :initarg :caption :initform "" :accessor button-caption)))

(defmethod width ((b button))
  (+ (call-next-method) (float (length (button-caption b)) 1.0d0)))

(defmethod kind ((b button))
  (concatenate 'string "button '" (button-caption b) "'"))

(defun main ()
  (let ((items
         (pg-vec (make-instance 'circle :r 2.0d0)
          (make-instance 'rect :w 3.0d0 :h 4.0d0))))
    (loop for s across items
          do (write-line (describe s)))
    (format t "total area = ~,2f~%" (total-area items)))
  (let ((ui
         (pg-vec (make-instance 'widget)
          (make-instance 'button :caption "OK"))))
    (loop for i from 0 below (length ui)
          do (move-to (aref ui i) (float (* 10 i) 1.0d0) 5.0d0))
    (loop for w across ui
          do (write-line (render w)))))
