;; Code generated by polyglot-generator. DO NOT EDIT.
;; Source: project.lisp (git blob f2715e5101)
(defpackage :shapes-demo.polyglot-rt
  (:use :cl)
  (:export #:pg-vec #:pg-clone #:pg-utf8-length #:pg-sorted-keys))

(in-package :shapes-demo.polyglot-rt)

(defun pg-vec (&rest items)
  "Adjustable vector with fill pointer: the representation of (vec T)."
  (make-array (length items) :adjustable t :fill-pointer t :initial-contents items))

(defgeneric pg-clone (x)
  (:documentation "Deep copy with the value semantics of the other targets."))

(defmethod pg-clone (x)
  x)

(defmethod pg-clone ((x vector))
  (if (stringp x)
      x
      (let ((copy (make-array (length x) :adjustable t :fill-pointer t)))
        (dotimes (i (length x) copy)
          (setf (aref copy i) (pg-clone (aref x i)))))))

(defmethod pg-clone ((x hash-table))
  (let ((copy (make-hash-table :test (hash-table-test x))))
    (maphash (lambda (k v) (setf (gethash k copy) (pg-clone v))) x)
    copy))

(defun pg-utf8-length (s)
  "Number of bytes of S in UTF-8."
  (loop for c across s
        sum (let ((code (char-code c)))
              (cond ((< code #x80) 1) ((< code #x800) 2) ((< code #x10000) 3) (t 4)))))

(defun pg-sorted-keys (map predicate)
  "The keys of MAP sorted with PREDICATE, as a vec."
  (apply #'pg-vec (sort (loop for k being the hash-keys of map collect k) predicate)))
