;; Code generated by polyglot-generator. DO NOT EDIT.
;; Source: project.lisp (git blob f2715e5101)
(defpackage :shapes-demo.shapes
  (:use :cl)
  (:shadow #:describe)
  (:export #:shape
           #:area
           #:label
           #:describe
           #:circle
           #:circle-r
           #:rect
           #:rect-w
           #:rect-h
           #:total-area))

(in-package :shapes-demo.shapes)

(defclass shape ()
  nil
  (:documentation "Something with an area."))

(defgeneric area (s))

(defgeneric label (s))

(defgeneric describe (s))

(defmethod describe ((s shape))
  (format nil "~a with area ~,2f" (label s) (area s)))

(defclass circle (shape)
  ((r :initarg :r :initform 1.0d0 :accessor circle-r)))

(defmethod area ((c circle))
  (* 3.0d0 (circle-r c) (circle-r c)))

(defmethod label ((c circle))
  "circle")

(defclass rect (shape)
  ((w :initarg :w :initform 1.0d0 :accessor rect-w)
   (h :initarg :h :initform 1.0d0 :accessor rect-h)))

(defmethod area ((r rect))
  (* (rect-w r) (rect-h r)))

(defmethod label ((r rect))
  "rect")

(defun total-area (items)
  "Sum of the areas of all shapes."
  (let ((sum 0.0d0))
    (loop for s across items
          do (incf sum (area s)))
    sum))
