;; Code generated by polyglot-generator. DO NOT EDIT.
;; Source: project.lisp (git blob f2715e5101)
(asdf:defsystem "shapes-demo"
  :serial t
  :components ((:file "polyglot-rt")
               (:file "shapes")
               (:file "app")))
