// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob a0ed3f7ea3)
//! Module av1.

const EAGAIN: i32 = -11;

#[derive(Debug, Clone)]
pub struct Rgba {
    pub w: u32,
    pub h: u32,
    pub data: Vec<u8>,
}

pub struct Decoder {
    pub ctx: Option<Dav1dContext>,
}

impl Decoder {
    /// Decode one tile (raw OBUs of a still picture) to RGBA8.
    pub fn decode(&mut self, _obu: &[u8]) -> Result<Rgba, String> {
        if _obu.is_empty() {
            return Err("leere Kachel".into());
        }
        // Dav1dContext is a Copy handle (raw Arc pointer).
        let ctx = self.ctx;
        let mut data = Dav1dData::default();
        // SAFETY: data is valid to write; the buffer holds _obu.len() bytes.
        unsafe {
            let p = dav1d_data_create(Some(NonNull::from(&mut data)), _obu.len());
            if p.is_null() {
                return Err("dav1d_data_create".into());
            }
            std::ptr::copy_nonoverlapping(_obu.as_ptr(), p, _obu.len());
        }
        let mut pic = Dav1dPicture::default();
        let mut got = false;
        // Send until everything is consumed, fetching pictures in between.
        for _ in 0..16 {
            if data.sz > 0 {
                // SAFETY: ctx comes from dav1d_open; data is valid.
                let r = unsafe { dav1d_send_data(ctx, Some(NonNull::from(&mut data))) };
                if r.0 != 0 && r.0 != EAGAIN {
                    // SAFETY: data is valid.
                    unsafe { dav1d_data_unref(Some(NonNull::from(&mut data))) };
                    return Err(format!("dav1d_send_data: {}", r.0));
                }
            }
            // SAFETY: ctx valid, pic writable.
            let r = unsafe { dav1d_get_picture(ctx, Some(NonNull::from(&mut pic))) };
            if r.0 == 0 {
                got = true;
                break;
            }
            if r.0 != EAGAIN {
                // SAFETY: data is valid.
                unsafe { dav1d_data_unref(Some(NonNull::from(&mut data))) };
                return Err(format!("dav1d_get_picture: {}", r.0));
            }
            if data.sz == 0 {
                break;
            }
        }
        // SAFETY: data is valid (maybe already empty).
        unsafe { dav1d_data_unref(Some(NonNull::from(&mut data))) };
        if !got {
            return Err("kein Bild dekodiert".into());
        }
        let out = picture_to_rgba(&pic);
        // SAFETY: pic was filled by dav1d_get_picture.
        unsafe { dav1d_picture_unref(Some(NonNull::from(&mut pic))) };
        out
    }
}

/// Open rav1d (1 thread is enough for 640x640).
pub fn decoder_new() -> Result<Decoder, String> {
    {
        let mut s = std::mem::MaybeUninit::<Dav1dSettings>::uninit();
        // SAFETY: s is valid to write; initialized afterwards.
        let mut s = unsafe {
            dav1d_default_settings(NonNull::new(s.as_mut_ptr()).unwrap());
            s.assume_init()
        };
        s.n_threads = 1;
        s.max_frame_delay = 1;
        let mut ctx: Option<Dav1dContext> = None;
        // SAFETY: pointers to local, valid values.
        let r = unsafe { dav1d_open(Some(NonNull::from(&mut ctx)), Some(NonNull::from(&mut s))) };
        if r.0 != 0 || ctx.is_none() {
            return Err(format!("dav1d_open: {}", r.0));
        }
        Ok(Decoder { ctx })
    }
}

/// Convert a decoded dav1d picture to RGBA8 (private helper).
fn picture_to_rgba(_pic: &Dav1dPicture) -> Result<Rgba, String> {
    {
        let (w, h) = (_pic.p.w as usize, _pic.p.h as usize);
        if _pic.p.bpc != 8 || _pic.p.layout != DAV1D_PIXEL_LAYOUT_I420 {
            return Err(format!(
                "nicht unterstützt: bpc {} layout {}",
                _pic.p.bpc, _pic.p.layout
            ));
        }
        let (ys, cs) = (_pic.stride[0] as usize, _pic.stride[1] as usize);
        let (ch, cw) = (h.div_ceil(2), w.div_ceil(2));
        let plane = |i: usize, len: usize| -> Result<&[u8], String> {
            let p = _pic.data[i].ok_or("fehlende Ebene")?;
            // SAFETY: dav1d guarantees stride-times-rows valid bytes per plane.
            Ok(unsafe { std::slice::from_raw_parts(p.as_ptr() as *const u8, len) })
        };
        let y = plane(0, ys * (h - 1) + w)?;
        let u = plane(1, cs * (ch - 1) + cw)?;
        let v = plane(2, cs * (ch - 1) + cw)?;
        let mut data = vec![0u8; w * h * 4];
        lbw_common::yuv::yuv420_to_rgba(y, ys, u, v, cs, w, h, &mut data);
        Ok(Rgba {
            w: w as u32,
            h: h as u32,
            data,
        })
    }
}

use rav1d::include::dav1d::data::Dav1dData;
use rav1d::include::dav1d::dav1d::{Dav1dContext, Dav1dSettings};
use rav1d::include::dav1d::headers::DAV1D_PIXEL_LAYOUT_I420;
use rav1d::include::dav1d::picture::Dav1dPicture;
use rav1d::src::lib::{
    dav1d_close, dav1d_data_create, dav1d_data_unref, dav1d_default_settings, dav1d_get_picture,
    dav1d_open, dav1d_picture_unref, dav1d_send_data,
};
use std::ptr::NonNull;

impl Drop for Decoder {
    fn drop(&mut self) {
        // SAFETY: ctx comes from dav1d_open and is closed exactly once here.
        unsafe { dav1d_close(Some(NonNull::from(&mut self.ctx))) };
    }
}
