// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob 54b973cbcc)
//! Module config.

#[derive(Debug, Clone)]
pub struct Config {
    pub connect: String,
}

/// Default server address (typical end of an ssh -L forward).
pub fn default_connect() -> String {
    "127.0.0.1:7878".to_string()
}

/// CLI usage, printed on --help and on parse errors.
pub fn usage_text() -> String {
    "lbw-client-pg: minimal low-bandwidth remote desktop client (640x640)\nusage: lbw-client-pg [--connect ADDR]".to_string()
}

/// Parse argv (argv[0] first). Nil on error; --help exits(0).
pub fn parse_args(args: &[String]) -> Option<Config> {
    let mut connect = default_connect();
    let mut bad = false;
    let mut i: i64 = 1;
    while i < args.len() as i64 {
        if args[i as usize] == "--connect" {
            i += 1;
            if i < args.len() as i64 {
                connect = args[i as usize].clone();
            } else {
                bad = true;
            }
        } else if args[i as usize] == "--help" || args[i as usize] == "-h" {
            println!("{}", usage_text());
            std::process::exit(0);
        } else {
            bad = true;
        }
        i += 1;
    }
    if bad {
        None
    } else {
        Some(Config { connect })
    }
}
