// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob eb76f6b228)
//! Module input.

/// Server name for a special key (None for unmapped keys).
pub fn key_name(_k: Key) -> Option<&'static str> {
    match _k {
        Key::Enter => Some("Enter"),
        Key::Escape => Some("Esc"),
        Key::Tab => Some("Tab"),
        Key::Backspace => Some("Backspace"),
        Key::Delete => Some("Delete"),
        Key::Up => Some("Up"),
        Key::Down => Some("Down"),
        Key::Left => Some("Left"),
        Key::Right => Some("Right"),
        Key::Home => Some("Home"),
        Key::End => Some("End"),
        Key::PageUp => Some("PageUp"),
        Key::PageDown => Some("PageDown"),
        Key::LeftShift => Some("Shift"),
        Key::RightShift => Some("Shift"),
        Key::LeftCtrl => Some("Control"),
        Key::RightCtrl => Some("Control"),
        Key::LeftAlt => Some("Alt"),
        Key::RightAlt => Some("Alt"),
        _ => None,
    }
}

/// Mouse buttons with X11 numbers.
pub fn btn_table() -> [(MouseButton, u8); 3] {
    [
        (MouseButton::Left, 1),
        (MouseButton::Middle, 2),
        (MouseButton::Right, 3),
    ]
}

use minifb::{Key, MouseButton};
