// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob cffc2f78a6)
// Thin bin: gen.lisp dropped the mod lines and
// rewrote the paths to the lib (bin split).
use lbw_client_pg::config::{parse_args, usage_text, Config};

/// Expand RGBA bytes to minifb 0RGB words.
fn upload_rgba(canvas: &[u8], buf: &mut [u32]) {
    for i in 0..canvas.len() as i64 / 4 {
        buf[i as usize] = canvas[(i * 4) as usize] as u32 * 65536
            + canvas[(i * 4 + 1) as usize] as u32 * 256
            + canvas[(i * 4 + 2) as usize] as u32;
    }
}

/// Fill a clipped rectangle in the u32 framebuffer.
fn fill_rect(_buf: &mut [u32], _x: u32, _y: u32, _w: u32, _h: u32, _color: u32) {
    let x0 = _x.min(640);
    let y0 = _y.min(640);
    let x1 = _x.saturating_add(_w).min(640);
    let y1 = _y.saturating_add(_h).min(640);
    for y in y0..y1 {
        for x in x0..x1 {
            _buf[(y * 640 + x) as usize] = _color;
        }
    }
}

/// Raster a string with scaled 8x8 glyphs (missing glyphs: ?).
fn draw_str(_buf: &mut [u32], _s: &str, _x: u32, _y: u32, _scale: u32, _fg: u32) {
    for (i, ch) in _s.chars().enumerate() {
        let glyph = BASIC_FONTS
            .get(ch)
            .or_else(|| LATIN_FONTS.get(ch))
            .or_else(|| BASIC_FONTS.get('?'))
            .unwrap_or([0; 8]);
        for (gy, row) in glyph.iter().enumerate() {
            for gx in 0..8u32 {
                if (row >> gx) & 1 == 1 {
                    for dy in 0.._scale {
                        for dx in 0.._scale {
                            let x = _x + (i as u32) * 8 * _scale + gx * _scale + dx;
                            let y = _y + (gy as u32) * _scale + dy;
                            if x < 640 && y < 640 {
                                _buf[(y * 640 + x) as usize] = _fg;
                            }
                        }
                    }
                }
            }
        }
    }
}

/// Raster one OCR text item (bg fill + scaled glyphs).
fn draw_text_item(_buf: &mut [u32], _item: &TextItem) {
    let bg = ((_item.bg[0] as u32) << 16) | ((_item.bg[1] as u32) << 8) | (_item.bg[2] as u32);
    let fg = ((_item.fg[0] as u32) << 16) | ((_item.fg[1] as u32) << 8) | (_item.fg[2] as u32);
    let (rx, ry, rw, rh) = (
        _item.rect.x as u32,
        _item.rect.y as u32,
        _item.rect.w as u32,
        _item.rect.h as u32,
    );
    fill_rect(&mut *_buf, rx, ry, rw, rh, bg);
    draw_str(&mut *_buf, &_item.text, rx, ry, (rh / 8).max(1), fg);
}

/// Raster the one-line status box (top, yellow on black).
fn draw_hud(_buf: &mut [u32], _scene: &Scene) {
    let link = match &_scene.link {
        Link::Connecting => "verbinde...".to_string(),
        Link::Up => "online".to_string(),
        Link::Down(why) => format!("offline ({why})"),
    };
    let hud = hud_text(
        &link,
        _scene.texts.len() as i64,
        _scene.tiles as i64,
        _scene.tile_bytes,
    );
    fill_rect(&mut *_buf, 0, 0, 640, 16, 0);
    draw_str(&mut *_buf, &hud, 8, 0, 2, 0xffff00);
}

/// Poll minifb input, send deltas to the server. True when F1 toggled.
fn poll_input(
    _net: &Net,
    _window: &Window,
    _chars: &Arc<Mutex<Vec<char>>>,
    _last_mouse: &mut (u16, u16),
    _last_btns: &mut [bool; 3],
    _show_hud: &mut bool,
) -> bool {
    let mut toggled = false;
    if let Some((mx, my)) = _window.get_mouse_pos(MouseMode::Clamp) {
        let pos = (mx.clamp(0.0, 639.0) as u16, my.clamp(0.0, 639.0) as u16);
        if pos != *_last_mouse {
            _net.send(ClientMsg::MouseMove { x: pos.0, y: pos.1 });
            *_last_mouse = pos;
        }
    }
    for (i, (btn, code)) in btn_table().iter().enumerate() {
        let down = _window.get_mouse_down(*btn);
        if down != _last_btns[i] {
            _net.send(ClientMsg::Button {
                button: *code,
                down,
            });
            _last_btns[i] = down;
        }
    }
    for ch in _chars.lock().unwrap().drain(..) {
        if !ch.is_control() {
            _net.send(ClientMsg::Text(ch.to_string()));
        }
    }
    for k in _window.get_keys_pressed(KeyRepeat::No) {
        if let Some(name) = key_name(k) {
            _net.send(ClientMsg::Key {
                key: name.into(),
                down: true,
            });
        }
    }
    for k in _window.get_keys_released() {
        if let Some(name) = key_name(k) {
            _net.send(ClientMsg::Key {
                key: name.into(),
                down: false,
            });
        }
    }
    if _window.is_key_pressed(Key::F1, KeyRepeat::No) {
        *_show_hud = !*_show_hud;
        toggled = true;
    }
    toggled
}

/// Run the client until the window closes.
fn run_app(_cfg: &Config) {
    let net = net_connect(&_cfg.connect);
    let mut scene = scene_new();
    let mut window = Window::new(
        "lbw-client-pg",
        640,
        640,
        WindowOptions {
            resize: false,
            ..Default::default()
        },
    )
    .expect("open window");
    window.set_target_fps(60);
    let chars = Arc::new(Mutex::new(Vec::new()));
    window.set_input_callback(Box::new(CharCollector {
        chars: chars.clone(),
    }));
    let mut buf = vec![0u32; 640 * 640];
    let mut show_hud = true;
    let mut last_mouse = (u16::MAX, u16::MAX);
    let mut last_btns = [false; 3];
    while window.is_open() {
        while let Ok(e) = net.events.try_recv() {
            scene.apply_event(e);
        }
        if scene.dirty {
            upload_rgba(&scene.canvas, &mut buf);
            scene.dirty = false;
        }
        for t in &scene.texts {
            draw_text_item(&mut buf, t);
        }
        if show_hud {
            draw_hud(&mut buf, &scene);
        }
        if poll_input(
            &net,
            &window,
            &chars,
            &mut last_mouse,
            &mut last_btns,
            &mut show_hud,
        ) {
            scene.dirty = true;
        }
        window
            .update_with_buffer(&buf, 640, 640)
            .expect("update window");
    }
}

fn main() {
    let args = std::env::args().collect::<Vec<String>>();
    if let Some(cfg) = parse_args(&args) {
        run_app(&cfg);
    } else {
        println!("{}", usage_text());
        std::process::exit(2);
    }
}

use font8x8::{UnicodeFonts, BASIC_FONTS, LATIN_FONTS};
use lbw_client_pg::input::{btn_table, key_name};
use lbw_client_pg::net::{net_connect, Net};
use lbw_client_pg::scene::{hud_text, scene_new, Link, Scene};
use lbw_common::{ClientMsg, TextItem};
use minifb::{InputCallback, Key, KeyRepeat, MouseMode, Window, WindowOptions};
use std::sync::{Arc, Mutex};

/// Collects typed unicode characters from minifb (see poll-input).
struct CharCollector {
    chars: Arc<Mutex<Vec<char>>>,
}

impl InputCallback for CharCollector {
    fn add_char(&mut self, uni: u32) {
        if let Some(ch) = char::from_u32(uni)
            && let Ok(mut chars) = self.chars.lock()
        {
            chars.push(ch);
        }
    }
}
