// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob 085a5b425e)
mod config;

use crate::config::{parse_args, usage_text};

fn main() {
    let args = std::env::args().collect::<Vec<String>>();
    if let Some(cfg) = parse_args(&args) {
        println!("{}", cfg.connect);
    } else {
        println!("{}", usage_text());
        std::process::exit(2);
    }
}
