// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob a0ed3f7ea3)
//! Module scene.

pub struct Scene {
    pub canvas: Vec<u8>,
    pub texts: Vec<lbw_common::TextItem>,
    pub dirty: bool,
    pub link: Link,
    pub tiles: u32,
    pub tile_bytes: u64,
}

impl Scene {
    /// Copy a w*h RGBA box at (x, y). Garbage is ignored, never panics.
    pub fn blit(&mut self, x: u32, y: u32, w: u32, h: u32, rgba: &[u8]) {
        if w > 640
            || h > 640
            || x + w > 640
            || y + h > 640
            || (w * h * 4) as i64 > rgba.len() as i64
        {
            return;
        }
        for row in 0..h {
            for k in 0..w * 4 {
                self.canvas[(((y + row) * 640 + x) * 4 + k) as usize] =
                    rgba[(row * (w * 4) + k) as usize];
            }
        }
        self.dirty = true;
    }

    /// Canvas color at (x, y) as [r g b] (tests/debug).
    pub fn pixel(&self, _x: u32, _y: u32) -> [u8; 3] {
        {
            let i = (_y as usize * 640 + _x as usize) * 4;
            [self.canvas[i], self.canvas[i + 1], self.canvas[i + 2]]
        }
    }

    /// Drop all text items.
    pub fn clear_texts(&mut self) {
        self.texts.clear();
    }

    /// Append one text item.
    pub fn push_text(&mut self, _ti: lbw_common::TextItem) {
        self.texts.push(_ti);
    }

    /// Apply a network event to the scene.
    pub fn apply_event(&mut self, _e: Event) {
        match _e {
            Event::Connected => {
                self.link = Link::Up;
            }
            Event::Disconnected(_why) => {
                if !matches!(self.link, Link::Down(_)) {
                    self.link = Link::Down(_why);
                }
            }
            Event::ClearText => {
                self.clear_texts();
            }
            Event::AddText(_t) => {
                self.push_text(_t);
            }
            Event::Tile {
                x,
                y,
                w,
                h,
                rgba,
                bytes,
            } => {
                self.blit(x as u32, y as u32, w, h, &rgba);
                self.tiles += 1;
                self.tile_bytes += bytes as u64;
            }
        }
    }
}

/// Fresh 640x640 scene (dark background), like source7 Scene::new.
pub fn scene_new() -> Scene {
    Scene {
        canvas: [24, 24, 32, 255].repeat(640 * 640),
        texts: Vec::new(),
        dirty: true,
        link: Link::Connecting,
        tiles: 0,
        tile_bytes: 0,
    }
}

/// One-line status for the HUD (link text comes from app's match).
pub fn hud_text(link: &str, n_texts: i64, tiles: i64, tile_bytes: u64) -> String {
    format!("{link} | {n_texts} Texte | {tiles} Kacheln ({tile_bytes} B) | F1 HUD")
}

/// Connection state for the HUD.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Link {
    Connecting,
    Up,
    Down(String),
}

/// Events the network thread hands to the UI (produced by net,
/// consumed by apply_event; lives here so scene is self-contained).
#[derive(Debug)]
pub enum Event {
    Connected,
    Disconnected(String),
    ClearText,
    AddText(lbw_common::TextItem),
    /// Decoded AV1 box (RGBA8, w times h).
    Tile {
        x: u16,
        y: u16,
        w: u32,
        h: u32,
        rgba: Vec<u8>,
        bytes: usize,
    },
}
