;;;; gen.lisp — HPIPM CFFI Binding Generator
;;;; Generates complete CFFI bindings for the HPIPM OCP QP solver library
;;;; from compact S-expression API specifications using cl-cl-generator.
;;;;
;;;; Usage: sbcl --load gen.lisp
;;;;
;;;; Output files in source01/:
;;;;   package.lisp, hpipm.asd, hpipm-cffi.lisp,
;;;;   hpipm-wrappers.lisp, mpc-demo.lisp

;;; ============================================================
;;; Section 1: Bootstrap
;;; ============================================================

(eval-when (:compile-toplevel :execute :load-toplevel)
  (let ((current-dir (make-pathname :directory (pathname-directory *load-pathname*))))
    (push (merge-pathnames "../../" current-dir) asdf:*central-registry*))
  (ql:quickload '(:cl-cl-generator :cffi)))

;;; ============================================================
;;; Section 2: Package and Configuration
;;; ============================================================

(defpackage :cl-cl-generator/hpipm-gen
  (:use :cl :cl-cl-generator))
(in-package :cl-cl-generator/hpipm-gen)

(defparameter *source-dir*
  (merge-pathnames "source01/"
    (make-pathname :directory (pathname-directory *load-pathname*))))

;;; ============================================================
;;; Section 3: Generation Metadata
;;; ============================================================

(defparameter *git-version*
  (handler-case
      (string-trim '(#\Space #\Tab #\Newline #\Return)
                   (with-output-to-string (s)
                     (sb-ext:run-program "/usr/bin/git" '("rev-parse" "HEAD")
                                         :output s)))
    (error () "unknown")))

(defparameter *generation-time*
  (multiple-value-bind (sec min hour day month year)
      (get-decoded-time)
    (format nil "~4d-~2,'0d-~2,'0d ~2,'0d:~2,'0d:~2,'0d"
            year month day hour min sec)))

(defun make-header-comments ()
  "Return toplevel comment forms with generation metadata."
  (list `(comment "Auto-generated by cl-cl-generator — do not edit manually.")
        `(comments ,(format nil "Generated: ~a" *generation-time*)
                   ,(format nil "Git:       ~a" *git-version*))))

;;; ============================================================
;;; Section 4: API Specification Tables
;;; ============================================================

(defparameter *precisions*
  ;; (c-prefix name cffi-float-type lisp-float-type description)
  '(("d" "double" :double double-float "Double-precision")
    ("s" "single" :float  single-float "Single-precision")))

(defparameter *dim-fields*
  ;; (c-field-name documentation)
  '(("nx"   "Number of states per stage")
    ("nu"   "Number of inputs per stage")
    ("nbx"  "Number of state box constraints per stage")
    ("nbu"  "Number of input box constraints per stage")
    ("ng"   "Number of general constraints per stage")
    ("ns"   "Number of soft constraint slacks per stage")
    ("nbxe" "Number of state box equality constraints")
    ("nbue" "Number of input box equality constraints")
    ("nge"  "Number of general equality constraints")))

(defparameter *qp-fields*
  ;; (c-field-name data-type documentation)
  ;; data-type: :matrix :vector :int-vector :int-flag
  '(;; Dynamics matrices
    ("A" :matrix "Dynamics matrix A_k (state to state)")
    ("B" :matrix "Dynamics matrix B_k (input to state)")
    ;; Cost matrices
    ("Q" :matrix "Cost Hessian Q_k (state)")
    ("R" :matrix "Cost Hessian R_k (input)")
    ("S" :matrix "Cost cross-term S_k (state x input)")
    ;; General constraint matrices
    ("C" :matrix "General constraint matrix C_k (state)")
    ("D" :matrix "General constraint matrix D_k (input)")
    ;; Dynamics vector
    ("b" :vector "Dynamics offset vector b_k")
    ;; Cost gradient vectors
    ("q" :vector "Cost gradient q_k (state)")
    ("r" :vector "Cost gradient r_k (input)")
    ;; Box constraint bounds
    ("lbu" :vector "Lower bound on inputs")
    ("ubu" :vector "Upper bound on inputs")
    ("lbx" :vector "Lower bound on states")
    ("ubx" :vector "Upper bound on states")
    ;; Box constraint masks
    ("lbu_mask" :vector "Mask for lower input box constraints")
    ("ubu_mask" :vector "Mask for upper input box constraints")
    ("lbx_mask" :vector "Mask for lower state box constraints")
    ("ubx_mask" :vector "Mask for upper state box constraints")
    ;; General constraint bounds
    ("lg" :vector "Lower bound on general constraints")
    ("ug" :vector "Upper bound on general constraints")
    ("lg_mask" :vector "Mask for lower general constraints")
    ("ug_mask" :vector "Mask for upper general constraints")
    ;; Soft constraint data
    ("Zl"  :vector "Soft constraint Hessian (lower)")
    ("Zu"  :vector "Soft constraint Hessian (upper)")
    ("zl"  :vector "Soft constraint gradient (lower)")
    ("zu"  :vector "Soft constraint gradient (upper)")
    ("lls" :vector "Lower bound on lower slack")
    ("lus" :vector "Lower bound on upper slack")
    ("lls_mask" :vector "Mask for lower slack bound")
    ("lus_mask" :vector "Mask for upper slack bound")
    ;; Index arrays
    ("idxb"     :int-vector "Indices of box-constrained variables")
    ("idxbx"    :int-vector "Indices of box-constrained states")
    ("idxbu"    :int-vector "Indices of box-constrained inputs")
    ("idxs"     :int-vector "Indices of soft-constrained variables")
    ("idxs_rev" :int-vector "Reverse mapping of soft constraint indices")
    ("idxe"     :int-vector "Indices of equality constraints")
    ("idxbue"   :int-vector "Indices of input box equalities")
    ("idxbxe"   :int-vector "Indices of state box equalities")
    ("idxge"    :int-vector "Indices of general equality constraints")
    ;; Selection matrices (integer arrays)
    ("Jbx"  :int-vector "Selection matrix for state box constraints")
    ("Jbu"  :int-vector "Selection matrix for input box constraints")
    ("Jsbu" :int-vector "Selection matrix for input soft constraints")
    ("Jsbx" :int-vector "Selection matrix for state soft constraints")
    ("Jsg"  :int-vector "Selection matrix for general soft constraints")
    ("Jbue" :int-vector "Selection matrix for input box equalities")
    ("Jbxe" :int-vector "Selection matrix for state box equalities")
    ("Jge"  :int-vector "Selection matrix for general equalities")
    ;; Flags
    ("diag_H_flag" :int-flag "Flag indicating diagonal Hessian")))

(defparameter *sol-fields*
  ;; (c-field-name documentation)
  '(("u"       "Optimal inputs")
    ("x"       "Optimal states")
    ("sl"      "Lower slack variables")
    ("su"      "Upper slack variables")
    ("pi"      "Dual variables (dynamics equality)")
    ("lam_lb"  "Lagrange multipliers (box lower)")
    ("lam_ub"  "Lagrange multipliers (box upper)")
    ("lam_lbu" "Lagrange multipliers (input lower)")
    ("lam_ubu" "Lagrange multipliers (input upper)")
    ("lam_lbx" "Lagrange multipliers (state lower)")
    ("lam_ubx" "Lagrange multipliers (state upper)")
    ("lam_lg"  "Lagrange multipliers (general lower)")
    ("lam_ug"  "Lagrange multipliers (general upper)")))

(defparameter *lifecycle-objects*
  ;; (c-suffix memsize-params create-params)
  ;; create always appends (struct-ptr :pointer) (mem :pointer)
  '(("ocp_qp_dim"     ((n :int))                           ((n :int)))
    ("ocp_qp"         ((dim :pointer))                     ((dim :pointer)))
    ("ocp_qp_sol"     ((dim :pointer))                     ((dim :pointer)))
    ("ocp_qp_ipm_arg" ((dim :pointer))                     ((dim :pointer)))
    ("ocp_qp_ipm_ws"  ((dim :pointer) (arg :pointer))      ((dim :pointer) (arg :pointer)))))

;;; ============================================================
;;; Section 5: Name Generation Helpers
;;; ============================================================

(defun lisp-name (&rest parts)
  "Join PARTS with hyphens, upcase, intern. Underscores become hyphens."
  (intern (string-upcase
           (format nil "~{~a~^-~}"
                   (mapcar (lambda (p) (substitute #\- #\_ (string p))) parts)))))

(defun c-name (&rest parts)
  "Join PARTS with underscores to form a C function name string."
  (format nil "~{~a~^_~}" (mapcar #'string parts)))

(defun make-qp-set-body (c-field field-type cffi-set-fn cffi-float lisp-float)
  "Generate the body of a QP setter wrapper function."
  (ecase field-type
    (:matrix
     `(let* ((rows (array-dimension value 0))
             (cols (array-dimension value 1))
             (ptr (cffi:foreign-alloc ,cffi-float :count (* rows cols))))
        (unwind-protect
            (progn
              (dotimes (j cols)
                (dotimes (i rows)
                  (setf (cffi:mem-aref ptr ,cffi-float (+ (* j rows) i))
                        (coerce (aref value i j) (quote ,lisp-float)))))
              (,cffi-set-fn ,c-field stage ptr qp))
          (cffi:foreign-free ptr))))
    (:vector
     `(let* ((n (length value))
             (ptr (cffi:foreign-alloc ,cffi-float :count n)))
        (unwind-protect
            (progn
              (dotimes (i n)
                (setf (cffi:mem-aref ptr ,cffi-float i)
                      (coerce (elt value i) (quote ,lisp-float))))
              (,cffi-set-fn ,c-field stage ptr qp))
          (cffi:foreign-free ptr))))
    (:int-vector
     `(let* ((n (length value))
             (ptr (cffi:foreign-alloc :int :count n)))
        (unwind-protect
            (progn
              (dotimes (i n)
                (setf (cffi:mem-aref ptr :int i) (elt value i)))
              (,cffi-set-fn ,c-field stage ptr qp))
          (cffi:foreign-free ptr))))
    (:int-flag
     `(cffi:with-foreign-object (ptr :int)
        (setf (cffi:mem-ref ptr :int) value)
        (,cffi-set-fn ,c-field stage ptr qp)))))

(defun make-sol-get-body (c-field cffi-get-fn cffi-float lisp-float)
  "Generate the body of a sol getter wrapper function."
  `(let ((ptr (cffi:foreign-alloc ,cffi-float :count n)))
     (unwind-protect
         (progn
           (,cffi-get-fn ,c-field stage ptr sol)
           (let ((result (make-array n :element-type (quote ,lisp-float))))
             (dotimes (i n)
               (setf (aref result i) (cffi:mem-aref ptr ,cffi-float i)))
             result))
       (cffi:foreign-free ptr))))

(defun make-with-macro-string (prec obj-suffix user-params)
  "Generate a with-<prec>-<obj> macro as a raw string.
   Uses call-with-<prec>-<obj> internally."
  (let ((macro-name (string-downcase
                     (format nil "with-~a-~a" prec
                             (substitute #\- #\_ obj-suffix))))
        (call-fn (string-downcase
                  (format nil "call-with-~a-~a" prec
                          (substitute #\- #\_ obj-suffix))))
        (params-decl (format nil "~{~(~a~)~^ ~}" user-params))
        (params-unquote (format nil "~{,~(~a~) ~}" user-params)))
    (format nil "(defmacro ~a ((var ~a) &body body)~%  ~
\"Allocate HPIPM ~a, bind to VAR, execute BODY, then free.\"~%  ~
(let ((fn-sym (gensym \"FN-\")))~%    ~
`(flet ((,fn-sym (,var) ,@body))~%       ~
(~a ~a#',fn-sym))))"
            macro-name params-decl obj-suffix call-fn params-unquote)))

;;; ============================================================
;;; Section 6: Generate package.lisp
;;; ============================================================

(let ((exports
       (append
        ;; Constants
        (list (lisp-name "+hpipm-struct-size+")
              (lisp-name "+hpipm-mode-speed+")
              (lisp-name "+hpipm-mode-balance+")
              (lisp-name "+hpipm-mode-robust+"))
        ;; Per precision
        (loop for (prec . nil) in *precisions* append
              (append
               ;; Lifecycle: memsize, create, call-with
               (loop for (obj . nil) in *lifecycle-objects* append
                     (list (lisp-name prec obj "memsize")
                           (lisp-name prec obj "create")
                           (lisp-name "call-with" prec obj)))
               ;; Generic set/get cffi functions
               (list (lisp-name prec "ocp-qp-dim-set")
                     (lisp-name prec "ocp-qp-set")
                     (lisp-name prec "ocp-qp-sol-get"))
               ;; Solve + set-default
               (list (lisp-name prec "ocp-qp-ipm-solve")
                     (lisp-name prec "ocp-qp-ipm-arg-set-default"))
               ;; Dim setter wrappers
               (loop for (field . nil) in *dim-fields*
                     collect (lisp-name prec "ocp-qp-dim-set" field))
               ;; QP setter wrappers
               (loop for (field . nil) in *qp-fields*
                     collect (lisp-name prec "ocp-qp-set" field))
               ;; Sol getter wrappers
               (loop for (field . nil) in *sol-fields*
                     collect (lisp-name prec "ocp-qp-sol-get" field)))))))
  (write-source "package"
    `(toplevel
      ,@(make-header-comments)
      (defpackage :hpipm
        (:use :cl)
        (:export ,@(mapcar (lambda (sym) (intern (symbol-name sym) :keyword))
                           exports))))
    *source-dir*))

(format t "Generated package.lisp~%")

;;; ============================================================
;;; Section 7: Generate hpipm.asd
;;; ============================================================

(let ((asd-path (merge-pathnames "hpipm.asd" *source-dir*)))
  (ensure-directories-exist asd-path)
  (with-open-file (out asd-path :direction :output :if-exists :supersede)
    (format out ";;;; hpipm.asd — Auto-generated by cl-cl-generator~%")
    (format out ";;;; Generated: ~a~%" *generation-time*)
    (format out "~%(defsystem :hpipm~%")
    (format out "  :description \"CFFI bindings for the HPIPM OCP QP solver\"~%")
    (format out "  :depends-on (:cffi)~%")
    (format out "  :serial t~%")
    (format out "  :components ((:file \"package\")~%")
    (format out "               (:file \"hpipm-cffi\")~%")
    (format out "               (:file \"hpipm-wrappers\")))~%")))

(format t "Generated hpipm.asd~%")

;;; ============================================================
;;; Section 8: Generate hpipm-cffi.lisp
;;; ============================================================

(write-source "hpipm-cffi"
  `(toplevel
    ,@(make-header-comments)
    (in-package :hpipm)

    (comment "--- Foreign library loading ---")
    (cffi:define-foreign-library libhpipm
      (:unix "libhpipm.so")
      (t (:default "libhpipm")))
    (cffi:use-foreign-library libhpipm)

    (comment "--- Constants ---")
    (defconstant +hpipm-struct-size+ 4096
      (raw "\"Upper bound for HPIPM struct allocation (bytes). Use cffi-grovel for exact size.\""))
    (defconstant +hpipm-mode-speed+ 0)
    (defconstant +hpipm-mode-balance+ 1)
    (defconstant +hpipm-mode-robust+ 2)

    ,@(loop
        for (prec prec-name cffi-float lisp-float prec-doc) in *precisions*
        append
        (append
         ;; Section header
         (list `(comment ,(format nil "--- ~a (~a) lifecycle functions ---"
                                  prec-doc prec)))

         ;; Lifecycle functions: memsize + create for each object
         (loop for (obj memsize-params create-params) in *lifecycle-objects*
               append
               (list
                ;; memsize
                `(cffi:defcfun (,(c-name prec obj "memsize")
                                ,(lisp-name prec obj "memsize"))
                     :int
                   ,@(loop for (pname ptype) in memsize-params
                           collect `(,pname ,ptype)))
                ;; create
                `(cffi:defcfun (,(c-name prec obj "create")
                                ,(lisp-name prec obj "create"))
                     :void
                   ,@(loop for (pname ptype) in create-params
                           collect `(,pname ,ptype))
                   (struct-ptr :pointer)
                   (mem :pointer))))

         ;; Generic dim_set
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_dim_set")
                               ,(lisp-name prec "ocp-qp-dim-set"))
                    :void
                  (field :string) (stage :int) (value :int) (dim :pointer)))

         ;; Generic qp_set
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_set")
                               ,(lisp-name prec "ocp-qp-set"))
                    :void
                  (field :string) (stage :int) (value :pointer) (qp :pointer)))

         ;; Generic sol_get
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_sol_get")
                               ,(lisp-name prec "ocp-qp-sol-get"))
                    :void
                  (field :string) (stage :int) (value :pointer) (sol :pointer)))

         ;; ipm_arg_set_default
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_ipm_arg_set_default")
                               ,(lisp-name prec "ocp-qp-ipm-arg-set-default"))
                    :void
                  (mode :int) (arg :pointer)))

         ;; ipm_solve
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_ipm_solve")
                               ,(lisp-name prec "ocp-qp-ipm-solve"))
                    :void
                  (qp :pointer) (qp-sol :pointer)
                  (arg :pointer) (ws :pointer))))))
  *source-dir*)

(format t "Generated hpipm-cffi.lisp~%")

;;; ============================================================
;;; Section 9: Generate hpipm-wrappers.lisp
;;; ============================================================

(write-source "hpipm-wrappers"
  `(toplevel
    ,@(make-header-comments)
    (in-package :hpipm)

    ,@(loop
        for (prec prec-name cffi-float lisp-float prec-doc) in *precisions*
        append
        (append
         ;; --- call-with-* functions ---
         (list `(comment ,(format nil "--- ~a call-with-* allocation helpers ---" prec-doc)))
         (loop for (obj memsize-params create-params) in *lifecycle-objects*
               for user-params = (mapcar #'first create-params)
               collect
               `(defun ,(lisp-name "call-with" prec obj) (,@user-params fn)
                  ,(format nil "Allocate ~a ~a, call FN with struct pointer, then free."
                           prec-doc obj)
                  (let* ((mem-size (,(lisp-name prec obj "memsize") ,@user-params))
                         (backing (cffi:foreign-alloc :char :count mem-size))
                         (ptr (cffi:foreign-alloc :char :count +hpipm-struct-size+)))
                    (,(lisp-name prec obj "create") ,@user-params ptr backing)
                    (unwind-protect (funcall fn ptr)
                      (cffi:foreign-free ptr)
                      (cffi:foreign-free backing)))))

         ;; --- with-* macros via raw strings ---
         (list `(comment ,(format nil "--- ~a with-* convenience macros ---" prec-doc)))
         (loop for (obj nil create-params) in *lifecycle-objects*
               for user-params = (mapcar #'first create-params)
               collect `(raw ,(make-with-macro-string prec obj user-params)))

         ;; --- Dim setter wrappers ---
         (list `(comment ,(format nil "--- ~a dimension setter wrappers ---" prec-doc)))
         (loop for (field doc) in *dim-fields*
               collect
               `(defun ,(lisp-name prec "ocp-qp-dim-set" field) (stage value dim)
                  ,doc
                  (,(lisp-name prec "ocp-qp-dim-set") ,field stage value dim)))

         ;; --- QP setter wrappers ---
         (list `(comment ,(format nil "--- ~a QP data setter wrappers ---" prec-doc)))
         (loop for (field field-type doc) in *qp-fields*
               collect
               `(defun ,(lisp-name prec "ocp-qp-set" field) (stage value qp)
                  ,doc
                  ,(make-qp-set-body field field-type
                                     (lisp-name prec "ocp-qp-set")
                                     cffi-float lisp-float)))

         ;; --- Sol getter wrappers ---
         (list `(comment ,(format nil "--- ~a solution getter wrappers ---" prec-doc)))
         (loop for (field doc) in *sol-fields*
               collect
               `(defun ,(lisp-name prec "ocp-qp-sol-get" field) (stage n sol)
                  ,(format nil "~a N is the number of elements to retrieve." doc)
                  ,(make-sol-get-body field
                                     (lisp-name prec "ocp-qp-sol-get")
                                     cffi-float lisp-float))))))
  *source-dir*)

(format t "Generated hpipm-wrappers.lisp~%")

;;; ============================================================
;;; Section 10: Generate mpc-demo.lisp
;;; ============================================================

;; Pre-compute discrete-time system matrices at generation time
(let* ((k 1.0d0) (c 0.1d0) (dt 0.1d0)
       ;; Ad = I + dt * Ac (Euler discretization)
       (ad00 1.0d0)       (ad01 dt)          (ad02 0.0d0)       (ad03 0.0d0)
       (ad10 (* dt -2 k)) (ad11 (+ 1 (* dt -2 c))) (ad12 (* dt k)) (ad13 (* dt c))
       (ad20 0.0d0)       (ad21 0.0d0)       (ad22 1.0d0)       (ad23 dt)
       (ad30 (* dt k))    (ad31 (* dt c))    (ad32 (* dt (- k))) (ad33 (+ 1 (* dt (- c))))
       ;; Bd = dt * Bc
       (bd0 0.0d0) (bd1 dt) (bd2 0.0d0) (bd3 0.0d0))

  (write-source "mpc-demo"
    `(toplevel
      ,@(make-header-comments)
      (comment "MPC demo: two coupled masses with spring and damper")
      (comment "System: m1*a1 = -2k*x1 + k*x2 - 2c*v1 + c*v2 + u")
      (comment "         m2*a2 =  k*x1 - k*x2 + c*v1 - c*v2")
      (comment "State: [x1 v1 x2 v2], Input: [F], Horizon: N=20")

      (defpackage :hpipm-demo
        (:use :cl :hpipm)
        (:export :run-mpc-demo))
      (in-package :hpipm-demo)

      (defun run-mpc-demo ()
        (let* ((N 20) (nx 4) (nu 1) (nbu 1) (nbx-0 4)
               (comment "Discrete-time system matrices (Euler, dt=0.1)")
               (Ad (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,ad00 ,ad01 ,ad02 ,ad03)
                          (list ,ad10 ,ad11 ,ad12 ,ad13)
                          (list ,ad20 ,ad21 ,ad22 ,ad23)
                          (list ,ad30 ,ad31 ,ad32 ,ad33))))
               (Bd (make-array (quote (4 1))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,bd0) (list ,bd1) (list ,bd2) (list ,bd3))))
               (comment "Cost matrices")
               (Q (make-array (quote (4 4))
                   :element-type (quote double-float)
                   :initial-contents
                   (quote ((1.0d0 0.0d0 0.0d0 0.0d0)
                           (0.0d0 0.1d0 0.0d0 0.0d0)
                           (0.0d0 0.0d0 1.0d0 0.0d0)
                           (0.0d0 0.0d0 0.0d0 0.1d0)))))
               (R (make-array (quote (1 1))
                   :element-type (quote double-float)
                   :initial-contents (quote ((0.01d0)))))
               (comment "Constraints and initial state")
               (u-max 5.0d0)
               (x0 (quote (1.0d0 0.0d0 0.5d0 0.0d0))))

          (format t "~%=== HPIPM MPC Demo: Mass-Spring-Damper ===~%")
          (format t "Horizon N=~a, nx=~a, nu=~a~%" N nx nu)
          (format t "Initial state: ~a~%" x0)

          (comment "1. Set up dimensions")
          (call-with-d-ocp-qp-dim N
            (lambda (dim)
              (dotimes (k (+ N 1))
                (d-ocp-qp-dim-set-nx k nx dim)
                (if (< k N)
                    (progn
                      (d-ocp-qp-dim-set-nu k nu dim)
                      (d-ocp-qp-dim-set-nbu k nbu dim))
                    (progn
                      (d-ocp-qp-dim-set-nu k 0 dim)
                      (d-ocp-qp-dim-set-nbu k 0 dim)))
                (if (= k 0)
                    (d-ocp-qp-dim-set-nbx k nbx-0 dim)
                    (d-ocp-qp-dim-set-nbx k 0 dim)))

              (comment "2. Set up QP data")
              (call-with-d-ocp-qp dim
                (lambda (qp)
                  (dotimes (k N)
                    (d-ocp-qp-set-A k Ad qp)
                    (d-ocp-qp-set-B k Bd qp)
                    (d-ocp-qp-set-Q k Q qp)
                    (d-ocp-qp-set-R k R qp)
                    (d-ocp-qp-set-idxbu k (quote (0)) qp)
                    (d-ocp-qp-set-lbu k (list (- u-max)) qp)
                    (d-ocp-qp-set-ubu k (list u-max) qp))
                  (comment "Terminal cost")
                  (d-ocp-qp-set-Q N Q qp)
                  (comment "Initial state constraint: lbx[0] = ubx[0] = x0")
                  (d-ocp-qp-set-idxbx 0 (quote (0 1 2 3)) qp)
                  (d-ocp-qp-set-lbx 0 x0 qp)
                  (d-ocp-qp-set-ubx 0 x0 qp)

                  (comment "3. Create solution struct")
                  (call-with-d-ocp-qp-sol dim
                    (lambda (sol)

                      (comment "4. Create solver arguments")
                      (call-with-d-ocp-qp-ipm-arg dim
                        (lambda (arg)
                          (d-ocp-qp-ipm-arg-set-default +hpipm-mode-balance+ arg)

                          (comment "5. Create workspace and solve")
                          (call-with-d-ocp-qp-ipm-ws dim arg
                            (lambda (ws)
                              (d-ocp-qp-ipm-solve qp sol arg ws)

                              (comment "6. Extract and print results")
                              (format t "~%Optimal inputs u*:~%")
                              (dotimes (k N)
                                (let ((uk (d-ocp-qp-sol-get-u k nu sol)))
                                  (format t "  u[~2d] = ~8,4f~%" k (aref uk 0))))
                              (format t "~%Optimal states x*:~%")
                              (dotimes (k (+ N 1))
                                (let ((xk (d-ocp-qp-sol-get-x k nx sol)))
                                  (format t "  x[~2d] = [~{~8,4f~^ ~}]~%"
                                          k (coerce xk (quote list)))))
                              (format t "~%MPC demo complete.~%")))))))))))))
    *source-dir*))

(format t "Generated mpc-demo.lisp~%")

;;; ============================================================
;;; Done
;;; ============================================================

(format t "~%=== Generation complete ===~%")
(format t "Output directory: ~a~%" *source-dir*)
(format t "Precisions: ~{~a~^, ~}~%" (mapcar #'fifth *precisions*))
(format t "Dim setter fields: ~a~%" (length *dim-fields*))
(format t "QP setter fields:  ~a~%" (length *qp-fields*))
(format t "Sol getter fields: ~a~%" (length *sol-fields*))
(format t "Lifecycle objects: ~a~%" (length *lifecycle-objects*))
(let ((per-prec (+ (* 2 (length *lifecycle-objects*))  ; memsize + create
                   3                                     ; dim-set, qp-set, sol-get
                   2                                     ; solve, set-default
                   (length *dim-fields*)
                   (length *qp-fields*)
                   (length *sol-fields*)
                   (length *lifecycle-objects*))))       ; call-with-*
  (format t "Functions per precision: ~a~%" per-prec)
  (format t "Total generated functions: ~a~%" (* 2 per-prec)))
