;;;; gen02.lisp — HPIPM High-Level Lisp-like API Generator
;;;; Generates a user-friendly Lisp interface on top of low-level CFFI bindings.
;;;;
;;;; Usage: sbcl --load gen02.lisp
;;;;
;;;; Output files in source01/:
;;;;   package.lisp (updated), hpipm.asd (updated), hpipm-high.lisp,
;;;;   mpc-demo-high.lisp, pendulum-demo-high.lisp, mpc-soft-demo.lisp

(eval-when (:compile-toplevel :execute :load-toplevel)
  (let ((current-dir (make-pathname :directory (pathname-directory *load-pathname*))))
    (push (merge-pathnames "../../" current-dir) asdf:*central-registry*))
  (ql:quickload '(:cl-cl-generator :cffi)))

(defpackage :cl-cl-generator/hpipm-gen-high
  (:use :cl :cl-cl-generator))
(in-package :cl-cl-generator/hpipm-gen-high)

(defparameter *source-dir*
  (merge-pathnames "source01/"
    (make-pathname :directory (pathname-directory *load-pathname*))))

(defparameter *git-version*
  (handler-case
      (string-trim '(#\Space #\Tab #\Newline #\Return)
                   (with-output-to-string (s)
                     (sb-ext:run-program "/usr/bin/git" '("rev-parse" "HEAD")
                                         :output s)))
    (error () "unknown")))

(defparameter *generation-time*
  (multiple-value-bind (sec min hour day month year)
      (get-decoded-time)
    (format nil "~4d-~2,'0d-~2,'0d ~2,'0d:~2,'0d:~2,'0d"
            year month day hour min sec)))

(defun make-header-comments ()
  "Return toplevel comment forms with generation metadata."
  (list `(comment "Auto-generated by cl-cl-generator (High-level API) — do not edit manually.")
        `(comments ,(format nil "Generated: ~a" *generation-time*)
                   ,(format nil "Git:       ~a" *git-version*))))

;;; Helper to create symbol names
(defun lisp-name (&rest parts)
  "Join PARTS with hyphens, upcase, intern. Underscores become hyphens."
  (intern (string-upcase
           (format nil "~{~a~^-~}"
                   (mapcar (lambda (p) (substitute #\- #\_ (string p))) parts)))))

;;; Low-level C-API specs (reused from gen01 to generate identical low-level package exports)
(defparameter *precisions*
  '(("d" "double" :double double-float "Double-precision")
    ("s" "single" :float  single-float "Single-precision")))

(defparameter *dim-fields*
  '(("nx") ("nu") ("nbx") ("nbu") ("ng") ("ns") ("nbxe") ("nbue") ("nge")))

(defparameter *qp-fields*
  '(("A") ("B") ("Q") ("R") ("S") ("C") ("D") ("b") ("q") ("r") ("lbu") ("ubu") ("lbx") ("ubx")
    ("Zl") ("Zu") ("zl") ("zu") ("lls") ("lus") ("idxs") ("idxbx") ("idxbu") ("Jsbx") ("Jsbu") ("Jsg")))

(defparameter *sol-fields*
  '(("u") ("x") ("sl") ("su") ("pi") ("lam_lb") ("lam_ub") ("lam_lbu") ("lam_ubu") ("lam_lbx") ("lam_ubx") ("lam_lg") ("lam_ug")))

(defparameter *lifecycle-objects*
  '("ocp_qp_dim" "ocp_qp" "ocp_qp_sol" "ocp_qp_ipm_arg" "ocp_qp_ipm_ws"))

;;; Generate low-level exports list
(defun make-low-level-exports ()
  (append
   (list (lisp-name "+hpipm-struct-size+")
         (lisp-name "+hpipm-mode-speed+")
         (lisp-name "+hpipm-mode-balance+")
         (lisp-name "+hpipm-mode-robust+"))
   (loop for (prec . nil) in *precisions* append
         (append
          (loop for obj in *lifecycle-objects* append
                (list (lisp-name prec obj "memsize")
                      (lisp-name prec obj "create")
                      (lisp-name "call-with" prec obj)))
          (list (lisp-name prec "ocp-qp-dim-set")
                (lisp-name prec "ocp-qp-set")
                (lisp-name prec "ocp-qp-sol-get")
                (lisp-name prec "ocp-qp-ipm-solve")
                (lisp-name prec "ocp-qp-ipm-arg-set-default")
                (lisp-name prec "ocp-qp-ipm-get-status")
                (lisp-name prec "ocp-qp-ipm-get-status-val")
                (lisp-name prec "ocp-qp-ipm-get-iter")
                (lisp-name prec "ocp-qp-ipm-get-iter-val"))
          (loop for (field) in *dim-fields*
                collect (lisp-name prec "ocp-qp-dim-set" field))
          (loop for (field) in *qp-fields*
                collect (lisp-name prec "ocp-qp-set" (cond ((string= field "b") "b-vec")
                                                           ((string= field "q") "q-vec")
                                                           ((string= field "r") "r-vec")
                                                           ((string= field "Zl") "Zl-mat")
                                                           ((string= field "Zu") "Zu-mat")
                                                           ((string= field "zl") "zl-vec")
                                                           ((string= field "zu") "zu-vec")
                                                           (t field))))
          (loop for (field) in *sol-fields*
                collect (lisp-name prec "ocp-qp-sol-get" field))))))

(defparameter *high-level-exports*
  '(mpc-solver
    mpc-solver-precision
    mpc-solver-horizon
    mpc-solver-nx
    mpc-solver-nu
    mpc-solver-ns
    mpc-solver-dim-ptr
    mpc-solver-qp-ptr
    mpc-solver-sol-ptr
    mpc-solver-arg-ptr
    mpc-solver-ws-ptr
    make-mpc-solver
    free-mpc-solver
    with-mpc-solver
    set-solver-stage-dynamics
    set-solver-dynamics
    set-solver-stage-cost
    set-solver-cost
    set-control-bounds
    set-state-bounds
    set-general-constraints
    set-solver-general-constraints
    solve-mpc))

;;; ============================================================
;;; 1. Generate package.lisp (Unified Exports)
;;; ============================================================
(let ((exports (append (make-low-level-exports) *high-level-exports*)))
  (write-source "package"
    `(toplevel
      ,@(make-header-comments)
      (defpackage :hpipm
        (:use :cl)
        (:export ,@(mapcar (lambda (sym) (intern (symbol-name sym) :keyword))
                           exports))))
    *source-dir*))

(format t "Generated package.lisp~%")

;;; ============================================================
;;; 2. Generate hpipm.asd (Unified System)
;;; ============================================================
(let ((asd-path (merge-pathnames "hpipm.asd" *source-dir*)))
  (ensure-directories-exist asd-path)
  (with-open-file (out asd-path :direction :output :if-exists :supersede)
    (format out ";;;; hpipm.asd — Auto-generated by cl-cl-generator~%")
    (format out ";;;; Generated: ~a~%" *generation-time*)
    (format out "~%(defsystem :hpipm~%")
    (format out "  :description \"CFFI bindings and high-level interface for the HPIPM OCP QP solver\"~%")
    (format out "  :depends-on (:cffi)~%")
    (format out "  :serial t~%")
    (format out "  :components ((:file \"package\")~%")
    (format out "               (:file \"hpipm-cffi\")~%")
    (format out "               (:file \"hpipm-wrappers\")~%")
    (format out "               (:file \"hpipm-high\")~%")
    (format out "               (:file \"mpc-demo\")~%")
    (format out "               (:file \"pendulum-demo\")~%")
    (format out "               (:file \"mpc-demo-high\")~%")
    (format out "               (:file \"pendulum-demo-high\")~%")
    (format out "               (:file \"mpc-soft-demo\")))~%")))

(format t "Generated hpipm.asd~%")

;;; ============================================================
;;; 3. Generate hpipm-high.lisp (High-Level API)
;;; ============================================================
(write-source "hpipm-high"
  `(toplevel
    ,@(make-header-comments)
    (in-package :hpipm)

    (comment "--- Solver Data Structure ---")
    (defstruct mpc-solver
      "Encapsulates all 5 HPIPM workspace and data pointers."
      precision
      horizon
      nx
      nu
      ns
      dim-ptr
      qp-ptr
      sol-ptr
      arg-ptr
      ws-ptr
      allocations)

    (comment "--- Helper for Aligned Struct Allocation ---")
    (defun allocate-hpipm-struct (memsize-fn create-fn create-args)
      "Calculate HPIPM struct memsize, allocate aligned buffers, create struct."
      (let* ((mem-size (apply memsize-fn create-args))
             (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
             (aligned-backing (align-pointer backing 64))
             (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
             (aligned-ptr (align-pointer ptr 64)))
        (apply create-fn (append create-args (list aligned-ptr aligned-backing)))
        (values aligned-ptr ptr backing)))

    (comment "--- Stage Resolution Helper ---")
    (defun expand-stage-spec (spec horizon type)
      "Expand symbolic stage spec (like :all, :terminal, :path) or integer into concrete stage list."
      (let ((N horizon))
        (cond
          ((integerp spec) (list spec))
          ((eq spec :all)
           (if (eq type :input)
               (loop for k from 0 below N collect k)
               (loop for k from 0 to N collect k)))
          ((eq spec :terminal) (list N))
          ((eq spec :path)
           (loop for k from 0 below N collect k))
          (t (error "Invalid stage specification: ~a" spec)))))

    (comment "--- Constructor and Destructor ---")
    (defun make-mpc-solver (&key (horizon 20) (nx 4) (nu 1) (nbu 0) (nbx 0) (ng 0) (precision :double) (mode :balance) soft-constraints)
      "Create, allocate, and initialize an MPC solver object."
      (let* ((nx-list (if (integerp nx) (make-list (+ horizon 1) :initial-element nx) (coerce nx 'list)))
             (nu-list (if (integerp nu) (append (make-list horizon :initial-element nu) (list 0)) (coerce nu 'list)))
             (nbu-list (if (integerp nbu) (append (make-list horizon :initial-element nbu) (list 0)) (coerce nbu 'list)))
             (nbx-list (if (integerp nbx) (cons (elt nx-list 0) (make-list horizon :initial-element nbx)) (coerce nbx 'list)))
             (ng-list (if (integerp ng) (make-list (+ horizon 1) :initial-element ng) (coerce ng 'list)))
             ;; Preprocess soft-constraints into stage-wise lists
             (soft-by-stage (make-array (+ horizon 1) :initial-element nil))
             (allocations nil))
        ;; Populate soft-by-stage array
        (dolist (sc soft-constraints)
          (let* ((stage-spec (getf sc :stage))
                 (sc-type (getf sc :type))
                 (stages (expand-stage-spec stage-spec horizon sc-type)))
            (dolist (st stages)
              (push sc (aref soft-by-stage st)))))
        
        ;; Reverse lists so they keep the original order
        (dotimes (k (+ horizon 1))
          (setf (aref soft-by-stage k) (nreverse (aref soft-by-stage k))))
        
        (flet ((register-alloc (aligned original backing)
                 (push original allocations)
                 (push backing allocations)
                 aligned))
          (multiple-value-bind (dim-ptr dim-orig dim-back)
              (ecase precision
                (:double (allocate-hpipm-struct #'d-ocp-qp-dim-memsize #'d-ocp-qp-dim-create (list horizon)))
                (:single (allocate-hpipm-struct #'s-ocp-qp-dim-memsize #'s-ocp-qp-dim-create (list horizon))))
            (register-alloc dim-ptr dim-orig dim-back)
            
            ;; Configure dimensions
            (dotimes (k (+ horizon 1))
              (let ((stage-nx (elt nx-list k))
                    (stage-nu (elt nu-list k))
                    (stage-nbx (elt nbx-list k))
                    (stage-nbu (elt nbu-list k))
                    (stage-ng (elt ng-list k))
                    (stage-ns (length (aref soft-by-stage k))))
                (ecase precision
                  (:double
                   (d-ocp-qp-dim-set-nx k stage-nx dim-ptr)
                   (d-ocp-qp-dim-set-nu k stage-nu dim-ptr)
                   (d-ocp-qp-dim-set-nbx k stage-nbx dim-ptr)
                   (d-ocp-qp-dim-set-nbu k stage-nbu dim-ptr)
                   (d-ocp-qp-dim-set-ng k stage-ng dim-ptr)
                   (d-ocp-qp-dim-set-ns k stage-ns dim-ptr))
                  (:single
                   (s-ocp-qp-dim-set-nx k stage-nx dim-ptr)
                   (s-ocp-qp-dim-set-nu k stage-nu dim-ptr)
                   (s-ocp-qp-dim-set-nbx k stage-nbx dim-ptr)
                   (s-ocp-qp-dim-set-nbu k stage-nbu dim-ptr)
                   (s-ocp-qp-dim-set-ng k stage-ng dim-ptr)
                   (s-ocp-qp-dim-set-ns k stage-ns dim-ptr)))))

            ;; Allocate QP, Solution, IPM Arg, and IPM Workspace
            (multiple-value-bind (qp-ptr qp-orig qp-back)
                (ecase precision
                  (:double (allocate-hpipm-struct #'d-ocp-qp-memsize #'d-ocp-qp-create (list dim-ptr)))
                  (:single (allocate-hpipm-struct #'s-ocp-qp-memsize #'s-ocp-qp-create (list dim-ptr))))
              (register-alloc qp-ptr qp-orig qp-back)
              
              ;; Populate soft constraints data inside QP
              (dotimes (k (+ horizon 1))
                (let* ((scs (aref soft-by-stage k))
                       (ns (length scs))
                       (nbu (elt nbu-list k))
                       (nbx (elt nbx-list k)))
                  (when (> ns 0)
                    (let ((idxs (make-array ns :element-type 'integer))
                          (Zl-weight (make-array ns :element-type 'double-float))
                          (Zu-weight (make-array ns :element-type 'double-float))
                          (zl-grad (make-array ns :element-type 'double-float))
                          (zu-grad (make-array ns :element-type 'double-float))
                          (lls (make-array ns :element-type 'double-float :initial-element 0.0d0))
                          (lus (make-array ns :element-type 'double-float :initial-element 0.0d0)))
                      (dotimes (i ns)
                        (let* ((sc (elt scs i))
                               (sc-type (getf sc :type))
                               (idx (getf sc :index))
                               (c-idx (ecase sc-type
                                        (:input idx)
                                        (:state (+ nbu idx))
                                        (:general (+ nbu nbx idx)))))
                          (setf (aref idxs i) c-idx)
                          (setf (aref Zl-weight i) (coerce (or (getf sc :Z) 1d3) 'double-float))
                          (setf (aref Zu-weight i) (coerce (or (getf sc :Z) 1d3) 'double-float))
                          (setf (aref zl-grad i) (coerce (or (getf sc :z) 0d0) 'double-float))
                          (setf (aref zu-grad i) (coerce (or (getf sc :z) 0d0) 'double-float))))
                      ;; Set in QP structure using resolved non-colliding names
                      (ecase precision
                        (:double
                         (d-ocp-qp-set-idxs k (coerce idxs 'list) qp-ptr)
                         (d-ocp-qp-set-Zl-mat k Zl-weight qp-ptr)
                         (d-ocp-qp-set-Zu-mat k Zu-weight qp-ptr)
                         (d-ocp-qp-set-zl-vec k zl-grad qp-ptr)
                         (d-ocp-qp-set-zu-vec k zu-grad qp-ptr)
                         (d-ocp-qp-set-lls k lls qp-ptr)
                         (d-ocp-qp-set-lus k lus qp-ptr))
                        (:single
                         (s-ocp-qp-set-idxs k (coerce idxs 'list) qp-ptr)
                         (s-ocp-qp-set-Zl-mat k (map 'simple-vector (lambda (x) (coerce x 'single-float)) Zl-weight) qp-ptr)
                         (s-ocp-qp-set-Zu-mat k (map 'simple-vector (lambda (x) (coerce x 'single-float)) Zu-weight) qp-ptr)
                         (s-ocp-qp-set-zl-vec k (map 'simple-vector (lambda (x) (coerce x 'single-float)) zl-grad) qp-ptr)
                         (s-ocp-qp-set-zu-vec k (map 'simple-vector (lambda (x) (coerce x 'single-float)) zu-grad) qp-ptr)
                         (s-ocp-qp-set-lls k (map 'simple-vector (lambda (x) (coerce x 'single-float)) lls) qp-ptr)
                         (s-ocp-qp-set-lus k (map 'simple-vector (lambda (x) (coerce x 'single-float)) lus) qp-ptr)))))))

              (multiple-value-bind (sol-ptr sol-orig sol-back)
                  (ecase precision
                    (:double (allocate-hpipm-struct #'d-ocp-qp-sol-memsize #'d-ocp-qp-sol-create (list dim-ptr)))
                    (:single (allocate-hpipm-struct #'s-ocp-qp-sol-memsize #'s-ocp-qp-sol-create (list dim-ptr))))
                (register-alloc sol-ptr sol-orig sol-back)
                
                (multiple-value-bind (arg-ptr arg-orig arg-back)
                    (ecase precision
                      (:double (allocate-hpipm-struct #'d-ocp-qp-ipm-arg-memsize #'d-ocp-qp-ipm-arg-create (list dim-ptr)))
                      (:single (allocate-hpipm-struct #'s-ocp-qp-ipm-arg-memsize #'s-ocp-qp-ipm-arg-create (list dim-ptr))))
                  (register-alloc arg-ptr arg-orig arg-back)
                  
                  ;; Set IPM solver settings default mode
                  (let ((mode-const (case mode
                                      (:speed +hpipm-mode-speed+)
                                      (:balance +hpipm-mode-balance+)
                                      (:robust +hpipm-mode-robust+)
                                      (t mode))))
                    (ecase precision
                      (:double (d-ocp-qp-ipm-arg-set-default mode-const arg-ptr))
                      (:single (s-ocp-qp-ipm-arg-set-default mode-const arg-ptr))))

                  (multiple-value-bind (ws-ptr ws-orig ws-back)
                      (ecase precision
                        (:double (allocate-hpipm-struct #'d-ocp-qp-ipm-ws-memsize #'d-ocp-qp-ipm-ws-create (list dim-ptr arg-ptr)))
                        (:single (allocate-hpipm-struct #'s-ocp-qp-ipm-ws-memsize #'s-ocp-qp-ipm-ws-create (list dim-ptr arg-ptr))))
                    (register-alloc ws-ptr ws-orig ws-back)
                    
                    (make-mpc-solver :precision precision
                                     :horizon horizon
                                     :nx nx-list
                                     :nu nu-list
                                     :ns (loop for k from 0 to horizon collect (length (aref soft-by-stage k)))
                                     :dim-ptr dim-ptr
                                     :qp-ptr qp-ptr
                                     :sol-ptr sol-ptr
                                     :arg-ptr arg-ptr
                                     :ws-ptr ws-ptr
                                     :allocations allocations)))))))))

    (defun free-mpc-solver (solver)
      "Free all allocated foreign memory for SOLVER."
      (dolist (ptr (mpc-solver-allocations solver))
        (cffi:foreign-free ptr))
      (setf (mpc-solver-allocations solver) nil))

    (defmacro with-mpc-solver ((solver-var &rest make-args) &body body)
      "Create an MPC solver, bind to SOLVER-VAR, run BODY, and ensure it is freed."
      `(let ((,solver-var (make-mpc-solver ,@make-args)))
         (unwind-protect
              (progn ,@body)
           (free-mpc-solver ,solver-var))))

    (comment "--- Setter Functions ---")
    (defun set-solver-stage-dynamics (solver stage A B)
      "Set dynamics transition matrix A and input matrix B for a specific STAGE."
      (let ((prec (mpc-solver-precision solver))
            (qp (mpc-solver-qp-ptr solver)))
        (ecase prec
          (:double
           (d-ocp-qp-set-a stage A qp)
           (d-ocp-qp-set-b stage B qp))
          (:single
           (s-ocp-qp-set-a stage A qp)
           (s-ocp-qp-set-b stage B qp)))))

    (defun set-solver-dynamics (solver A B)
      "Set uniform dynamics matrices A and B across all stages 0..N-1."
      (dotimes (k (mpc-solver-horizon solver))
        (set-solver-stage-dynamics solver k A B)))

    (defun set-solver-stage-cost (solver stage Q R &key S)
      "Set quadratic stage cost Hessian matrices Q (states) and R (inputs), and optional cross-term S."
      (let ((prec (mpc-solver-precision solver))
            (qp (mpc-solver-qp-ptr solver)))
        (ecase prec
          (:double
           (when Q (d-ocp-qp-set-q stage Q qp))
           (when R (d-ocp-qp-set-r stage R qp))
           (when S (d-ocp-qp-set-s stage S qp)))
          (:single
           (when Q (s-ocp-qp-set-q stage Q qp))
           (when R (s-ocp-qp-set-r stage R qp))
           (when S (s-ocp-qp-set-s stage S qp))))))

    (defun set-solver-cost (solver Q R &key terminal-q)
      "Set uniform cost matrices Q and R for stages 0..N-1, and TERMINAL-Q (defaults to Q) for stage N."
      (let ((N (mpc-solver-horizon solver)))
        (dotimes (k N)
          (set-solver-stage-cost solver k Q R))
        (set-solver-stage-cost solver N (or terminal-q Q) nil)))

    (defun set-control-bounds (solver index min max)
      "Set uniform control input bounds for control channel INDEX to range [MIN, MAX] across stages 0..N-1."
      (let ((prec (mpc-solver-precision solver))
            (qp (mpc-solver-qp-ptr solver))
            (N (mpc-solver-horizon solver)))
        (dotimes (k N)
          (ecase prec
            (:double
             (d-ocp-qp-set-idxbu k (list index) qp)
             (d-ocp-qp-set-lbu k (list min) qp)
             (d-ocp-qp-set-ubu k (list max) qp))
            (:single
             (s-ocp-qp-set-idxbu k (list index) qp)
             (s-ocp-qp-set-lbu k (list min) qp)
             (s-ocp-qp-set-ubu k (list max) qp))))))

    (defun set-state-bounds (solver stage indices min-values max-values)
      "Set state bounds at a specific STAGE for state INDICES (list of integers) to [MIN-VALUES, MAX-VALUES] (lists)."
      (let ((prec (mpc-solver-precision solver))
            (qp (mpc-solver-qp-ptr solver)))
        (ecase prec
          (:double
           (d-ocp-qp-set-idxbx stage indices qp)
           (d-ocp-qp-set-lbx stage min-values qp)
           (d-ocp-qp-set-ubx stage max-values qp))
          (:single
           (s-ocp-qp-set-idxbx stage indices qp)
           (s-ocp-qp-set-lbx stage min-values qp)
           (s-ocp-qp-set-ubx stage max-values qp)))))

    (comment "--- General Constraints Setters ---")
    (defun set-general-constraints (solver stage C D lg ug)
      "Set general linear constraints: lg <= C*x + D*u <= ug at a specific STAGE.
       If C or D are nil, they default to zero matrices of the correct dimensions."
      (let* ((prec (mpc-solver-precision solver))
             (qp (mpc-solver-qp-ptr solver))
             (nx (elt (mpc-solver-nx solver) stage))
             (nu (elt (mpc-solver-nu solver) stage))
             (ng (length lg))
             (element-type (ecase prec (:double 'double-float) (:single 'single-float)))
             (zero-val (ecase prec (:double 0.0d0) (:single 0.0f0)))
             (actual-C (or C (make-array (list ng nx) :element-type element-type :initial-element zero-val)))
             (actual-D (or D (make-array (list ng nu) :element-type element-type :initial-element zero-val))))
        (ecase prec
          (:double
           (d-ocp-qp-set-c stage actual-C qp)
           (d-ocp-qp-set-d stage actual-D qp)
           (d-ocp-qp-set-lg stage lg qp)
           (d-ocp-qp-set-ug stage ug qp))
          (:single
           (s-ocp-qp-set-c stage actual-C qp)
           (s-ocp-qp-set-d stage actual-D qp)
           (s-ocp-qp-set-lg stage (map 'list (lambda (x) (coerce x 'single-float)) lg) qp)
           (s-ocp-qp-set-ug stage (map 'list (lambda (x) (coerce x 'single-float)) ug) qp)))))

    (defun set-solver-general-constraints (solver C D lg ug)
      "Set uniform general linear constraints across all stages 0..N-1."
      (dotimes (k (mpc-solver-horizon solver))
        (set-general-constraints solver k C D lg ug)))

    (comment "--- Solver Call ---")
    (defun solve-mpc (solver x0)
      "Lock the initial state at stage 0 to X0, solve, and return (values u-trajectory x-trajectory status iterations sl-trajectory su-trajectory)."
      (let ((prec (mpc-solver-precision solver))
            (qp (mpc-solver-qp-ptr solver))
            (sol (mpc-solver-sol-ptr solver))
            (arg (mpc-solver-arg-ptr solver))
            (ws (mpc-solver-ws-ptr solver))
            (N (mpc-solver-horizon solver))
            (nx (elt (mpc-solver-nx solver) 0))
            (nu-list (mpc-solver-nu solver))
            (nx-list (mpc-solver-nx solver))
            (ns-list (mpc-solver-ns solver)))
        (let ((indices (loop for i from 0 below nx collect i)))
          (set-state-bounds solver 0 indices x0 x0))
        (ecase prec
          (:double
           (d-ocp-qp-ipm-solve qp sol arg ws))
          (:single
           (s-ocp-qp-ipm-solve qp sol arg ws)))
        (let ((status (ecase prec
                        (:double (d-ocp-qp-ipm-get-status-val ws))
                        (:single (s-ocp-qp-ipm-get-status-val ws))))
              (iterations (ecase prec
                            (:double (d-ocp-qp-ipm-get-iter-val ws))
                            (:single (s-ocp-qp-ipm-get-iter-val ws))))
              (u-traj (make-array N))
              (x-traj (make-array (+ N 1)))
              (sl-traj (make-array (+ N 1)))
              (su-traj (make-array (+ N 1))))
          (dotimes (k N)
            (let ((nu (elt nu-list k)))
              (setf (aref u-traj k)
                    (ecase prec
                      (:double (d-ocp-qp-sol-get-u k nu sol))
                      (:single (s-ocp-qp-sol-get-u k nu sol))))))
          (dotimes (k (+ N 1))
            (let ((nx (elt nx-list k)))
              (setf (aref x-traj k)
                    (ecase prec
                      (:double (d-ocp-qp-sol-get-x k nx sol))
                      (:single (s-ocp-qp-sol-get-x k nx sol))))))
          (dotimes (k (+ N 1))
            (let ((ns (elt ns-list k)))
              (setf (aref sl-traj k)
                    (if (> ns 0)
                        (ecase prec
                          (:double (d-ocp-qp-sol-get-sl k ns sol))
                          (:single (s-ocp-qp-sol-get-sl k ns sol)))
                        #()))
              (setf (aref su-traj k)
                    (if (> ns 0)
                        (ecase prec
                          (:double (d-ocp-qp-sol-get-su k ns sol))
                          (:single (s-ocp-qp-sol-get-su k ns sol)))
                        #()))))
          (values u-traj x-traj status iterations sl-traj su-traj)))))
  *source-dir*)

(format t "Generated hpipm-high.lisp~%")

;;; ============================================================
;;; 4. Generate mpc-demo-high.lisp (Coupled Mass-Spring-Damper)
;;; ============================================================
(let* ((k 1.0d0) (c 0.1d0) (dt 0.1d0)
       (ad00 1.0d0)       (ad01 dt)          (ad02 0.0d0)       (ad03 0.0d0)
       (ad10 (* dt -2 k)) (ad11 (+ 1 (* dt -2 c))) (ad12 (* dt k)) (ad13 (* dt c))
       (ad20 0.0d0)       (ad21 0.0d0)       (ad22 1.0d0)       (ad23 dt)
       (ad30 (* dt k))    (ad31 (* dt c))    (ad32 (* dt (- k))) (ad33 (+ 1 (* dt (- c))))
       (bd0 0.0d0) (bd1 dt) (bd2 0.0d0) (bd3 0.0d0))

  (write-source "mpc-demo-high"
    `(toplevel
      ,@(make-header-comments)
      (comment "================================================================================")
      (comment " MPC Demo (High-Level API): Coupled Mass-Spring-Damper System")
      (comment "================================================================================")

      (defpackage :hpipm-demo-high
        (:use :cl :hpipm)
        (:export :run-mpc-demo))
      (in-package :hpipm-demo-high)

      (defun run-mpc-demo ()
        "Run the coupled mass-spring-damper MPC simulation using the high-level API."
        (let* ((N 20)
               (nx 4)
               (nu 1)
               
               (Ad (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,ad00 ,ad01 ,ad02 ,ad03)
                          (list ,ad10 ,ad11 ,ad12 ,ad13)
                          (list ,ad20 ,ad21 ,ad22 ,ad23)
                          (list ,ad30 ,ad31 ,ad32 ,ad33))))
                          
               (Bd (make-array (quote (4 1))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,bd0) (list ,bd1) (list ,bd2) (list ,bd3))))
                     
               (Q (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (quote ((1.0d0 0.0d0 0.0d0 0.0d0)
                            (0.0d0 0.1d0 0.0d0 0.0d0)
                            (0.0d0 0.0d0 1.0d0 0.0d0)
                            (0.0d0 0.0d0 0.0d0 0.1d0)))))
                            
               (R (make-array (quote (1 1))
                    :element-type (quote double-float)
                    :initial-contents (quote ((0.01d0)))))
                    
               (u-max 5.0d0)
               (x0 (quote (1.0d0 0.0d0 0.5d0 0.0d0))))

          (format t "~%=== HPIPM MPC Demo (High-Level API): Mass-Spring-Damper ===~%")
          (format t "Horizon N=~a, nx=~a, nu=~a~%" N nx nu)
          (format t "Initial state: ~a~%" x0)

          (with-mpc-solver (solver :horizon N :nx nx :nu nu :precision :double :mode :balance)
            (set-solver-dynamics solver Ad Bd)
            (set-solver-cost solver Q R)
            (set-control-bounds solver 0 (- u-max) u-max)

            (multiple-value-bind (u-traj x-traj status iterations sl-traj su-traj)
                (solve-mpc solver x0)
              (declare (ignore sl-traj su-traj))
              (format t "~%Solver finished with status ~a after ~a iterations.~%" status iterations)
              (format t "~%Optimal control force input trajectory u* (Newtons):~%")
              (dotimes (k N)
                (format t "  u[~2d] = ~8,4f~%" k (aref (aref u-traj k) 0)))
              
              (format t "~%Optimal state trajectory x* (predicted positions & velocities):~%")
              (dotimes (k (+ N 1))
                (let ((xk (aref x-traj k)))
                  (format t "  x[~2d] = [pos1:~8,4f vel1:~8,4f pos2:~8,4f vel2:~8,4f]~%"
                          k 
                          (aref xk 0) (aref xk 1)
                          (aref xk 2) (aref xk 3))))
              (format t "~%MPC demo complete.~%"))))))
    *source-dir*))

(format t "Generated mpc-demo-high.lisp~%")

;;; ============================================================
;;; 5. Generate pendulum-demo-high.lisp (Inverted Pendulum)
;;; ============================================================
(let* ((dt 0.05d0)
       (pad00 1.00000000d0) (pad01 0.05000000d0) (pad02 0.00000000d0) (pad03 0.00000000d0)
       (pad10 0.00000000d0) (pad11 0.99512195d0) (pad12 0.03589024d0) (pad13 0.00000000d0)
       (pad20 0.00000000d0) (pad21 0.00000000d0) (pad22 1.00000000d0) (pad23 0.05000000d0)
       (pad30 0.00000000d0) (pad31 -0.00731707d0) (pad32 0.78958537d0) (pad33 1.00000000d0)
       (pbd0 0.00000000d0)
       (pbd1 0.04878049d0)
       (pbd2 0.00000000d0)
       (pbd3 0.07317073d0))

  (write-source "pendulum-demo-high"
    `(toplevel
      ,@(make-header-comments)
      (comment "================================================================================")
      (comment " MPC Demo (High-Level API): Inverted Pendulum on a Cart")
      (comment "================================================================================")

      (defpackage :hpipm-pendulum-demo-high
        (:use :cl :hpipm)
        (:export :run-pendulum-demo))
      (in-package :hpipm-pendulum-demo-high)

      (defun run-pendulum-demo ()
        "Run the unstable inverted pendulum MPC stabilization simulation using the high-level API."
        (let* ((N 30)
               (nx 4)
               (nu 1)
               
               (Ad (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,pad00 ,pad01 ,pad02 ,pad03)
                          (list ,pad10 ,pad11 ,pad12 ,pad13)
                          (list ,pad20 ,pad21 ,pad22 ,pad23)
                          (list ,pad30 ,pad31 ,pad32 ,pad33))))
                          
               (Bd (make-array (quote (4 1))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,pbd0) (list ,pbd1) (list ,pbd2) (list ,pbd3))))
                     
               (Q (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (quote ((10.0d0 0.0d0 0.0d0 0.0d0)
                            (0.0d0 1.0d0 0.0d0 0.0d0)
                            (0.0d0 0.0d0 100.0d0 0.0d0)
                            (0.0d0 0.0d0 0.0d0 10.0d0)))))
                            
               (R (make-array (quote (1 1))
                    :element-type (quote double-float)
                    :initial-contents (quote ((0.1d0)))))
                    
               (u-max 10.0d0)
               (x0 (quote (0.0d0 0.0d0 0.2d0 0.0d0))))

          (format t "~%=== HPIPM MPC Demo (High-Level API): Inverted Pendulum on Cart ===~%")
          (format t "Horizon N=~a, nx=~a, nu=~a~%" N nx nu)
          (format t "Initial state: ~a (tilted by ~5,2f deg)~%" x0 (* 0.2d0 (/ 180.0d0 pi)))

          (with-mpc-solver (solver :horizon N :nx nx :nu nu :precision :double :mode :balance)
            (set-solver-dynamics solver Ad Bd)
            (set-solver-cost solver Q R)
            (set-control-bounds solver 0 (- u-max) u-max)

            (multiple-value-bind (u-traj x-traj status iterations sl-traj su-traj)
                (solve-mpc solver x0)
              (declare (ignore sl-traj su-traj))
              (format t "~%Solver finished with status ~a after ~a iterations.~%" status iterations)
              (format t "~%Optimal force trajectory u* (Newtons):~%")
              (dotimes (k N)
                (format t "  u[~2d] = ~8,4f~%" k (aref (aref u-traj k) 0)))
              
              (format t "~%Optimal state trajectory x* (predicted cart position & pole angle):~%")
              (dotimes (k (+ N 1))
                (let ((xk (aref x-traj k)))
                  (format t "  x[~2d] = [cart_pos:~8,4f cart_vel:~8,4f pole_ang:~8,4f pole_vel:~8,4f]~%"
                          k 
                          (aref xk 0) (aref xk 1)
                          (aref xk 2) (aref xk 3))))
              (format t "~%Inverted pendulum stabilization complete.~%"))))))
    *source-dir*))

(format t "Generated pendulum-demo-high.lisp~%")

;;; ============================================================
;;; 6. Generate mpc-soft-demo.lisp (Soft-Constraints MSD Demo)
;;; ============================================================
(let* ((k 1.0d0) (c 0.1d0) (dt 0.1d0)
       (ad00 1.0d0)       (ad01 dt)          (ad02 0.0d0)       (ad03 0.0d0)
       (ad10 (* dt -2 k)) (ad11 (+ 1 (* dt -2 c))) (ad12 (* dt k)) (ad13 (* dt c))
       (ad20 0.0d0)       (ad21 0.0d0)       (ad22 1.0d0)       (ad23 dt)
       (ad30 (* dt k))    (ad31 (* dt c))    (ad32 (* dt (- k))) (ad33 (+ 1 (* dt (- c))))
       (bd0 0.0d0) (bd1 dt) (bd2 0.0d0) (bd3 0.0d0))

  (write-source "mpc-soft-demo"
    `(toplevel
      ,@(make-header-comments)
      (comment "================================================================================")
      (comment " MPC Demo with Soft-Constraints: Coupled Mass-Spring-Damper System")
      (comment "================================================================================")

      (defpackage :hpipm-soft-demo
        (:use :cl :hpipm)
        (:export :run-soft-demo))
      (in-package :hpipm-soft-demo)

      (defun run-soft-demo ()
        "Run mass-spring-damper MPC simulation showing how soft constraints handle otherwise infeasible bounds."
        (let* ((N 20)
               (nx 4)
               (nu 1)
               (Ad (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,ad00 ,ad01 ,ad02 ,ad03)
                          (list ,ad10 ,ad11 ,ad12 ,ad13)
                          (list ,ad20 ,ad21 ,ad22 ,ad23)
                          (list ,ad30 ,ad31 ,ad32 ,ad33))))
               (Bd (make-array (quote (4 1))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,bd0) (list ,bd1) (list ,bd2) (list ,bd3))))
               (Q (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (quote ((1.0d0 0.0d0 0.0d0 0.0d0)
                            (0.0d0 0.1d0 0.0d0 0.0d0)
                            (0.0d0 0.0d0 1.0d0 0.0d0)
                            (0.0d0 0.0d0 0.0d0 0.1d0)))))
               (R (make-array (quote (1 1))
                    :element-type (quote double-float)
                    :initial-contents (quote ((0.01d0)))))
               (u-max 5.0d0)
               ;; Initial state x0: mass 2 is at 0.5 meters.
               (x0 (quote (1.0d0 0.0d0 0.5d0 0.0d0)))
               ;; We place a soft constraint on mass 2 position (index 2 in state vector)
               ;; seeking to restrict it to <= 0.4 meters.
               ;; Since x0 has mass 2 at 0.5, this bound is immediately violated at stage 0!
               ;; If it were a hard constraint, the solver would fail (infeasible).
               ;; Using soft constraints, it converges successfully using positive slack.
               (soft-specs (quote ((:stage :all :type :state :index 2 :Z 1e4 :z 0.0)))))

          (format t "~%=== HPIPM MPC Soft-Constraints Demo ===~%")
          (format t "Horizon N=~a, nx=~a, nu=~a~%" N nx nu)
          (format t "Initial state: ~a~%" x0)
          (format t "Target: Restrict mass 2 position x2 <= 0.4m (softened with weight Z=1e4)~%")

          ;; We set nbx=1 for stages 1..N to enable the bound on x2
          (with-mpc-solver (solver :horizon N :nx nx :nu nu :nbx 1 :precision :double :soft-constraints soft-specs)
            (set-solver-dynamics solver Ad Bd)
            (set-solver-cost solver Q R)
            (set-control-bounds solver 0 (- u-max) u-max)
            
            ;; Set bounds on x2 (state index 2) to [-2.0, 0.4] for stages 1..N
            ;; Note: stage 0 is locked to x0, so we bound stage 1..N
            (dotimes (k N)
              (set-state-bounds solver (+ k 1) (quote (2)) (quote (-2.0d0)) (quote (0.4d0))))

            (multiple-value-bind (u-traj x-traj status iterations sl-traj su-traj)
                (solve-mpc solver x0)
              (format t "~%Solver finished with status ~a after ~a iterations.~%" status iterations)
              
              (format t "~%Optimal state trajectory x* & slacks s_u* at mass 2:~%")
              (dotimes (k (+ N 1))
                (let* ((xk (aref x-traj k))
                       (suk (aref su-traj k))
                       (slack-val (if (> (length suk) 0) (aref suk 0) 0.0d0)))
                  (format t "  Stage ~2d | x2 = ~8,4f m | upper slack = ~8,4f m~%"
                          k (aref xk 2) slack-val)))
              (format t "~%MPC soft-constraints demo complete.~%"))))))
    *source-dir*))

(format t "Generated mpc-soft-demo.lisp~%")
(format t "~%=== Generation Complete (gen02.lisp) ===~%")
