;;;; gen.lisp — HPIPM CFFI Binding Generator
;;;; Generates complete CFFI bindings for the HPIPM OCP QP solver library
;;;; from compact S-expression API specifications using cl-cl-generator.
;;;;
;;;; Usage: sbcl --load gen.lisp
;;;;
;;;; Output files in source01/:
;;;;   package.lisp, hpipm.asd, hpipm-cffi.lisp,
;;;;   hpipm-wrappers.lisp, mpc-demo.lisp

;;; ============================================================
;;; Section 1: Bootstrap
;;; ============================================================

(eval-when (:compile-toplevel :execute :load-toplevel)
  (let ((current-dir (make-pathname :directory (pathname-directory *load-pathname*))))
    (push (merge-pathnames "../../" current-dir) asdf:*central-registry*))
  (ql:quickload '(:cl-cl-generator :cffi)))

;;; ============================================================
;;; Section 2: Package and Configuration
;;; ============================================================

(defpackage :cl-cl-generator/hpipm-gen
  (:use :cl :cl-cl-generator))
(in-package :cl-cl-generator/hpipm-gen)

(defparameter *source-dir*
  (merge-pathnames "source01/"
    (make-pathname :directory (pathname-directory *load-pathname*))))

;;; ============================================================
;;; Section 3: Generation Metadata
;;; ============================================================

(defparameter *git-version*
  (handler-case
      (string-trim '(#\Space #\Tab #\Newline #\Return)
                   (with-output-to-string (s)
                     (sb-ext:run-program "/usr/bin/git" '("rev-parse" "HEAD")
                                         :output s)))
    (error () "unknown")))

(defparameter *generation-time*
  (multiple-value-bind (sec min hour day month year)
      (get-decoded-time)
    (format nil "~4d-~2,'0d-~2,'0d ~2,'0d:~2,'0d:~2,'0d"
            year month day hour min sec)))

(defun make-header-comments ()
  "Return toplevel comment forms with generation metadata."
  (list `(comment "Auto-generated by cl-cl-generator — do not edit manually.")
        `(comments ,(format nil "Generated: ~a" *generation-time*)
                   ,(format nil "Git:       ~a" *git-version*))))

;;; ============================================================
;;; Section 4: API Specification Tables
;;; ============================================================

(defparameter *precisions*
  ;; (c-prefix name cffi-float-type lisp-float-type description)
  '(("d" "double" :double double-float "Double-precision")
    ("s" "single" :float  single-float "Single-precision")))

(defparameter *dim-fields*
  ;; (c-field-name documentation)
  '(("nx"   "Number of states per stage")
    ("nu"   "Number of inputs per stage")
    ("nbx"  "Number of state box constraints per stage")
    ("nbu"  "Number of input box constraints per stage")
    ("ng"   "Number of general constraints per stage")
    ("ns"   "Number of soft constraint slacks per stage")
    ("nbxe" "Number of state box equality constraints")
    ("nbue" "Number of input box equality constraints")
    ("nge"  "Number of general equality constraints")))

(defparameter *qp-fields*
  ;; (c-field-name data-type documentation)
  ;; data-type: :matrix :vector :int-vector :int-flag
  '(;; Dynamics matrices
    ("A" :matrix "Dynamics matrix A_k (state to state)")
    ("B" :matrix "Dynamics matrix B_k (input to state)")
    ;; Cost matrices
    ("Q" :matrix "Cost Hessian Q_k (state)")
    ("R" :matrix "Cost Hessian R_k (input)")
    ("S" :matrix "Cost cross-term S_k (state x input)")
    ;; General constraint matrices
    ("C" :matrix "General constraint matrix C_k (state)")
    ("D" :matrix "General constraint matrix D_k (input)")
    ;; Dynamics vector
    ("b" :vector "Dynamics offset vector b_k")
    ;; Cost gradient vectors
    ("q" :vector "Cost gradient q_k (state)")
    ("r" :vector "Cost gradient r_k (input)")
    ;; Box constraint bounds
    ("lbu" :vector "Lower bound on inputs")
    ("ubu" :vector "Upper bound on inputs")
    ("lbx" :vector "Lower bound on states")
    ("ubx" :vector "Upper bound on states")
    ;; Box constraint masks
    ("lbu_mask" :vector "Mask for lower input box constraints")
    ("ubu_mask" :vector "Mask for upper input box constraints")
    ("lbx_mask" :vector "Mask for lower state box constraints")
    ("ubx_mask" :vector "Mask for upper state box constraints")
    ;; General constraint bounds
    ("lg" :vector "Lower bound on general constraints")
    ("ug" :vector "Upper bound on general constraints")
    ("lg_mask" :vector "Mask for lower general constraints")
    ("ug_mask" :vector "Mask for upper general constraints")
    ;; Soft constraint data
    ("Zl"  :vector "Soft constraint Hessian (lower)")
    ("Zu"  :vector "Soft constraint Hessian (upper)")
    ("zl"  :vector "Soft constraint gradient (lower)")
    ("zu"  :vector "Soft constraint gradient (upper)")
    ("lls" :vector "Lower bound on lower slack")
    ("lus" :vector "Lower bound on upper slack")
    ("lls_mask" :vector "Mask for lower slack bound")
    ("lus_mask" :vector "Mask for upper slack bound")
    ;; Index arrays
    ("idxb"     :int-vector "Indices of box-constrained variables")
    ("idxbx"    :int-vector "Indices of box-constrained states")
    ("idxbu"    :int-vector "Indices of box-constrained inputs")
    ("idxs"     :int-vector "Indices of soft-constrained variables")
    ("idxs_rev" :int-vector "Reverse mapping of soft constraint indices")
    ("idxe"     :int-vector "Indices of equality constraints")
    ("idxbue"   :int-vector "Indices of input box equalities")
    ("idxbxe"   :int-vector "Indices of state box equalities")
    ("idxge"    :int-vector "Indices of general equality constraints")
    ;; Selection matrices (integer arrays)
    ("Jbx"  :int-vector "Selection matrix for state box constraints")
    ("Jbu"  :int-vector "Selection matrix for input box constraints")
    ("Jsbu" :int-vector "Selection matrix for input soft constraints")
    ("Jsbx" :int-vector "Selection matrix for state soft constraints")
    ("Jsg"  :int-vector "Selection matrix for general soft constraints")
    ("Jbue" :int-vector "Selection matrix for input box equalities")
    ("Jbxe" :int-vector "Selection matrix for state box equalities")
    ("Jge"  :int-vector "Selection matrix for general equalities")
    ;; Flags
    ("diag_H_flag" :int-flag "Flag indicating diagonal Hessian")))

(defparameter *sol-fields*
  ;; (c-field-name documentation)
  '(("u"       "Optimal inputs")
    ("x"       "Optimal states")
    ("sl"      "Lower slack variables")
    ("su"      "Upper slack variables")
    ("pi"      "Dual variables (dynamics equality)")
    ("lam_lb"  "Lagrange multipliers (box lower)")
    ("lam_ub"  "Lagrange multipliers (box upper)")
    ("lam_lbu" "Lagrange multipliers (input lower)")
    ("lam_ubu" "Lagrange multipliers (input upper)")
    ("lam_lbx" "Lagrange multipliers (state lower)")
    ("lam_ubx" "Lagrange multipliers (state upper)")
    ("lam_lg"  "Lagrange multipliers (general lower)")
    ("lam_ug"  "Lagrange multipliers (general upper)")))

(defparameter *lifecycle-objects*
  ;; (c-suffix memsize-params create-params)
  ;; create always appends (struct-ptr :pointer) (mem :pointer)
  '(("ocp_qp_dim"     ((n :int))                           ((n :int)))
    ("ocp_qp"         ((dim :pointer))                     ((dim :pointer)))
    ("ocp_qp_sol"     ((dim :pointer))                     ((dim :pointer)))
    ("ocp_qp_ipm_arg" ((dim :pointer))                     ((dim :pointer)))
    ("ocp_qp_ipm_ws"  ((dim :pointer) (arg :pointer))      ((dim :pointer) (arg :pointer)))))

;;; ============================================================
;;; Section 5: Name Generation Helpers
;;; ============================================================

(defun lisp-name (&rest parts)
  "Join PARTS with hyphens, upcase, intern. Underscores become hyphens."
  (intern (string-upcase
           (format nil "~{~a~^-~}"
                   (mapcar (lambda (p) (substitute #\- #\_ (string p))) parts)))))

(defun c-name (&rest parts)
  "Join PARTS with underscores to form a C function name string."
  (format nil "~{~a~^_~}" (mapcar #'string parts)))

(defun lisp-field-name (field)
  "Map colliding lowercase C fields (b, q, r) and case-colliding slacks to distinct Lisp names."
  (cond
    ((string= field "b") "b-vec")
    ((string= field "q") "q-vec")
    ((string= field "r") "r-vec")
    ((string= field "Zl") "Zl-mat")
    ((string= field "Zu") "Zu-mat")
    ((string= field "zl") "zl-vec")
    ((string= field "zu") "zu-vec")
    (t field)))

(defun make-qp-set-body (c-field field-type cffi-set-fn cffi-float lisp-float)
  "Generate the body of a QP setter wrapper function."
  (ecase field-type
    (:matrix
     `(let* ((rows (array-dimension value 0))
             (cols (array-dimension value 1))
             (ptr (cffi:foreign-alloc ,cffi-float :count (* rows cols))))
        (unwind-protect
            (progn
              (dotimes (j cols)
                (dotimes (i rows)
                  (setf (cffi:mem-aref ptr ,cffi-float (+ (* j rows) i))
                        (coerce (aref value i j) (quote ,lisp-float)))))
              (,cffi-set-fn ,c-field stage ptr qp))
          (cffi:foreign-free ptr))))
    (:vector
     `(let* ((n (length value))
             (ptr (cffi:foreign-alloc ,cffi-float :count n)))
        (unwind-protect
            (progn
              (dotimes (i n)
                (setf (cffi:mem-aref ptr ,cffi-float i)
                      (coerce (elt value i) (quote ,lisp-float))))
              (,cffi-set-fn ,c-field stage ptr qp))
          (cffi:foreign-free ptr))))
    (:int-vector
     `(let* ((n (length value))
             (ptr (cffi:foreign-alloc :int :count n)))
        (unwind-protect
            (progn
              (dotimes (i n)
                (setf (cffi:mem-aref ptr :int i) (elt value i)))
              (,cffi-set-fn ,c-field stage ptr qp))
          (cffi:foreign-free ptr))))
    (:int-flag
     `(cffi:with-foreign-object (ptr :int)
        (setf (cffi:mem-ref ptr :int) value)
        (,cffi-set-fn ,c-field stage ptr qp)))))

(defun make-sol-get-body (c-field cffi-get-fn cffi-float lisp-float)
  "Generate the body of a sol getter wrapper function."
  `(let ((ptr (cffi:foreign-alloc ,cffi-float :count n)))
     (unwind-protect
         (progn
           (,cffi-get-fn ,c-field stage sol ptr)
           (let ((result (make-array n :element-type (quote ,lisp-float))))
             (dotimes (i n)
               (setf (aref result i) (cffi:mem-aref ptr ,cffi-float i)))
             result))
       (cffi:foreign-free ptr))))

(defun make-with-macro-string (prec obj-suffix user-params)
  "Generate a with-<prec>-<obj> macro as a raw string.
   Uses call-with-<prec>-<obj> internally."
  (let ((macro-name (string-downcase
                     (format nil "with-~a-~a" prec
                             (substitute #\- #\_ obj-suffix))))
        (call-fn (string-downcase
                  (format nil "call-with-~a-~a" prec
                          (substitute #\- #\_ obj-suffix))))
        (params-decl (format nil "~{~(~a~)~^ ~}" user-params))
        (params-unquote (format nil "~{,~(~a~) ~}" user-params)))
    (format nil "(defmacro ~a ((var ~a) &body body)~%  ~
\"Allocate HPIPM ~a, bind to VAR, execute BODY, then free.\"~%  ~
(let ((fn-sym (gensym \"FN-\")))~%    ~
`(flet ((,fn-sym (,var) ,@body))~%       ~
(~a ~a#',fn-sym))))"
            macro-name params-decl obj-suffix call-fn params-unquote)))

;;; ============================================================
;;; Section 6: Generate package.lisp
;;; ============================================================

(let ((exports
       (append
        ;; Constants
        (list (lisp-name "+hpipm-struct-size+")
              (lisp-name "+hpipm-mode-speed+")
              (lisp-name "+hpipm-mode-balance+")
              (lisp-name "+hpipm-mode-robust+"))
        ;; Per precision
        (loop for (prec . nil) in *precisions* append
              (append
               ;; Lifecycle: memsize, create, call-with
               (loop for (obj . nil) in *lifecycle-objects* append
                     (list (lisp-name prec obj "memsize")
                           (lisp-name prec obj "create")
                           (lisp-name "call-with" prec obj)))
               ;; Generic set/get cffi functions
               (list (lisp-name prec "ocp-qp-dim-set")
                     (lisp-name prec "ocp-qp-set")
                     (lisp-name prec "ocp-qp-sol-get"))
               ;; Solve + set-default + status/iter
               (list (lisp-name prec "ocp-qp-ipm-solve")
                     (lisp-name prec "ocp-qp-ipm-arg-set-default")
                     (lisp-name prec "ocp-qp-ipm-get-status")
                     (lisp-name prec "ocp-qp-ipm-get-status-val")
                     (lisp-name prec "ocp-qp-ipm-get-iter")
                     (lisp-name prec "ocp-qp-ipm-get-iter-val"))
               ;; Dim setter wrappers
               (loop for (field . nil) in *dim-fields*
                     collect (lisp-name prec "ocp-qp-dim-set" field))
               ;; QP setter wrappers
               (loop for (field . nil) in *qp-fields*
                     collect (lisp-name prec "ocp-qp-set" (lisp-field-name field)))
               ;; Sol getter wrappers
               (loop for (field . nil) in *sol-fields*
                     collect (lisp-name prec "ocp-qp-sol-get" field)))))))
  (write-source "package"
    `(toplevel
      ,@(make-header-comments)
      (defpackage :hpipm
        (:use :cl)
        (:export ,@(mapcar (lambda (sym) (intern (symbol-name sym) :keyword))
                           exports))))
    *source-dir*))

(format t "Generated package.lisp~%")

;;; ============================================================
;;; Section 7: Generate hpipm.asd
;;; ============================================================

(let ((asd-path (merge-pathnames "hpipm.asd" *source-dir*)))
  (ensure-directories-exist asd-path)
  (with-open-file (out asd-path :direction :output :if-exists :supersede)
    (format out ";;;; hpipm.asd — Auto-generated by cl-cl-generator~%")
    (format out ";;;; Generated: ~a~%" *generation-time*)
    (format out "~%(defsystem :hpipm~%")
    (format out "  :description \"CFFI bindings for the HPIPM OCP QP solver\"~%")
    (format out "  :depends-on (:cffi)~%")
    (format out "  :serial t~%")
    (format out "  :components ((:file \"package\")~%")
    (format out "               (:file \"hpipm-cffi\")~%")
    (format out "               (:file \"hpipm-wrappers\")~%")
    (format out "               (:file \"mpc-demo\")~%")
    (format out "               (:file \"pendulum-demo\")))~%")))

(format t "Generated hpipm.asd~%")

;;; ============================================================
;;; Section 8: Generate hpipm-cffi.lisp
;;; ============================================================

(write-source "hpipm-cffi"
  `(toplevel
    ,@(make-header-comments)
    (in-package :hpipm)

    (comment "--- Foreign library loading ---")
    (cffi:define-foreign-library libhpipm
      (:unix "libhpipm.so")
      (t (:default "libhpipm")))
    (cffi:use-foreign-library libhpipm)

    (comment "--- Constants ---")
    (defconstant +hpipm-struct-size+ 4096
      (raw "\"Upper bound for HPIPM struct allocation (bytes). Use cffi-grovel for exact size.\""))
    (defconstant +hpipm-mode-speed+ 0)
    (defconstant +hpipm-mode-balance+ 1)
    (defconstant +hpipm-mode-robust+ 2)

    ,@(loop
        for (prec prec-name cffi-float lisp-float prec-doc) in *precisions*
        append
        (append
         ;; Section header
         (list `(comment ,(format nil "--- ~a (~a) lifecycle functions ---"
                                  prec-doc prec)))

         ;; Lifecycle functions: memsize + create for each object
         (loop for (obj memsize-params create-params) in *lifecycle-objects*
               append
               (list
                ;; memsize
                `(cffi:defcfun (,(c-name prec obj "memsize")
                                ,(lisp-name prec obj "memsize"))
                     :int
                   ,@(loop for (pname ptype) in memsize-params
                           collect `(,pname ,ptype)))
                ;; create
                `(cffi:defcfun (,(c-name prec obj "create")
                                ,(lisp-name prec obj "create"))
                     :void
                   ,@(loop for (pname ptype) in create-params
                           collect `(,pname ,ptype))
                   (struct-ptr :pointer)
                   (mem :pointer))))

         ;; Generic dim_set
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_dim_set")
                               ,(lisp-name prec "ocp-qp-dim-set"))
                    :void
                  (field :string) (stage :int) (value :int) (dim :pointer)))

         ;; Generic qp_set
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_set")
                               ,(lisp-name prec "ocp-qp-set"))
                    :void
                  (field :string) (stage :int) (value :pointer) (qp :pointer)))

         ;; Generic sol_get
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_sol_get")
                               ,(lisp-name prec "ocp-qp-sol-get"))
                    :void
                  (field :string) (stage :int) (sol :pointer) (value :pointer)))

         ;; ipm_arg_set_default
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_ipm_arg_set_default")
                               ,(lisp-name prec "ocp-qp-ipm-arg-set-default"))
                    :void
                  (mode :int) (arg :pointer)))

         ;; ipm_solve
         (list `(cffi:defcfun (,(c-name prec "ocp_qp_ipm_solve")
                               ,(lisp-name prec "ocp-qp-ipm-solve"))
                    :void
                  (qp :pointer) (qp-sol :pointer)
                  (arg :pointer) (ws :pointer))
               ;; ipm_get_status
               `(cffi:defcfun (,(c-name prec "ocp_qp_ipm_get_status")
                               ,(lisp-name prec "ocp-qp-ipm-get-status"))
                    :void
                  (workspace :pointer) (status :pointer))
               ;; ipm_get_iter
               `(cffi:defcfun (,(c-name prec "ocp_qp_ipm_get_iter")
                               ,(lisp-name prec "ocp-qp-ipm-get-iter"))
                    :void
                  (workspace :pointer) (iter :pointer))))))
  *source-dir*)

(format t "Generated hpipm-cffi.lisp~%")

;;; ============================================================
;;; Section 9: Generate hpipm-wrappers.lisp
;;; ============================================================

(write-source "hpipm-wrappers"
  `(toplevel
    ,@(make-header-comments)
    (in-package :hpipm)

    (defun align-pointer (ptr alignment)
      "Align pointer PTR to ALIGNMENT boundary."
      (let* ((addr (cffi:pointer-address ptr))
             (aligned-addr (* (ceiling addr alignment) alignment)))
        (cffi:make-pointer aligned-addr)))

    ,@(loop
        for (prec prec-name cffi-float lisp-float prec-doc) in *precisions*
        append
        (append
         ;; --- call-with-* functions ---
         (list `(comment ,(format nil "--- ~a call-with-* allocation helpers ---" prec-doc)))
         (loop for (obj memsize-params create-params) in *lifecycle-objects*
               for user-params = (mapcar #'first create-params)
               collect
               `(defun ,(lisp-name "call-with" prec obj) (,@user-params fn)
                  ,(format nil "Allocate ~a ~a, call FN with struct pointer, then free."
                           prec-doc obj)
                  (let* ((mem-size (,(lisp-name prec obj "memsize") ,@user-params))
                         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
                         (aligned-backing (align-pointer backing 64))
                         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
                         (aligned-ptr (align-pointer ptr 64)))
                    (,(lisp-name prec obj "create") ,@user-params aligned-ptr aligned-backing)
                    (unwind-protect (funcall fn aligned-ptr)
                      (cffi:foreign-free ptr)
                      (cffi:foreign-free backing)))))

         ;; --- with-* macros via raw strings ---
         (list `(comment ,(format nil "--- ~a with-* convenience macros ---" prec-doc)))
         (loop for (obj nil create-params) in *lifecycle-objects*
               for user-params = (mapcar #'first create-params)
               collect `(raw ,(make-with-macro-string prec obj user-params)))

         ;; --- Dim setter wrappers ---
         (list `(comment ,(format nil "--- ~a dimension setter wrappers ---" prec-doc)))
         (loop for (field doc) in *dim-fields*
               collect
               `(defun ,(lisp-name prec "ocp-qp-dim-set" field) (stage value dim)
                  ,doc
                  (,(lisp-name prec "ocp-qp-dim-set") ,field stage value dim)))

         ;; --- QP setter wrappers ---
         (list `(comment ,(format nil "--- ~a QP data setter wrappers ---" prec-doc)))
         (loop for (field field-type doc) in *qp-fields*
               collect
               `(defun ,(lisp-name prec "ocp-qp-set" (lisp-field-name field)) (stage value qp)
                  ,doc
                  ,(make-qp-set-body field field-type
                                     (lisp-name prec "ocp-qp-set")
                                     cffi-float lisp-float)))

         ;; --- Sol getter wrappers ---
         (list `(comment ,(format nil "--- ~a solution getter wrappers ---" prec-doc)))
         (append
          (loop for (field doc) in *sol-fields*
                collect
                `(defun ,(lisp-name prec "ocp-qp-sol-get" field) (stage n sol)
                   ,(format nil "~a N is the number of elements to retrieve." doc)
                   ,(make-sol-get-body field
                                      (lisp-name prec "ocp-qp-sol-get")
                                      cffi-float lisp-float)))
          ;; --- IPM status & iter getters ---
          (list `(defun ,(lisp-name prec "ocp-qp-ipm-get-status-val") (workspace)
                   "Retrieve solver status (0 = success, other = failure)."
                   (cffi:with-foreign-object (ptr :int)
                     (,(lisp-name prec "ocp-qp-ipm-get-status") workspace ptr)
                     (cffi:mem-ref ptr :int)))
                `(defun ,(lisp-name prec "ocp-qp-ipm-get-iter-val") (workspace)
                   "Retrieve number of IPM iterations."
                   (cffi:with-foreign-object (ptr :int)
                     (,(lisp-name prec "ocp-qp-ipm-get-iter") workspace ptr)
                     (cffi:mem-ref ptr :int))))))))
  *source-dir*)

(format t "Generated hpipm-wrappers.lisp~%")

;;; ============================================================
;;; Section 10: Generate mpc-demo.lisp (Mass-Spring-Damper)
;;; ============================================================

;; Pre-compute discrete-time system matrices for Coupled Mass-Spring-Damper
;; System parameters:
;;   m1 = 1.0 kg, m2 = 1.0 kg (masses)
;;   k = 1.0 N/m (spring stiffness)
;;   c = 0.1 N/m/s (damper coefficient)
;;   dt = 0.1 s (sampling time)
;; Dynamics equations (continuous):
;;   x1_dot = v1
;;   v1_dot = 1/m1 * (-2k*x1 + k*x2 - 2c*v1 + c*v2 + u)
;;   x2_dot = v2
;;   v2_dot = 1/m2 * (k*x1 - k*x2 + c*v1 - c*v2)
;; Euler discretization: Ad = I + dt * Ac, Bd = dt * Bc
(let* ((k 1.0d0) (c 0.1d0) (dt 0.1d0)
       (ad00 1.0d0)       (ad01 dt)          (ad02 0.0d0)       (ad03 0.0d0)
       (ad10 (* dt -2 k)) (ad11 (+ 1 (* dt -2 c))) (ad12 (* dt k)) (ad13 (* dt c))
       (ad20 0.0d0)       (ad21 0.0d0)       (ad22 1.0d0)       (ad23 dt)
       (ad30 (* dt k))    (ad31 (* dt c))    (ad32 (* dt (- k))) (ad33 (+ 1 (* dt (- c))))
       (bd0 0.0d0) (bd1 dt) (bd2 0.0d0) (bd3 0.0d0))

  (write-source "mpc-demo"
    `(toplevel
      ,@(make-header-comments)
      (comment "================================================================================")
      (comment " MPC Demo: Coupled Mass-Spring-Damper System Stabilizer")
      (comment "================================================================================")
      (comment " This file contains a complete, self-contained Model Predictive Control (MPC)")
      (comment " simulation using the HPIPM high-performance QP solver.")
      (comments
       "System Description:"
       "  We simulate two unit masses (m1 = m2 = 1.0 kg) connected to each other and to the"
       "  walls via springs (stiffness k = 1.0 N/m) and dampers (damping c = 0.1 N/m/s)."
       "  An actuator applies a force 'u' (in Newtons) directly to mass 1."
       ""
       "State Vector Layout (nx = 4):"
       "  x[0] = x1 : position of mass 1 (meters)"
       "  x[1] = v1 : velocity of mass 1 (meters/second)"
       "  x[2] = x2 : position of mass 2 (meters)"
       "  x[3] = v2 : velocity of mass 2 (meters/second)"
       ""
       "Control Vector Layout (nu = 1):"
       "  u[0] = F  : force applied to mass 1 (Newtons)"
       ""
       "Continuous-Time System Equations (Ac & Bc):"
       "  dx1/dt = v1"
       "  dv1/dt = -2*k*x1 - 2*c*v1 + k*x2 + c*v2 + F"
       "  dx2/dt = v2"
       "  dv2/dt = k*x1 + c*v1 - k*x2 - c*v2"
       ""
       "Discrete-Time System Equations (Ad & Bd):"
       "  Derived using Euler integration with sampling time dt = 0.1 seconds:"
       "  x(k+1) = Ad * x(k) + Bd * u(k)"
       ""
       "Optimal Control Problem Formulation (solved at each step):"
       "  minimize   Sum_{k=0..N-1} (x(k)^T * Q * x(k) + u(k)^T * R * u(k)) + x(N)^T * Q_term * x(N)"
       "  subject to x(k+1) = Ad * x(k) + Bd * u(k)"
       "             x(0)   = x0 (current measured state)"
       "             -u_max <= u(k) <= u_max (actuator force constraints)"
       ""
       "HPIPM Lifecycle Steps demonstrated here:"
       "  1. Allocate/initialize OCP QP Dimensions (dim)"
       "  2. Allocate/initialize OCP QP Problem Data (qp) and set matrices (A, B, Q, R, bounds)"
       "  3. Allocate/initialize OCP QP Solution structure (sol)"
       "  4. Allocate/initialize Solver Settings (ipm_arg) and set defaults"
       "  5. Allocate/initialize Solver Workspace (ipm_ws)"
       "  6. Run the solver (d_ocp_qp_ipm_solve)"
       "  7. Extract the optimal controls and predicted trajectories")
      (comment "================================================================================")

      (defpackage :hpipm-demo
        (:use :cl :hpipm)
        (:export :run-mpc-demo))
      (in-package :hpipm-demo)

      (defun run-mpc-demo ()
        "Run the coupled mass-spring-damper MPC simulation."
        (let* ((N 20)      (comment "Prediction horizon (20 steps * 0.1s = 2.0 seconds look-ahead)")
               (nx 4)     (comment "Number of states")
               (nu 1)     (comment "Number of inputs")
               (nbu 1)    (comment "Number of bounded control inputs (u is bounded)")
               (nbx-0 4)  (comment "Number of bounded states at stage 0 (used to lock initial state x0)")
               
               (comment "Discretized dynamics transition matrix Ad")
               (Ad (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,ad00 ,ad01 ,ad02 ,ad03)
                          (list ,ad10 ,ad11 ,ad12 ,ad13)
                          (list ,ad20 ,ad21 ,ad22 ,ad23)
                          (list ,ad30 ,ad31 ,ad32 ,ad33))))
                          
               (comment "Discretized dynamics input matrix Bd")
               (Bd (make-array (quote (4 1))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,bd0) (list ,bd1) (list ,bd2) (list ,bd3))))
                    
               (comment "State cost weighting matrix Q (penalizes deviations from zero)")
               (Q (make-array (quote (4 4))
                   :element-type (quote double-float)
                   :initial-contents
                   (quote ((1.0d0 0.0d0 0.0d0 0.0d0)   (comment "Penalize mass 1 position displacement")
                           (0.0d0 0.1d0 0.0d0 0.0d0)   (comment "Subtle penalty on mass 1 velocity to damp oscillations")
                           (0.0d0 0.0d0 1.0d0 0.0d0)   (comment "Penalize mass 2 position displacement")
                           (0.0d0 0.0d0 0.0d0 0.1d0))))) (comment "Subtle penalty on mass 2 velocity")
                           
               (comment "Control cost weighting matrix R (penalizes actuator effort)")
               (R (make-array (quote (1 1))
                   :element-type (quote double-float)
                   :initial-contents (quote ((0.01d0)))))
                   
               (comment "Constraints: maximum absolute force allowed (Newtons)")
               (u-max 5.0d0)
               
               (comment "Initial state: mass 1 at +1.0m, mass 2 at +0.5m, both stationary")
               (x0 (quote (1.0d0 0.0d0 0.5d0 0.0d0))))

          (format t "~%=== HPIPM MPC Demo: Mass-Spring-Damper ===~%")
          (format t "Horizon N=~a, nx=~a, nu=~a~%" N nx nu)
          (format t "Initial state: ~a~%" x0)

          (comment "----------------------------------------------------------------")
          (comment " Step 1: Set up OCP QP dimensions")
          (comment "----------------------------------------------------------------")
          (call-with-d-ocp-qp-dim N
            (lambda (dim)
              (comment "Loop over all stages to define state, control, and constraint counts")
              (dotimes (k (+ N 1))
                (d-ocp-qp-dim-set-nx k nx dim)
                (if (< k N)
                    (progn
                      (d-ocp-qp-dim-set-nu k nu dim)
                      (comment "We place box constraints on control inputs at stages 0..N-1")
                      (d-ocp-qp-dim-set-nbu k nbu dim))
                    (progn
                      (d-ocp-qp-dim-set-nu k 0 dim)
                      (d-ocp-qp-dim-set-nbu k 0 dim)))
                (comment "We place box constraints on state ONLY at stage 0 (to enforce x0)")
                (if (= k 0)
                    (d-ocp-qp-dim-set-nbx k nbx-0 dim)
                    (d-ocp-qp-dim-set-nbx k 0 dim)))

              (comment "----------------------------------------------------------------")
              (comment " Step 2: Set up OCP QP problem data")
              (comment "----------------------------------------------------------------")
              (call-with-d-ocp-qp dim
                (lambda (qp)
                  (comment "Set dynamics transition, input, and cost matrices for stage 0..N-1")
                  (dotimes (k N)
                    (d-ocp-qp-set-A k Ad qp)
                    (d-ocp-qp-set-B k Bd qp)
                    (d-ocp-qp-set-Q k Q qp)
                    (d-ocp-qp-set-R k R qp)
                    (comment "Enforce bounds on control: index 0 (u) is bounded by [-u-max, u-max]")
                    (d-ocp-qp-set-idxbu k (quote (0)) qp)
                    (d-ocp-qp-set-lbu k (list (- u-max)) qp)
                    (d-ocp-qp-set-ubu k (list u-max) qp))
                  
                  (comment "Set terminal cost at stage N")
                  (d-ocp-qp-set-Q N Q qp)
                  
                  (comment "Enforce initial state constraints: x(0) must equal x0")
                  (comment "We lock all 4 states (indices 0, 1, 2, 3) to the initial value x0")
                  (d-ocp-qp-set-idxbx 0 (quote (0 1 2 3)) qp)
                  (d-ocp-qp-set-lbx 0 x0 qp)
                  (d-ocp-qp-set-ubx 0 x0 qp)

                  (comment "----------------------------------------------------------------")
                  (comment " Step 3: Create solution structure")
                  (comment "----------------------------------------------------------------")
                  (call-with-d-ocp-qp-sol dim
                    (lambda (sol)

                      (comment "----------------------------------------------------------------")
                      (comment " Step 4: Create solver settings / arguments")
                      (comment "----------------------------------------------------------------")
                      (call-with-d-ocp-qp-ipm-arg dim
                        (lambda (arg)
                          (comment "Choose balance mode (trade-off between speed and accuracy)")
                          (d-ocp-qp-ipm-arg-set-default +hpipm-mode-balance+ arg)

                          (comment "----------------------------------------------------------------")
                          (comment " Step 5 & 6: Create solver workspace and solve the QP")
                          (comment "----------------------------------------------------------------")
                          (call-with-d-ocp-qp-ipm-ws dim arg
                            (lambda (ws)
                              (d-ocp-qp-ipm-solve qp sol arg ws)

                              (comment "----------------------------------------------------------------")
                              (comment " Step 7: Extract and print the optimal solution trajectory")
                              (comment "----------------------------------------------------------------")
                              (format t "~%Optimal control force input trajectory u* (Newtons):~%")
                              (dotimes (k N)
                                (let ((uk (d-ocp-qp-sol-get-u k nu sol)))
                                  (format t "  u[~2d] = ~8,4f~%" k (aref uk 0))))
                              
                              (format t "~%Optimal state trajectory x* (predicted positions & velocities):~%")
                              (dotimes (k (+ N 1))
                                (let ((xk (d-ocp-qp-sol-get-x k nx sol)))
                                  (format t "  x[~2d] = [pos1:~8,4f vel1:~8,4f pos2:~8,4f vel2:~8,4f]~%"
                                          k 
                                          (aref xk 0) (aref xk 1)
                                          (aref xk 2) (aref xk 3))))
                              (format t "~%MPC demo complete.~%"))))))))))))))
    *source-dir*))

(format t "Generated mpc-demo.lisp~%")

;;; ============================================================
;;; Section 11: Generate pendulum-demo.lisp (Inverted Pendulum)
;;; ============================================================

;; We now write a second, complete MPC simulation demo for an unstable inverted pendulum on a cart.
;; We will write extensive comments directly in this generator file (using ;; comments) to make the code
;; self-explanatory to developers reading gen01.lisp.
;;
;; Physical Equations and Linearization:
;;   State space: x = [p, v, theta, omega]^T
;;   Parameters:
;;     M = 1.0 kg (cart mass)
;;     m = 0.1 kg (pendulum mass)
;;     l = 0.5 m  (half-pole length)
;;     g = 9.81 m/s^2 (gravity)
;;     b = 0.1 N/m/s (cart damping/friction)
;;   Continuous-time linearized dynamics matrices (Ac & Bc) around upright position (theta = 0):
;;     Ac[1, 1] = - (I + m*l^2)*b / den   where I = 1/3 * m * l^2, den = I*(M+m) + M*m*l^2
;;     Ac[1, 2] = m^2 * l^2 * g / den
;;     Ac[3, 1] = - m*l*b / den
;;     Ac[3, 2] = m*l*(M+m)*g / den
;;   Euler discretized matrices (Ad & Bd) with dt = 0.05 seconds (derived using python script above):
(let* (;; Sampling time of 0.05 seconds is critical for keeping an unstable pendulum stable.
       (dt 0.05d0)
       ;; Ad = I + dt * Ac (Euler discretized transition matrix)
       (pad00 1.00000000d0) (pad01 0.05000000d0) (pad02 0.00000000d0) (pad03 0.00000000d0)
       (pad10 0.00000000d0) (pad11 0.99512195d0) (pad12 0.03589024d0) (pad13 0.00000000d0)
       (pad20 0.00000000d0) (pad21 0.00000000d0) (pad22 1.00000000d0) (pad23 0.05000000d0)
       (pad30 0.00000000d0) (pad31 -0.00731707d0) (pad32 0.78958537d0) (pad33 1.00000000d0)
       ;; Bd = dt * Bc (Euler discretized input matrix)
       (pbd0 0.00000000d0)
       (pbd1 0.04878049d0)
       (pbd2 0.00000000d0)
       (pbd3 0.07317073d0))

  (write-source "pendulum-demo"
    `(toplevel
      ,@(make-header-comments)
      (comment "================================================================================")
      (comment " MPC Demo: Inverted Pendulum on a Cart Stabilizer")
      (comment "================================================================================")
      (comment " This file contains a complete, self-contained Model Predictive Control (MPC)")
      (comment " simulation to balance an unstable inverted pendulum on a moving cart.")
      (comments
       "System Description:"
       "  An unstable pendulum is mounted on a cart. We want to stabilize the pendulum in the"
       "  upright position (theta = 0) and keep the cart at position x = 0 by applying a force"
       "  actuator 'u' directly to the cart."
       ""
       "State Vector Layout (nx = 4):"
       "  x[0] = p     : cart position (meters)"
       "  x[1] = v     : cart velocity (meters/second)"
       "  x[2] = theta : pendulum angle (radians, 0 is upright, positive is tilted right)"
       "  x[3] = omega : pendulum angular velocity (radians/second)"
       ""
       "Control Vector Layout (nu = 1):"
       "  u[0] = F     : force applied to the cart (Newtons)"
       ""
       "Linearized continuous dynamics (around theta=0) with parameters:"
       "  M = 1.0 kg, m = 0.1 kg, l = 0.5 m, g = 9.81 m/s^2, b = 0.1 N/m/s"
       ""
       "Discrete-Time dynamics (Ad & Bd):"
       "  Euler discretized with sampling time dt = 0.05 seconds (20 Hz controller rate)"
       ""
       "Cost Function Weights:"
       "  Penalizes angular deviation heavily to force stabilization, with minor penalty"
       "  on cart position to slowly drift back to center.")
      (comment "================================================================================")

      (defpackage :hpipm-pendulum-demo
        (:use :cl :hpipm)
        (:export :run-pendulum-demo))
      (in-package :hpipm-pendulum-demo)

      (defun run-pendulum-demo ()
        "Run the unstable inverted pendulum MPC stabilization simulation."
        (let* ((N 30)      (comment "Prediction horizon (30 steps * 0.05s = 1.5 seconds look-ahead)")
               (nx 4)     (comment "Number of states")
               (nu 1)     (comment "Number of inputs")
               (nbu 1)    (comment "Number of bounded control inputs (force on cart)")
               (nbx-0 4)  (comment "Number of bounded states at stage 0 (locked to initial condition)")
               
               (comment "Discrete dynamics transition matrix Ad")
               (Ad (make-array (quote (4 4))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,pad00 ,pad01 ,pad02 ,pad03)
                          (list ,pad10 ,pad11 ,pad12 ,pad13)
                          (list ,pad20 ,pad21 ,pad22 ,pad23)
                          (list ,pad30 ,pad31 ,pad32 ,pad33))))
                          
               (comment "Discrete dynamics input matrix Bd")
               (Bd (make-array (quote (4 1))
                    :element-type (quote double-float)
                    :initial-contents
                    (list (list ,pbd0) (list ,pbd1) (list ,pbd2) (list ,pbd3))))
                    
               (comment "State cost matrix Q: penalizes state deviation from center/upright")
               (Q (make-array (quote (4 4))
                   :element-type (quote double-float)
                   :initial-contents
                   (quote ((10.0d0 0.0d0 0.0d0 0.0d0)    (comment "Moderate weight on cart position (keep near 0)")
                           (0.0d0 1.0d0 0.0d0 0.0d0)     (comment "Subtle weight on cart velocity")
                           (0.0d0 0.0d0 100.0d0 0.0d0)   (comment "HEAVY weight on pendulum angle (vital for stabilization!)")
                           (0.0d0 0.0d0 0.0d0 10.0d0))))) (comment "Moderate weight on angular velocity")
                           
               (comment "Control cost matrix R: penalizes high force usage")
               (R (make-array (quote (1 1))
                   :element-type (quote double-float)
                   :initial-contents (quote ((0.1d0)))))
                   
               (comment "Constraint bounds: absolute force on cart limited to 10 Newtons")
               (u-max 10.0d0)
               
               (comment "Initial state x0: Cart centered, stationary. Pendulum tilted right by 0.2 rad (approx 11.5 deg).")
               (x0 (quote (0.0d0 0.0d0 0.2d0 0.0d0))))

          (format t "~%=== HPIPM MPC Demo: Inverted Pendulum on Cart ===~%")
          (format t "Horizon N=~a, nx=~a, nu=~a~%" N nx nu)
          (format t "Initial state: ~a (tilted by ~5,2f deg)~%" x0 (* 0.2d0 (/ 180.0d0 pi)))

          (comment "1. Set up dimensions")
          (call-with-d-ocp-qp-dim N
            (lambda (dim)
              (dotimes (k (+ N 1))
                (d-ocp-qp-dim-set-nx k nx dim)
                (if (< k N)
                    (progn
                      (d-ocp-qp-dim-set-nu k nu dim)
                      (d-ocp-qp-dim-set-nbu k nbu dim))
                    (progn
                      (d-ocp-qp-dim-set-nu k 0 dim)
                      (d-ocp-qp-dim-set-nbu k 0 dim)))
                (if (= k 0)
                    (d-ocp-qp-dim-set-nbx k nbx-0 dim)
                    (d-ocp-qp-dim-set-nbx k 0 dim)))

              (comment "2. Set up QP data")
              (call-with-d-ocp-qp dim
                (lambda (qp)
                  (dotimes (k N)
                    (d-ocp-qp-set-A k Ad qp)
                    (d-ocp-qp-set-B k Bd qp)
                    (d-ocp-qp-set-Q k Q qp)
                    (d-ocp-qp-set-R k R qp)
                    (d-ocp-qp-set-idxbu k (quote (0)) qp)
                    (d-ocp-qp-set-lbu k (list (- u-max)) qp)
                    (d-ocp-qp-set-ubu k (list u-max) qp))
                  (d-ocp-qp-set-Q N Q qp)
                  
                  (comment "Lock initial state constraints at stage 0")
                  (d-ocp-qp-set-idxbx 0 (quote (0 1 2 3)) qp)
                  (d-ocp-qp-set-lbx 0 x0 qp)
                  (d-ocp-qp-set-ubx 0 x0 qp)

                  (comment "3. Create solution struct")
                  (call-with-d-ocp-qp-sol dim
                    (lambda (sol)

                      (comment "4. Create solver arguments")
                      (call-with-d-ocp-qp-ipm-arg dim
                        (lambda (arg)
                          (d-ocp-qp-ipm-arg-set-default +hpipm-mode-balance+ arg)

                          (comment "5. Create workspace and solve")
                          (call-with-d-ocp-qp-ipm-ws dim arg
                            (lambda (ws)
                              (d-ocp-qp-ipm-solve qp sol arg ws)

                              (comment "6. Extract and print results")
                              (format t "~%Optimal force trajectory u* (Newtons):~%")
                              (dotimes (k N)
                                (let ((uk (d-ocp-qp-sol-get-u k nu sol)))
                                  (format t "  u[~2d] = ~8,4f~%" k (aref uk 0))))
                                  
                              (format t "~%Optimal state trajectory x* (predicted cart position & pole angle):~%")
                              (dotimes (k (+ N 1))
                                (let ((xk (d-ocp-qp-sol-get-x k nx sol)))
                                  (format t "  x[~2d] = [cart_pos:~8,4f cart_vel:~8,4f pole_ang:~8,4f pole_vel:~8,4f]~%"
                                          k 
                                          (aref xk 0) (aref xk 1)
                                          (aref xk 2) (aref xk 3))))
                              (format t "~%Inverted pendulum stabilization complete.~%"))))))))))))))
    *source-dir*))

(format t "Generated pendulum-demo.lisp~%")

;;; ============================================================
;;; Done
;;; ============================================================

(format t "~%=== Generation complete ===~%")
(format t "Output directory: ~a~%" *source-dir*)
(format t "Precisions: ~{~a~^, ~}~%" (mapcar #'fifth *precisions*))
(format t "Dim setter fields: ~a~%" (length *dim-fields*))
(format t "QP setter fields:  ~a~%" (length *qp-fields*))
(format t "Sol getter fields: ~a~%" (length *sol-fields*))
(format t "Lifecycle objects: ~a~%" (length *lifecycle-objects*))
(let ((per-prec (+ (* 2 (length *lifecycle-objects*))  ; memsize + create
                   3                                     ; dim-set, qp-set, sol-get
                   2                                     ; solve, set-default
                   (length *dim-fields*)
                   (length *qp-fields*)
                   (length *sol-fields*)
                   (length *lifecycle-objects*))))       ; call-with-*
  (format t "Functions per precision: ~a~%" per-prec)
  (format t "Total generated functions: ~a~%" (* 2 per-prec)))

