;;;; p02_arith --- integer operators, CL division semantics, precedence,
;;;; float formatting and bit operators

(in-package :polyglot-user)
(in-dsl)

(defmodule arith (:entry t)
  (defun show (label value)
    (declare (type :string label) (type :i64 value))
    (print-line (format-string "{} = {}" label value)))

  (defun show-float (label value)
    (declare (type :string label) (type :f64 value))
    (print-line (format-string "{} = {:.6f}" label value)))

  (defun main ()
    (let ((a 17) (b -5) (c 3) (d 2))
      (show "a + b * c" (+ a (* b c)))
      (show "(a + b) * c" (* (+ a b) c))
      (show "a - (b - c)" (- a (- b c)))
      (show "a - b - c" (- (- a b) c))
      (show "-(a - d)" (- (- a d)))
      (show "truncate 17 -5" (truncate a b))
      (show "floor 17 -5" (floor a b))
      (show "mod 17 -5" (mod a b))
      (show "rem 17 -5" (rem a b))
      (show "truncate -17 5" (truncate (- a) 5))
      (show "floor -17 5" (floor (- a) 5))
      (show "mod -17 5" (mod (- a) 5))
      (show "rem -17 5" (rem (- a) 5))
      (show "logand 12 10" (logand 12 10))
      (show "logior 12 10" (logior 12 10))
      (show "logxor 12 10" (logxor 12 10))
      (show "lognot 12" (lognot 12))
      (show "shl 1 10" (shl 1 10))
      (show "shr 1024 3" (shr 1024 3))
      (show "a*c + b*d - a" (- (+ (* a c) (* b d)) a))
      (show "max/min/abs" (+ (max a c) (min b d) (abs b)))
      (show-float "a / 4.0" (/ (to-float a) 4d0))
      (show-float "sqrt 2" (sqrt 2d0))
      (show-float "1/3" (/ 1d0 3d0))
      (show-float "-2.5 * 4" (* -2.5d0 4))
      (show "floor 7.9" (floor 7.9d0))
      (show "truncate -7.9" (truncate -7.9d0))
      (when (and (> a c) (or (< b 0) (= c 0)) (not (= a b)))
        (print-line "logic ok")))))

(defproject arith (:modules arith) (:entry arith))
