;;;; 80-artifacts.lisp --- artifacts: what a backend wants written

(in-package :polyglot)

(defstruct artifact
  "One output file. PATH is relative to the backend directory, KIND one of
:source :header :build :prelude, CONTENT the text without header comment."
  path kind content)

(defun artifact-extension (artifact)
  (let ((path (artifact-path artifact)))
    (cond ((search "CMakeLists.txt" path) "cmake")
          (t (or (pathname-type (pathname path)) "")))))

(defun comment-prefix (artifact)
  "Line comment syntax for the file type of ARTIFACT."
  (let ((ext (artifact-extension artifact)))
    (cond ((member ext '("hpp" "cpp" "h" "rs" "go" "mod") :test #'string=) "//")
          ((member ext '("py" "toml" "cmake" "txt") :test #'string=) "#")
          ((member ext '("lisp" "asd") :test #'string=) ";;")
          (t nil))))

(defun header-comment (artifact source-info)
  "The generated-file header. Go recognizes the 'Code generated ... DO NOT EDIT.' form."
  (let ((prefix (comment-prefix artifact)))
    (when prefix
      (format nil "~a Code generated by polyglot-generator. DO NOT EDIT.~%~
                   ~a Source: ~a (git blob ~a)~%"
              prefix prefix (getf source-info :file "unknown") (getf source-info :hash "unknown")))))
