// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
// Package shapes is generated from the DSL module of the same name.
package shapes

import (
	"fmt"
)

// Shape Something with an area.
type Shape interface {
	Area() float64
	Label() string
	Describe() string
}

func ShapeDescribe(s Shape) string {
	return fmt.Sprintf("%s with area %.2f", s.Label(), s.Area())
}

type Circle struct {
	R float64
}

func (c *Circle) Area() float64 {
	return 3.0 * c.R * c.R
}

func (c *Circle) Label() string {
	return "circle"
}

func (s *Circle) Describe() string {
	return ShapeDescribe(s)
}

type Rect struct {
	W float64
	H float64
}

func (r *Rect) Area() float64 {
	return r.W * r.H
}

func (r *Rect) Label() string {
	return "rect"
}

func (s *Rect) Describe() string {
	return ShapeDescribe(s)
}

// TotalArea Sum of the areas of all shapes.
func TotalArea(items []Shape) float64 {
	sum := 0.0
	for _, s := range items {
		sum += s.Area()
	}
	return sum
}
