(eval-when (:compile-toplevel :execute :load-toplevel)
  ;; Load the local generator system
  (push "/home/kiel/stage/cl-cl-generator/" asdf:*central-registry*)
  (ql:quickload :cl-cl-generator))

(defpackage :cl-cl-generator/example
  (:use :cl :cl-cl-generator))

(in-package :cl-cl-generator/example)

(defparameter *output-dir* (asdf:system-relative-pathname :cl-cl-generator "example/00_test/"))
(defparameter *output-filename* "run_example")

(let* ((git-version
         (handler-case
             (let ((str (with-output-to-string (s)
                          (sb-ext:run-program "/usr/bin/git"
                                              '("rev-parse" "HEAD")
                                              :output s))))
               (string-trim '(#\Space #\Tab #\Newline #\Return) str))
           (error () "unknown-git-revision")))
       
       (generation-time
         (multiple-value-bind (second minute hour date month year day-of-week dst-p tz)
             (get-decoded-time)
           (declare (ignorable dst-p))
           (let ((days '("Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday" "Sunday")))
             (format nil "~2,'0d:~2,'0d:~2,'0d on ~a, ~d-~2,'0d-~2,'0d (GMT~@d)"
                     hour minute second (nth day-of-week days) year month date (- tz)))))

       (code
         `(toplevel
            (comment "This file is auto-generated by cl-cl-generator. DO NOT EDIT MANUALLY.")
            (comments ,(format nil "Generated at: ~a" generation-time)
                      ,(format nil "Git commit:    ~a" git-version))
            
            (in-package :cl-user)
            
            (comment "A basic mathematical helper")
            (defun add-three (x)
              (+ x 3))
            
            (comment "A more complex helper using optional parameters and bindings")
            (defun compute-power (base &optional (exponent 2))
              (let ((result (expt base exponent)))
                (comments "Check if result is extremely large"
                          "and return optionally scaled value")
                (cond
                  ((> result 1000)
                   (comment "Scale down huge values")
                   (/ result 10))
                  (t result)))))))
  
  (let ((result-path (write-source *output-filename* code *output-dir*)))
    (format t "Successfully generated Lisp source at ~a~%" result-path)))
