// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
#include <format>
#include <iostream>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "polyglot_rt.hpp"
#include "shapes.hpp"

namespace {
struct Widget {
  double x = 0.0;
  double y = 0.0;
  Widget(double x, double y) : x(x), y(y) {}
  virtual ~Widget() = default;
  virtual double width() const;
  virtual std::string kind() const;
  std::string render() const;
  void move_to(double nx, double ny);
};

struct Button : public Widget {
  std::string caption = "";
  Button(double x, double y, std::string caption)
      : Widget(x, y), caption(std::move(caption)) {}
  double width() const override;
  std::string kind() const override;
};
} // namespace

namespace {
double Widget::width() const { return 1.0; }

std::string Widget::kind() const { return "widget"; }

std::string Widget::render() const {
  const std::string arg_1 = kind();
  const double arg_2 = width();
  return std::format("{} at ({:.1f}, {:.1f}) width {:.1f}", arg_1, x, y, arg_2);
}

void Widget::move_to(double nx, double ny) {
  x = nx;
  y = ny;
}

double Button::width() const {
  return Widget::width() +
         static_cast<double>(polyglot_rt::utf8_char_count(caption));
}

std::string Button::kind() const {
  return std::string("button '") + caption + "'";
}
} // namespace

int main() {
  {
    const std::vector<std::unique_ptr<shapes::Shape>> items =
        polyglot_rt::make_vec<std::unique_ptr<shapes::Shape>>(
            std::make_unique<shapes::Circle>(2.0),
            std::make_unique<shapes::Rect>(3.0, 4.0));
    for (const auto &s : items) {
      std::cout << s->describe() << '\n';
    }
    std::cout << std::format("total area = {:.2f}", shapes::total_area(items))
              << '\n';
  }
  std::vector<std::unique_ptr<Widget>> ui =
      polyglot_rt::make_vec<std::unique_ptr<Widget>>(
          std::make_unique<Widget>(0.0, 0.0),
          std::make_unique<Button>(0.0, 0.0, "OK"));
  for (std::int64_t i = 0; i < static_cast<std::int64_t>(ui.size()); ++i) {
    ui[i]->move_to(static_cast<double>(10 * i), 5.0);
  }
  for (const auto &w : ui) {
    std::cout << w->render() << '\n';
  }
}
