// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
#pragma once

#include <cstdint>
#include <string_view>
#include <utility>
#include <vector>

namespace polyglot_rt {

// Number of Unicode code points of a UTF-8 string.
inline std::int64_t utf8_char_count(std::string_view s) {
  std::int64_t n = 0;
  for (const char c : s) {
    if ((static_cast<unsigned char>(c) & 0xC0U) != 0x80U) {
      ++n;
    }
  }
  return n;
}

// A vector of move-only values (std::initializer_list would copy).
template <typename T, typename... Args>
std::vector<T> make_vec(Args &&...args) {
  std::vector<T> v;
  v.reserve(sizeof...(args));
  (v.emplace_back(std::forward<Args>(args)), ...);
  return v;
}

} // namespace polyglot_rt
