// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
#include "shapes.hpp"

#include <format>
#include <memory>
#include <string>
#include <vector>

namespace shapes {
std::string Shape::describe() const {
  const std::string arg_1 = label();
  const double arg_2 = area();
  return std::format("{} with area {:.2f}", arg_1, arg_2);
}

double Circle::area() const { return 3.0 * r * r; }

std::string Circle::label() const { return "circle"; }

double Rect::area() const { return w * h; }

std::string Rect::label() const { return "rect"; }

double total_area(const std::vector<std::unique_ptr<Shape>> &items) {
  double sum = 0.0;
  for (const auto &s : items) {
    sum += s->area();
  }
  return sum;
}

} // namespace shapes
