// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
#pragma once

#include <memory>
#include <string>
#include <vector>

namespace shapes {

struct Shape {
  virtual ~Shape() = default;
  virtual double area() const = 0;
  virtual std::string label() const = 0;
  virtual std::string describe() const;
};

struct Circle : public Shape {
  double r = 1.0;
  explicit Circle(double r) : r(r) {}
  double area() const override;
  std::string label() const override;
};

struct Rect : public Shape {
  double w = 1.0;
  double h = 1.0;
  Rect(double w, double h) : w(w), h(h) {}
  double area() const override;
  std::string label() const override;
};

double total_area(const std::vector<std::unique_ptr<Shape>> &items);

} // namespace shapes
