;;;; 01_package.lisp — Package and Helper Setup for Expanse Combat Game Generator

(eval-when (:compile-toplevel :execute :load-toplevel)
  (let ((current-dir (make-pathname :directory (pathname-directory *load-pathname*))))
    ;; Push local ASDF system paths to central registry
    (push (merge-pathnames "../../" current-dir) asdf:*central-registry*)
    (push (merge-pathnames "../06_hpipm_cffi/source01/" current-dir) asdf:*central-registry*)
    (push (merge-pathnames "../07_pure_x11/source/" current-dir) asdf:*central-registry*))
  (ql:quickload '(:cl-cl-generator :pure-x11-gen :hpipm)))

(defpackage :cl-cl-generator/example-expanse-gen
  (:use :cl :cl-cl-generator))
(in-package :cl-cl-generator/example-expanse-gen)

(defparameter *output-dir*
  (merge-pathnames "source/"
                   (make-pathname :directory (pathname-directory *load-pathname*))))

(defparameter *git-version*
  (handler-case
      (string-trim '(#\Space #\Tab #\Newline #\Return)
                   (with-output-to-string (s)
                     (sb-ext:run-program "/usr/bin/git" '("rev-parse" "HEAD")
                                          :output s)))
    (error () "unknown")))

(defparameter *generation-time*
  (multiple-value-bind (sec min hour day month year)
      (get-decoded-time)
    (format nil "~4d-~2,'0d-~2,'0d ~2,'0d:~2,'0d:~2,'0d"
            year month day hour min sec)))

(defun make-header-comments ()
  (list `(comment "Auto-generated by cl-cl-generator — do not edit manually.")
        `(comments ,(format nil "Generated: ~a" *generation-time*)
                   ,(format nil "Git:       ~a" *git-version*))))
