;;;; expr.lisp --- Go backend: expressions and call arguments

(in-package :polyglot)

(defun go-struct-pointer-param-p (var)
  (and (eq :param (ir-kind var)) (eq :inout (ir-mode var))
       (or (named-type-p (ir-ty var)) (eq :map (type-head (ir-ty var))))))

(defmethod emit-expr ((b go-backend) (e lit-expr))
  (let ((v (ir-value e)))
    (ecase (ir-kind e)
      (:int (values (princ-to-string v) (literal-op v)))
      (:float (values (float-literal v) (literal-op v)))
      (:string (prim (string-literal v :go)))
      (:char (prim (char-literal v :go)))
      (:bool (prim (if v "true" "false")))
      (:nil (prim (or (and (member (type-head (ir-ty e)) '(:vec :map)) (go-zero-value (ir-ty e))) "nil"))))))

(defmethod emit-expr ((b go-backend) (e var-expr))
  (let ((binding (ir-binding e)))
    (cond ((not (typep binding 'var-def)) (prim (go-item-ref binding)))
          ((and (eq :param (ir-kind binding)) (eq :inout (ir-mode binding))
                (not (go-struct-pointer-param-p binding)))
           (values (format nil "*~a" (ir-target-name binding)) :deref))
          (t (prim (ir-target-name binding))))))

(defmethod emit-expr ((b go-backend) (e op-expr))
  (let ((args (ir-args e)))
    (case (ir-op e)
      ((:neg :bitnot :not) (unary (ir-op e) (first args)))
      (t (binary (ir-op e) (first args) (second args))))))

(defun addressable-p (e) (typep e '(or var-expr field-expr aref-expr)))

(defun go-arg (a p)
  "Argument A for parameter P: &x for :inout, *p when a pointer is passed by value."
  (let ((ty (ir-ty p)))
    (cond ((eq :inout (ir-mode p))
           (cond ((eq :map (type-head ty)) (ex-str a))
                 ((and (typep a 'var-expr) (typep (ir-binding a) 'var-def)
                       (eq :param (ir-kind (ir-binding a))) (eq :inout (ir-mode (ir-binding a))))
                  (ir-target-name (ir-binding a)))
                 ((addressable-p a) (format nil "&~a" (operand :addr :only a)))
                 (t (unsupported (ir-source a) ":inout argument must be a variable or place"))))
          ((and (go-pointer-value-p a) (not (go-pointer-type-p ty)) (not (member (type-head ty) '(:ref :mut-ref))))
           (values (unary-string +go-ops+ :deref (ex-pair a) *mode*)))
          ((and (member (type-head ty) '(:ref :mut-ref)) (not (eq :dyn (type-head (second ty))))
                (not (go-pointer-value-p a)) (addressable-p a))
           (format nil "&~a" (operand :addr :only a)))
          (t (ex-str a)))))

(defun go-pointer-type-p (ty)
  (or (eq :optional (type-head ty))
      (and (eq :box (type-head ty)) (not (eq :dyn (type-head (second ty)))))))

(defun go-args (args params)
  (format nil "~{~a~^, ~}" (loop for a in args for p in params collect (go-arg a p))))

(defmethod emit-expr ((b go-backend) (e call-expr))
  (ecase (ir-call-kind e)
    (:function (prim (format nil "~a(~a)" (go-item-ref (ir-target e)) (go-args (ir-args e) (ir-params (ir-target e))))))
    (:extern (go-extern-call e))
    (:intrinsic (emit-intrinsic e))))

(defun go-extern-call (e)
  (let* ((item (ir-target e))
         (spec (or (cdr (assoc :go (ir-expansions item)))
                   (unsupported (ir-source e) "extern ~a has no :go spelling" (ir-name item)))))
    (dolist (i (getf (cdr spec) :imports)) (note-import (list :std i)))
    (prim (format nil "~a(~a)" (first spec) (comma-list (ir-args e))))))

(defmethod emit-expr ((b go-backend) (e method-call-expr))
  (let ((m (ir-target e)))
    (prim (format nil "~a.~a(~a)" (receiver (ir-receiver e)) (ir-target-name m)
                  (go-args (ir-args e) (rest (ir-params m)))))))

(defmethod emit-expr ((b go-backend) (e field-expr))
  (prim (format nil "~a.~a" (receiver (ir-object e)) (ir-target-name (ir-target e)))))

(defmethod emit-expr ((b go-backend) (e aref-expr))
  (prim (format nil "~a[~a]" (receiver (ir-object e)) (ex-str (ir-index e)))))

(defun go-field-value (field value)
  (let ((ty (ir-ty field)))
    (if (and (member (type-head ty) '(:ref :mut-ref)) (not (eq :dyn (type-head (second ty))))
             (not (go-pointer-value-p value)))
        (format nil "&~a" (operand :addr :only value))
        (go-arg value (make-var-def :name "field" :kind :param :mode :in :ty ty)))))

(defmethod emit-expr ((b go-backend) (e make-expr))
  (let ((item (ir-target e)))
    (prim (format nil "~a{~{~a~^, ~}}" (go-item-ref item)
                  (loop for f in (ir-fields item)
                        for init = (make-init-for e f)
                        when init collect (format nil "~a: ~a" (ir-target-name f) (go-field-value f (ir-value init)))
                        else when (ir-default f)
                        collect (format nil "~a: ~a" (ir-target-name f) (go-field-value f (ir-default f))))))))

(defmethod emit-expr ((b go-backend) (e vec-expr))
  (prim (format nil "[]~a{~a}" (go-type (ir-elem-type e)) (comma-list (ir-elems e)))))

(defmethod emit-expr ((b go-backend) (e map-expr))
  (prim (format nil "~a{}" (go-type (ir-ty e)))))

(defun go-clone (e)
  (let ((v (ir-value e)) (ty (ir-ty e)))
    (case (type-head ty)
      (:vec (note-import (list :std "slices")) (prim (format nil "slices.Clone(~a)" (ex-str v))))
      (:map (note-import (list :std "maps")) (prim (format nil "maps.Clone(~a)" (ex-str v))))
      (t (if (go-pointer-value-p v)
             (values (unary-string +go-ops+ :deref (ex-pair v) *mode*))
             (ex v))))))

(defmethod emit-expr ((b go-backend) (e own-expr))
  (let ((v (ir-value e)))
    (ecase (ir-kind e)
      (:move (ex v))
      (:clone (go-clone e))
      ((:box :some)
       (cond ((eq :dyn (type-head (strip-indirection (ir-ty v))))
              (ex v))
             ((typep v 'make-expr)
              (values (format nil "&~a" (ex-str v)) :addr))
             (t (note-prelude "Ptr")
                (prim (format nil "polyglotrt.Ptr(~a)" (ex-str v)))))))))

(defmethod emit-expr ((b go-backend) (e funcall-expr))
  (prim (format nil "~a(~a)" (receiver (ir-fn e)) (comma-list (ir-args e)))))

(defmethod emit-expr ((b go-backend) (e raw-expr)) (prim (ir-text e)))

(defmethod emit-expr ((b go-backend) (e target-form-expr))
  (let ((form (ir-form e)))
    (if (and (form-is (car form) "raw") (stringp (second form)))
        (prim (second form))
        (unsupported form "unknown go: form"))))
