;;;; types.lisp --- Go backend: types, parameter modes, pointer values

(in-package :polyglot)

(defvar *go-module* nil "Module being emitted.")
(defvar *go-project* nil "Project being emitted.")
(defvar *go-loop-pointers*)
(defvar *go-pointer-receiver* nil "Receiver var-def of a method with a pointer receiver.")

(defun go-item-ref (item)
  "Name of ITEM as seen from *GO-MODULE* (package qualified when foreign)."
  (let ((module (ir-module item)))
    (if (or (null module) (eq module *go-module*))
        (ir-target-name item)
        (progn (note-import (list :pkg (ir-target-name module)))
               (format nil "~a.~a" (ir-target-name module) (ir-target-name item))))))

(defun go-type (ty)
  (cond ((member ty '(:i8 :i16 :i32 :i64 :u8 :u16 :u32 :u64))
         (format nil "~:[int~;uint~]~d" (char= #\U (char (symbol-name ty) 0))
                 (parse-integer (symbol-name ty) :start 1)))
        ((eq ty :f64) "float64")
        ((eq ty :f32) "float32")
        ((eq ty :bool) "bool")
        ((eq ty :char) "rune")
        ((eq ty :string) "string")
        ((eq ty :void) "")
        ((not (consp ty)) "any")
        (t (go-compound-type ty))))

(defun go-compound-type (ty)
  (ecase (car ty)
    (:vec (format nil "[]~a" (go-type (second ty))))
    (:array (format nil "[~d]~a" (third ty) (go-type (second ty))))
    (:map (format nil "map[~a]~a" (go-type (second ty)) (go-type (third ty))))
    (:optional (format nil "*~a" (go-type (second ty))))
    (:box (if (eq :dyn (type-head (second ty))) (go-type (second ty)) (format nil "*~a" (go-type (second ty)))))
    (:dyn (go-item-ref (third ty)))
    (:named (go-item-ref (third ty)))
    (:fn (format nil "func(~{~a~^, ~})~@[ ~a~]" (mapcar #'go-type (second ty))
                 (let ((r (go-type (third ty)))) (and (plusp (length r)) r))))
    ((:ref :mut-ref) (if (eq :dyn (type-head (second ty)))
                         (go-type (second ty))
                         (format nil "*~a" (go-type (second ty)))))
    (:view (if (eq :string (second ty)) "string" (format nil "[]~a" (go-type (second (second ty))))))
    (:raw (if (eq (second ty) :go) (third ty) (unsupported ty "raw type for another backend")))))

(defun go-param-type (var)
  "K1: :in -> T, :inout -> *T (maps are references already), :sink -> T."
  (let ((ty (ir-ty var)))
    (if (and (eq :inout (ir-mode var)) (not (eq :map (type-head ty))))
        (format nil "*~a" (go-type ty))
        (go-type ty))))

(defun go-pointer-value-p (e)
  "The Go value of E is a pointer to the DSL value (deref with * for copies)."
  (let ((ty (ir-ty e)))
    (or (and (typep e 'var-expr) (typep (ir-binding e) 'var-def)
             (or (and (eq :param (ir-kind (ir-binding e))) (eq :inout (ir-mode (ir-binding e)))
                      (not (eq :map (type-head ty))))
                 (member (ir-binding e) *go-loop-pointers*)
                 (eq (ir-binding e) *go-pointer-receiver*)))
        (and (member (type-head ty) '(:box :ref :mut-ref))
             (not (eq :dyn (type-head (second ty))))))))

(defun go-zero-value (ty)
  (cond ((numeric-type-p ty) "0")
        ((eq ty :bool) "false")
        ((eq ty :string) "\"\"")
        ((eq ty :char) "' '")
        ((member (type-head ty) '(:vec :map)) (format nil "~a{}" (go-type ty)))
        (t nil)))
