# Code generated by polyglot-generator. DO NOT EDIT.
# Source: project.lisp (git blob f2715e5101)
"""Module app."""

from dataclasses import dataclass

from shapes import Circle, Rect, total_area


@dataclass
class Widget:
    x: float = 0.0
    y: float = 0.0

    def width(self) -> float:
        return 1.0

    def kind(self) -> str:
        return "widget"

    def render(self) -> str:
        return f"{self.kind()} at ({self.x:.1f}, {self.y:.1f}) width {self.width():.1f}"

    def move_to(self, nx: float, ny: float) -> None:
        self.x = nx
        self.y = ny


@dataclass
class Button(Widget):
    caption: str = ""

    def width(self) -> float:
        return super().width() + float(len(self.caption))

    def kind(self) -> str:
        return "button '" + self.caption + "'"


def main() -> None:
    items = [Circle(r=2.0), Rect(w=3.0, h=4.0)]
    for s in items:
        print(s.describe())
    print(f"total area = {total_area(items):.2f}")
    ui = [Widget(), Button(caption="OK")]
    for i in range(len(ui)):
        ui[i].move_to(float(10 * i), 5.0)
    for w in ui:
        print(w.render())


if __name__ == "__main__":
    main()
