# Code generated by polyglot-generator. DO NOT EDIT.
# Source: project.lisp (git blob f2715e5101)
"""Module shapes."""

from abc import ABC, abstractmethod
from dataclasses import dataclass


class Shape(ABC):
    """Something with an area."""

    @abstractmethod
    def area(self) -> float: ...

    @abstractmethod
    def label(self) -> str: ...

    def describe(self) -> str:
        return f"{self.label()} with area {self.area():.2f}"


@dataclass
class Circle(Shape):
    r: float = 1.0

    def area(self) -> float:
        return 3.0 * self.r * self.r

    def label(self) -> str:
        return "circle"


@dataclass
class Rect(Shape):
    w: float = 1.0
    h: float = 1.0

    def area(self) -> float:
        return self.w * self.h

    def label(self) -> str:
        return "rect"


def total_area(items: list[Shape]) -> float:
    """Sum of the areas of all shapes."""
    sum = 0.0
    for s in items:
        sum += s.area()
    return sum


__all__ = ["Circle", "Rect", "Shape", "total_area"]
