// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
package main

import (
	"fmt"
	"unicode/utf8"

	"shapes_demo/shapes"
)

type widgetDyn interface {
	widget() *widget
	widgetMut() *widget
	width() float64
	kind() string
}

type widget struct {
	x float64
	y float64
}

func (w *widget) widget() *widget {
	return w
}

func (w *widget) widgetMut() *widget {
	return w
}

func (w *widget) width() float64 {
	return widgetWidth(w)
}

func (w *widget) kind() string {
	return widgetKind(w)
}

func widgetWidth(this widgetDyn) float64 {
	return 1.0
}

func widgetKind(this widgetDyn) string {
	return "widget"
}

func widgetRender(this widgetDyn) string {
	return fmt.Sprintf("%s at (%.1f, %.1f) width %.1f", this.kind(), this.widget().x, this.widget().y, this.width())
}

func widgetMoveTo(this widgetDyn, nx float64, ny float64) {
	this.widgetMut().x = nx
	this.widgetMut().y = ny
}

type buttonDyn interface {
	widgetDyn
	button() *button
}

type button struct {
	base    widget
	caption string
}

func (b *button) button() *button {
	return b
}

func (b *button) widget() *widget {
	return &b.base
}

func (b *button) widgetMut() *widget {
	return &b.base
}

func (b *button) width() float64 {
	return buttonWidth(b)
}

func (b *button) kind() string {
	return buttonKind(b)
}

func buttonWidth(this buttonDyn) float64 {
	return widgetWidth(this) + float64(int64(utf8.RuneCountInString(this.button().caption)))
}

func buttonKind(this buttonDyn) string {
	return "button '" + this.button().caption + "'"
}

func main() {
	{
		items := []shapes.Shape{&shapes.Circle{R: 2.0}, &shapes.Rect{W: 3.0, H: 4.0}}
		for _, s := range items {
			fmt.Println(s.Describe())
		}
		fmt.Printf("total area = %.2f\n", shapes.TotalArea(items))
	}
	ui := []widgetDyn{&widget{x: 0.0, y: 0.0}, &button{base: widget{x: 0.0, y: 0.0}, caption: "OK"}}
	for i := int64(0); i < int64(len(ui)); i++ {
		widgetMoveTo(ui[i], float64(10*i), 5.0)
	}
	for _, w := range ui {
		fmt.Println(widgetRender(w))
	}
}
