;;;; 03_widgets_template.lisp — Widgets toolkit template specification

(in-package :cl-cl-generator/example-x11-gen)

(defparameter *widgets-template-code*
  `(toplevel
     ,@(make-header-comments)
     (in-package :pure-x11-gen)

     (defstruct widget
       type
       name
       x y w h
       props
       children)

     (defun parse-node (node)
       "Parse a layout node into properties and children."
       (let ((type (car node))
             (name nil)
             (x 0) (y 0) (w 0) (h 0)
             (props nil)
             (tail (cdr node)))
         (loop while (and tail (keywordp (car tail))) do
           (let ((key (pop tail))
                 (val (pop tail)))
             (case key
               (:name (setf name val))
               (:x (setf x val))
               (:y (setf y val))
               (:w (setf w val))
               (:h (setf h val))
               (t (setf props (list* key val props))))))
         (make-widget :type type :name name :x x :y y :w w :h h :props props :children tail)))

     (defun collect-focusable-widgets (layout)
       "Recursively traverse the layout tree to collect all focusable widgets."
       (let ((result nil))
         (labels ((traverse (node)
                    (when (listp node)
                      (let ((w-struct (parse-node node)))
                        (when (let ((type (widget-type w-struct)))
                               (and type (symbolp type)
                                    (member (symbol-name type) '("BUTTON" "CHECKBOX" "TEXT-INPUT") :test #'string-equal)))
                          (push w-struct result))
                        (dolist (child (widget-children w-struct))
                          (traverse child))))))
           (traverse layout))
         (nreverse result)))

     (defun find-widget-at (layout mx my)
       "Recursively search the layout list for the leaf widget enclosing the mouse coordinates (mx, my)."
       (let ((found nil))
         (labels ((search-layout (node)
                    (when (listp node)
                      (let ((w-struct (parse-node node)))
                        (let ((x (widget-x w-struct))
                              (y (widget-y w-struct))
                              (w (widget-w w-struct))
                              (h (widget-h w-struct)))
                          (when (and (>= mx x) (< mx (+ x w))
                                     (>= my y) (< my (+ y h)))
                            (setf found w-struct)
                            (dolist (child (widget-children w-struct))
                              (search-layout child))))))))
           (search-layout layout))
         found))

     (defun find-widget-by-name (layout target-name)
       "Find a widget in the layout tree by its name."
       (let ((found nil))
         (labels ((search-layout (node)
                    (when (listp node)
                      (let ((w-struct (parse-node node)))
                        (if (eq (widget-name w-struct) target-name)
                            (setf found w-struct)
                            (dolist (child (widget-children w-struct))
                              (search-layout child)))))))
           (search-layout layout))
         found))

     (defun find-nearest-widget (layout current-name direction)
       "Find the next widget to focus from current-name in direction (:up, :down, :left, :right)."
       (let* ((widgets (collect-focusable-widgets layout))
              (current (find current-name widgets :key #'widget-name))
              (best nil)
              (best-dist nil))
         (unless current
           (return-from find-nearest-widget (and widgets (widget-name (car widgets)))))
         (let ((cx (+ (widget-x current) (/ (widget-w current) 2)))
               (cy (+ (widget-y current) (/ (widget-h current) 2)))
               (dir-vec (ecase direction
                          (:right '(1 0))
                          (:left '(-1 0))
                          (:down '(0 1))
                          (:up '(0 -1)))))
           (dolist (w widgets)
             (unless (eq (widget-name w) current-name)
               (let* ((tx (+ (widget-x w) (/ (widget-w w) 2)))
                      (ty (+ (widget-y w) (/ (widget-h w) 2)))
                      (dx (- tx cx))
                      (dy (- ty cy))
                      (dist (+ (* dx dx) (* dy dy))))
                 (let* ((dot (+ (* dx (car dir-vec)) (* dy (cadr dir-vec)))))
                   (when (> dot 0)
                     (let* ((cross (- (* dx (cadr dir-vec)) (* dy (car dir-vec))))
                            (in-cone-p (>= dot (abs cross))))
                       (when in-cone-p
                         (when (or (null best-dist) (< dist best-dist))
                           (setf best-dist dist
                                 best (widget-name w)))))))))))
         best))

     (defun translate-keycode (keyboard-map keycode state-mask)
       "Translate X11 keycode and shift modifier state to a Lisp character or keyword symbol."
       (let* ((first-keycode (car keyboard-map))
              (keysy-per-keycode (cadr keyboard-map))
              (map-data (caddr keyboard-map))
              (idx (- keycode first-keycode)))
         (when (and (>= idx 0) (< idx (/ (length map-data) keysy-per-keycode)))
           (let* ((offset (* idx keysy-per-keycode))
                  (shift-p (/= 0 (logand state-mask 1)))
                  (keysym-code (aref map-data (+ offset (if shift-p 1 0)))))
             (cond
               ((and (>= keysym-code 32) (<= keysym-code 126))
                (code-char keysym-code))
               ((= keysym-code #xff08) :backspace)
               ((= keysym-code #xff0d) :return)
               ((= keysym-code #xff51) :left)
               ((= keysym-code #xff52) :up)
               ((= keysym-code #xff53) :right)
               ((= keysym-code #xff54) :down)
               (t nil))))))

     (defun draw-line-segment-gc2 (x1 y1 x2 y2)
       "Helper to draw a single line segment using *gc2*."
       (let* ((segs (list (list x1 y1 x2 y2))))
         (with-packet (card8 66) (card8 0) (card16 (+ 3 (* 2 (length segs))))
          (card32 *window*) (card32 *gc2*)
          (dolist (s segs)
            (dolist (p s)
              (card16 p))))))

     (defun render-layout (layout focused pressed hovered)
       "Render layout tree on the X11 canvas."
       (labels ((render-node (node)
                  (when (listp node)
                    (let* ((w-struct (parse-node node))
                           (type (widget-type w-struct))
                           (name (widget-name w-struct))
                           (x (widget-x w-struct))
                           (y (widget-y w-struct))
                           (w (widget-w w-struct))
                           (h (widget-h w-struct))
                           (props (widget-props w-struct)))
                      (let ((type-name (and type (symbolp type) (symbol-name type))))
                        (cond
                          ((and type-name (string-equal type-name "PANEL"))
                           (let ((bg (getf props :bg #x00d0d0d0)))
                             (declare (ignorable bg))
                             (poly-fill-rectangle (list (list x y w h)))
                             (dolist (child (widget-children w-struct))
                               (render-node child))))
                          ((and type-name (string-equal type-name "LABEL"))
                           (let ((text (getf props :text "")))
                             (imagetext8 text :x x :y y)))
                          ((and type-name (string-equal type-name "BUTTON"))
                           (let* ((text (getf props :text ""))
                                  (is-pressed-p (eq name pressed))
                                  (is-hover-p (eq name hovered))
                                  (text-x (+ x (/ (- w (* 6 (length text))) 2)))
                                  (text-y (+ y (/ h 2) 4)))
                             (declare (ignorable is-hover-p))
                             (poly-fill-rectangle (list (list x y w h)))
                             (if is-pressed-p
                                 (progn
                                   (poly-rectangle (list (list x y (1- w) (1- h))) :gc *gc2*)
                                   (imagetext8 text :x (1+ text-x) :y (1+ text-y)))
                                 (progn
                                   (poly-rectangle (list (list x y (1- w) (1- h))) :gc *gc*)
                                   (draw-line-segment-gc2 (1+ x) (+ y h -1) (+ x w -1) (+ y h -1))
                                   (draw-line-segment-gc2 (+ x w -1) (1+ y) (+ x w -1) (+ y h -1))
                                   (imagetext8 text :x text-x :y text-y)))))
                          ((and type-name (string-equal type-name "CHECKBOX"))
                           (let* ((label (getf props :label ""))
                                  (checked-p (getf props :checked-p))
                                  (is-focused-p (eq name focused))
                                  (bx (+ x 2))
                                  (by (+ y (/ (- h 16) 2)))
                                  (text-x (+ x 22))
                                  (text-y (+ y (/ h 2) 4)))
                             (poly-fill-rectangle (list (list bx by 16 16)) :gc *gc2*)
                             (poly-rectangle (list (list bx by 15 15)) :gc *gc*)
                             (when checked-p
                               (imagetext8 "X" :x (+ bx 4) :y (+ by 12)))
                             (imagetext8 label :x text-x :y text-y)
                             (when is-focused-p
                               (poly-rectangle (list (list (1- text-x) (- text-y 12) (+ (* 6 (length label)) 2) 16))))))
                          ((and type-name (string-equal type-name "TEXT-INPUT"))
                           (let* ((text (getf props :text ""))
                                  (cursor-pos (getf props :cursor-pos 0))
                                  (is-focused-p (eq name focused))
                                  (text-x (+ x 6))
                                  (text-y (+ y (/ h 2) 4)))
                             (poly-fill-rectangle (list (list x y w h)) :gc *gc*)
                             (poly-rectangle (list (list x y (1- w) (1- h))) :gc *gc2*)
                             (imagetext8 text :x text-x :y text-y)
                             (when is-focused-p
                               (let ((cx (+ text-x (* 6 cursor-pos))))
                                 (draw-line-segment-gc2 cx (+ y 4) cx (+ y h -4))))))))))))
         (render-node layout)))

     (defvar *window-width* 400)
     (defvar *window-height* 300)
     (defvar *focused-widget* nil)
     (defvar *pressed-widget* nil)
     (defvar *hovered-widget* nil)

     (defun run-gui (update-fn view-fn initial-state)
       "Run the X11 GUI event loop using Model-Update-View (MUV)."
       (format t "Connecting to X server...~%")
       (handler-case (connect)
         (error (c)
           (format t "Failed to connect to X server: ~a~%" c)
           (return-from run-gui nil)))
       (format t "Creating window...~%")
       (let ((win (make-window :width *window-width* :height *window-height*)))
         (format t "Window created with ID: ~a~%" win)
         (let ((state initial-state)
               (layout nil)
               (keyboard-map (multiple-value-bind (map per-keycode)
                                 (get-keyboard-mapping 8 248)
                               (list 8 per-keycode map))))
           (labels ((rebuild-layout ()
                      (setf layout (funcall view-fn *window-width* *window-height* state))
                      (let ((focusable (collect-focusable-widgets layout)))
                        (when (and *focused-widget*
                                   (not (find *focused-widget* focusable :key #'widget-name)))
                          (setf *focused-widget* (and focusable (widget-name (car focusable)))))))
                    (redraw ()
                      (clear-area :w *window-width* :h *window-height*)
                      (render-layout layout *focused-widget* *pressed-widget* *hovered-widget*)))
             (rebuild-layout)
             (format t "Mapping window...~%")
             (map-window win)
             (format t "Entering event loop. Press Ctrl+C to exit.~%")
             (loop
               (let ((reply (read-reply-wait)))
                 (let ((code (logand (aref reply 0) #x7f)))
                   (format t "Received event code ~a~%" code)
                   (force-output)
                   (cond
                     ((= code 12) ; Expose
                      (redraw))
                     ((= code 22) ; ConfigureNotify (Resize)
                      (multiple-value-bind (w h) (parse-configure-notify reply)
                        (when (or (/= w *window-width*) (/= h *window-height*))
                          (setf *window-width* w
                                *window-height* h)
                          (rebuild-layout)
                          (clear-area :w w :h h :exposures 1))))
                     ((= code 6) ; MotionNotify
                      (multiple-value-bind (mx my state-mask time) (parse-motion-notify reply)
                        (declare (ignorable state-mask time))
                        (let* ((hit (find-widget-at layout mx my))
                               (hit-name (when hit (widget-name hit))))
                          (when (not (eq hit-name *hovered-widget*))
                            (setf *hovered-widget* hit-name)
                            (redraw)))))
                     ((= code 4) ; ButtonPress
                      (multiple-value-bind (btn mx my state-mask time) (parse-button-press reply)
                        (declare (ignorable state-mask time))
                        (when (= btn 1)
                          (let* ((hit (find-widget-at layout mx my))
                                 (hit-name (when hit (widget-name hit)))
                                 (hit-type (when hit (widget-type hit))))
                            (when hit-name
                              (setf *pressed-widget* hit-name)
                              (if (and hit-type (symbolp hit-type)
                                     (member (symbol-name hit-type) '("BUTTON" "CHECKBOX" "TEXT-INPUT") :test #'string-equal))
                                  (setf *focused-widget* hit-name)
                                  (setf *focused-widget* nil))
                              (redraw))))))
                     ((= code 5) ; ButtonRelease
                      (multiple-value-bind (btn mx my state-mask time) (parse-button-release reply)
                        (declare (ignorable state-mask time))
                        (when (and (= btn 1) *pressed-widget*)
                          (let* ((hit (find-widget-at layout mx my))
                                 (hit-name (when hit (widget-name hit))))
                            (when (eq hit-name *pressed-widget*)
                              (let ((w-struct (find-widget-by-name layout *pressed-widget*)))
                                (when w-struct
                                   (let* ((w-type (widget-type w-struct))
                                         (type-name (and w-type (symbolp w-type) (symbol-name w-type))))
                                    (cond
                                      ((and type-name (string-equal type-name "BUTTON"))
                                       (let ((msg (getf (widget-props w-struct) :msg)))
                                         (when msg
                                           (setf state (funcall update-fn state msg))
                                           (rebuild-layout))))
                                      ((and type-name (string-equal type-name "CHECKBOX"))
                                       (let ((msg (getf (widget-props w-struct) :msg)))
                                         (when msg
                                           (setf state (funcall update-fn state msg))
                                            (rebuild-layout)))))))
                            (setf *pressed-widget* nil)
                            (redraw)))))))
                     ((= code 2) ; KeyPress
                      (multiple-value-bind (detail mx my state-mask time) (parse-key-press reply)
                        (declare (ignorable mx my time))
                        (let ((keysym (translate-keycode keyboard-map detail state-mask)))
                          (cond
                            ((member keysym '(:left :right :up :down))
                             (let ((next-focus (find-nearest-widget layout *focused-widget* keysym)))
                               (when next-focus
                                 (setf *focused-widget* next-focus)
                                 (redraw))))
                            (*focused-widget*
                             (let ((w-struct (find-widget-by-name layout *focused-widget*)))
                               (when (and w-struct (let ((type (widget-type w-struct)))
                                                    (and type (symbolp type) (string-equal (symbol-name type) "TEXT-INPUT"))))
                                 (let ((current-text (getf (widget-props w-struct) :text ""))
                                       (cursor-pos (getf (widget-props w-struct) :cursor-pos 0))
                                       (msg-change (getf (widget-props w-struct) :msg-change)))
                                   (cond
                                     ((eq keysym :left)
                                      (let ((msg (list :cursor-move *focused-widget* (max 0 (1- cursor-pos)))))
                                        (setf state (funcall update-fn state msg))
                                        (rebuild-layout)
                                        (redraw)))
                                     ((eq keysym :right)
                                      (let ((msg (list :cursor-move *focused-widget* (min (length current-text) (1+ cursor-pos)))))
                                        (setf state (funcall update-fn state msg))
                                        (rebuild-layout)
                                        (redraw)))
                                     ((eq keysym :backspace)
                                      (when (> cursor-pos 0)
                                        (let* ((new-text (concatenate 'string
                                                                      (subseq current-text 0 (1- cursor-pos))
                                                                      (subseq current-text cursor-pos)))
                                               (new-pos (1- cursor-pos))
                                               (msg (append msg-change (list new-text new-pos))))
                                          (setf state (funcall update-fn state msg))
                                          (rebuild-layout)
                                          (redraw))))
                                     ((characterp keysym)
                                      (let* ((new-text (concatenate 'string
                                                                    (subseq current-text 0 cursor-pos)
                                                                    (string keysym)
                                                                    (subseq current-text cursor-pos)))
                                             (new-pos (1+ cursor-pos))
                                             (msg (append msg-change (list new-text new-pos))))
                                        (setf state (funcall update-fn state msg))
                                        (rebuild-layout)
                                        (redraw))))))))))))))))))))))
