;;;; 05_tests_template.lisp — Unit and integration tests template specification

(in-package :cl-cl-generator/example-x11-gen)

(defparameter *tests-template-code*
  `(toplevel
     ,@(make-header-comments)
     (defpackage :pure-x11-gen/tests
       (:use :cl :pure-x11-gen)
       (:export #:run-all-tests))
     (in-package :pure-x11-gen/tests)

     (defparameter *test-failures* 0)

     (defmacro assert-test (form &optional msg)
       `(if ,form
            (format t "PASS: ~a~%" ,(or msg (format nil "~s" form)))
            (progn
              (format t "FAIL: ~a~%" ,(or msg (format nil "~s" form)))
              (incf *test-failures*))))

     (defun test-parse-node ()
       (format t "--- Running test-parse-node ---~%")
       (let ((w (pure-x11-gen::parse-node '(panel :name :main-panel :x 10 :y 20 :w 100 :h 200 :bg 123 (button :name :b1)))))
         (assert-test (string-equal (symbol-name (pure-x11-gen::widget-type w)) "PANEL") "Widget type is PANEL")
         (assert-test (eq (pure-x11-gen::widget-name w) :main-panel) "Widget name is :main-panel")
         (assert-test (= (pure-x11-gen::widget-x w) 10) "Widget x is 10")
         (assert-test (= (pure-x11-gen::widget-y w) 20) "Widget y is 20")
         (assert-test (= (pure-x11-gen::widget-w w) 100) "Widget w is 100")
         (assert-test (= (pure-x11-gen::widget-h w) 200) "Widget h is 200")
         (assert-test (equal (pure-x11-gen::widget-children w) '((button :name :b1))) "Children parsed correctly")))

     (defun test-collect-focusable ()
       (format t "--- Running test-collect-focusable ---~%")
       (let* ((layout '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
                        (label :name :l1 :text "Title" :x 10 :y 10)
                        (button :name :b1 :x 10 :y 30 :w 100 :h 30)
                        (checkbox :name :c1 :x 10 :y 70 :w 100 :h 20)
                        (text-input :name :t1 :x 10 :y 100 :w 100 :h 30)))
              (focusable (pure-x11-gen::collect-focusable-widgets (pure-x11-gen::resolve-layout layout))))
         (assert-test (= (length focusable) 3) "Found 3 focusable widgets")
         (assert-test (eq (pure-x11-gen::widget-name (first focusable)) :b1) "First is :b1")
         (assert-test (eq (pure-x11-gen::widget-name (second focusable)) :c1) "Second is :c1")
         (assert-test (eq (pure-x11-gen::widget-name (third focusable)) :t1) "Third is :t1")))

     (defun test-hit-testing ()
       (format t "--- Running test-hit-testing ---~%")
       (let* ((layout (pure-x11-gen::resolve-layout
                        '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
                          (button :name :b1 :x 10 :y 30 :w 100 :h 30)
                          (button :name :b2 :x 120 :y 30 :w 100 :h 30)))))
         (assert-test (eq (pure-x11-gen::widget-name (pure-x11-gen::find-widget-at layout 15 45)) :b1) "Hit button 1")
         (assert-test (eq (pure-x11-gen::widget-name (pure-x11-gen::find-widget-at layout 150 45)) :b2) "Hit button 2")
         (assert-test (eq (pure-x11-gen::widget-name (pure-x11-gen::find-widget-at layout 5 5)) :main-panel) "Hit panel background")
         (assert-test (null (pure-x11-gen::find-widget-at layout 500 500)) "No hit outside bounds")))

     (defun test-cone-focus-search ()
       (format t "--- Running test-cone-focus-search ---~%")
       (let* ((layout (pure-x11-gen::resolve-layout
                        '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
                          (button :name :b1 :x 40 :y 40 :w 20 :h 20)
                          (button :name :b2 :x 140 :y 40 :w 20 :h 20)
                          (button :name :b3 :x 40 :y 140 :w 20 :h 20)))))
         (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b1 :right) :b2) "b1 -> right is b2")
         (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b1 :down) :b3) "b1 -> down is b3")
         (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b2 :left) :b1) "b2 -> left is b1")
         (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b3 :up) :b1) "b3 -> up is b1")))

     (defun test-widget-registry ()
       (format t "--- Running test-widget-registry ---~%")
       (let ((rendered-p nil))
         (pure-x11-gen::register-widget "MOCK"
           (lambda (w-struct focused pressed hovered)
             (declare (ignore focused pressed hovered))
             (setf rendered-p (eq (pure-x11-gen::widget-name w-struct) :my-mock))))
         (pure-x11-gen::render-layout (pure-x11-gen::resolve-layout '(mock :name :my-mock)) nil nil nil)
         (assert-test rendered-p "Mock widget renderer dispatched successfully")))

     (defun test-glue-solver ()
       (format t "--- Running test-glue-solver ---~%")
       (let* ((glues (list (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)
                           (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)
                           (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)))
              (sizes1 (pure-x11-gen::solve-glue glues 300))
              (sizes2 (pure-x11-gen::solve-glue glues 600))
              (glues3 (list (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)
                            (pure-x11-gen::make-glue :natural 100 :stretch 2 :shrink 0)))
              (sizes3 (pure-x11-gen::solve-glue glues3 300))
              (glues4 (list (pure-x11-gen::make-glue :natural 200 :stretch 0 :shrink 1)
                            (pure-x11-gen::make-glue :natural 200 :stretch 0 :shrink 1)))
              (sizes4 (pure-x11-gen::solve-glue glues4 300)))
         (assert-test (equal sizes1 '(100 100 100)) "Stretched to 300: 100, 100, 100")
         (assert-test (equal sizes2 '(200 200 200)) "Stretched to 600: 200, 200, 200")
         (assert-test (equal sizes3 '(133 167)) "Proportional stretch 1:2: size is correct")
         (assert-test (equal sizes4 '(150 150)) "Shrunk to 300: 150, 150")))

     (defun test-bevel-coordinates ()
       (format t "--- Running test-bevel-coordinates ---~%")
       (let ((pure-x11-gen::*window* 123)
             (pure-x11-gen::*gc-light* 1)
             (pure-x11-gen::*gc-face* 2)
             (pure-x11-gen::*gc-shadow* 3)
             (pure-x11-gen::*gc-dark* 4))
         (pure-x11-gen::with-buffered-output
           (pure-x11-gen::draw-bevel 10 10 100 50 :style :raised :bevel-width 2)
           (assert-test (= (length pure-x11-gen::*packet-buffer*) 8) "Buffered 8 draw-line packets for bevel"))))

     (defun test-dirty-widgets ()
       (format t "--- Running test-dirty-widgets ---~%")
       (let ((pure-x11-gen::*focused-widget* :w1)
             (pure-x11-gen::*pressed-widget* nil)
             (pure-x11-gen::*hovered-widget* :w2)
             (pure-x11-gen::*prev-focused* nil)
             (pure-x11-gen::*prev-pressed* nil)
             (pure-x11-gen::*prev-hovered* nil))
         (let ((dirty (pure-x11-gen::compute-dirty-widgets)))
           (assert-test (member :w1 dirty) ":w1 is dirty (focus change)")
           (assert-test (member :w2 dirty) ":w2 is dirty (hover change)")
           (assert-test (= (length dirty) 2) "Only 2 dirty widgets")
           (pure-x11-gen::save-visual-state)
           (assert-test (eq pure-x11-gen::*prev-focused* :w1) "prev-focused snapshot correct")
           (assert-test (null (pure-x11-gen::compute-dirty-widgets)) "No dirty widgets after save"))))

     (defun test-x11-opcodes ()
       (format t "--- Running test-x11-opcodes ---~%")
       (let ((pure-x11-gen::*window* 123)
             (pure-x11-gen::*gc-text* 456))
         (pure-x11-gen::with-buffered-output
           (pure-x11-gen::poly-fill-rectangle '((10 20 100 200)))
           (pure-x11-gen::imagetext8 "Hello" :x 10 :y 20)
           (pure-x11-gen::poly-rectangle '((10 20 100 200)))
           (let* ((packets (reverse pure-x11-gen::*packet-buffer*))
                  (p-fill-rect (first packets))
                  (p-imagetext (second packets))
                  (p-rect (third packets)))
             (assert-test (= (aref p-fill-rect 0) 70) "poly-fill-rectangle major opcode is 70")
             (assert-test (= (aref p-imagetext 0) 76) "imagetext8 major opcode is 76")
             (assert-test (= (aref p-rect 0) 74) "poly-rectangle major opcode is 74"))))

     (defun test-event-handlers ()
       (format t "--- Running test-event-handlers ---~%")
       (let* ((layout (pure-x11-gen::resolve-layout
                        '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
                          (button :name :b1 :x 10 :y 30 :w 100 :h 30 :msg :b1-clicked))))
              (pure-x11-gen::*window* 123)
              (pure-x11-gen::*gc-light* 1)
              (pure-x11-gen::*gc-face* 2)
              (pure-x11-gen::*gc-shadow* 3)
              (pure-x11-gen::*gc-dark* 4)
              (pure-x11-gen::*gc-text* 5)
              (pure-x11-gen::*resource-id-base* #x00000000)
              (pure-x11-gen::*resource-id-mask* #x000fffff)
              (pure-x11-gen::*resource-id-counter* 0)
              (pure-x11-gen::*hovered-widget* nil)
              (pure-x11-gen::*pressed-widget* nil)
              (pure-x11-gen::*focused-widget* nil))
         ;; Test motion handler (hover state update)
         (let ((reply (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
           (setf (aref reply 0) 6) ; MotionNotify
           (setf (aref reply 24) 15)
           (setf (aref reply 26) 45)
           (pure-x11-gen::handle-motion-event reply layout)
           (assert-test (eq pure-x11-gen::*hovered-widget* :b1) "Motion event updates hovered widget to :b1"))
         ;; Test button press handler (pressed & focused state update)
         (let ((reply (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
           (setf (aref reply 0) 4) ; ButtonPress
           (setf (aref reply 1) 1) ; Button 1
           (setf (aref reply 24) 15)
           (setf (aref reply 26) 45)
           (pure-x11-gen::handle-button-press-event reply layout)
           (assert-test (eq pure-x11-gen::*pressed-widget* :b1) "ButtonPress updates pressed widget to :b1")
           (assert-test (eq pure-x11-gen::*focused-widget* :b1) "ButtonPress updates focused widget to :b1"))
         ;; Test button release handler (state update & clear pressed)
         (let ((reply (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0))
               (state-updated nil))
           (setf (aref reply 0) 5) ; ButtonRelease
           (setf (aref reply 1) 1) ; Button 1
           (setf (aref reply 24) 15)
           (setf (aref reply 26) 45)
           (let ((new-state (pure-x11-gen::handle-button-release-event
                              reply layout :init-state
                              (lambda (s msg)
                                (setf state-updated (and (eq s :init-state) (eq msg :b1-clicked)))
                                :new-state)
                              (lambda ()))))
             (assert-test state-updated "ButtonRelease dispatched update-fn with widget :msg")
             (assert-test (eq new-state :new-state) "ButtonRelease returned updated state")
             (assert-test (null pure-x11-gen::*pressed-widget*) "ButtonRelease cleared pressed widget")))
         ;; Test configure handler (window resize)
         (let ((reply (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0))
               (rebuilt nil))
           (setf (aref reply 0) 22) ; ConfigureNotify
           (setf (aref reply 20) 100)
           (setf (aref reply 21) 1)
           (setf (aref reply 22) 44)
           (setf (aref reply 23) 1)
           (pure-x11-gen::handle-configure-event reply layout (lambda () (setf rebuilt t)))
           (assert-test rebuilt "ConfigureNotify triggers layout rebuild"))
         ;; Test expose handler (window redraw)
         (let ((reply (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
           (setf (aref reply 0) 12) ; Expose
           (pure-x11-gen::handle-expose-event layout)
           (assert-test t "Expose event handled cleanly"))
         ;; Test key press handler
         (let ((reply (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0))
               (kb-map (make-array '(256 2) :element-type '(unsigned-byte 32) :initial-element 0)))
           (setf (aref reply 0) 2) ; KeyPress
           (setf (aref reply 1) 24) ; Keycode 24
           (setf (aref kb-map 24 0) #x71) ; 'q'
           (pure-x11-gen::handle-key-press-event
             reply layout :state kb-map
             (lambda (s msg) (declare (ignore s msg)) :new-state)
             (lambda ()))
           (assert-test t "KeyPress event handled cleanly"))))

     (defun test-client-message-event ()
       (format t "--- Running test-client-message-event ---~%")
       (let ((pure-x11-gen::*wm-protocols-atom* 42)
             (pure-x11-gen::*wm-delete-window-atom* 99)
             (buf (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
         (setf (aref buf 0) 33   ; code = ClientMessage
               (aref buf 1) 32   ; format = 32
               (aref buf 2) 1    ; sequence number
               (aref buf 4) 100  ; window ID
               (aref buf 8) 42   ; type atom
               (aref buf 12) 99) ; data0 atom
         (multiple-value-bind (fmt win type d0 d1 d2 d3 d4) (pure-x11-gen::parse-client-message buf)
           (declare (ignore fmt win d1 d2 d3 d4))
           (assert-test (= type 42) "ClientMessage parsed type 42")
           (assert-test (= d0 99) "ClientMessage parsed data0 99"))
         (assert-test (eq (pure-x11-gen::handle-client-message-event buf) :close)
                      "ClientMessage with WM_DELETE_WINDOW returned :close")))

     (defun test-put-image-big-req ()
       (format t "--- Running test-put-image-big-req ---~%")
       (let ((pure-x11-gen::*s* (make-broadcast-stream))
             (pure-x11-gen::*window* 123)
             (pure-x11-gen::*gc-text* 1)
             (img (make-array '(10 10 4) :element-type '(unsigned-byte 8) :initial-element 255)))
         (pure-x11-gen::with-buffered-output
           (pure-x11-gen::poly-fill-rectangle '((0 0 10 10)))
           (assert-test (= (length pure-x11-gen::*packet-buffer*) 1) "Initial packet buffered")
           (pure-x11-gen::put-image-big-req img :dst-x 0 :dst-y 0)
           (assert-test (zerop (length pure-x11-gen::*packet-buffer*)) "Packet buffer flushed before big request stream write"))))

     (defun test-canvas-pixmap-cleanup ()
       (format t "--- Running test-canvas-pixmap-cleanup ---~%")
       (let ((pure-x11-gen::*s* (make-broadcast-stream))
             (pure-x11-gen::*window* 123)
             (pure-x11-gen::*gc-face* 1)
             (pure-x11-gen::*gc-light* 2)
             (pure-x11-gen::*gc-shadow* 3)
             (pure-x11-gen::*gc-dark* 4)
             (pure-x11-gen::*gc-text* 5)
             (pure-x11-gen::*resource-id-base* #x00000000)
             (pure-x11-gen::*resource-id-mask* #x000fffff)
             (pure-x11-gen::*resource-id-counter* 0))
         (pure-x11-gen::with-buffered-output
           (let ((w (pure-x11-gen::resolve-layout '(canvas :name :c1 :x 0 :y 0 :w 100 :h 100))))
             (pure-x11-gen::render-widget w nil nil nil)
             ;; FreePixmap opcode is 54
             (let ((free-pixmap-packets (remove-if-not (lambda (p) (= (aref p 0) 54)) pure-x11-gen::*packet-buffer*)))
               (assert-test (= (length free-pixmap-packets) 1) "FreePixmap opcode 54 emitted during canvas render cleanup"))))))

     (defun test-live-x11-connection ()
       (format t "--- Running test-live-x11-connection ---~%")
       (let ((display (uiop:getenv "DISPLAY")))
         (if (and display (string/= display ""))
             (handler-case
                 (progn
                   (connect :display display)
                   (assert-test pure-x11-gen::*s* "Connected to live X server socket")
                   (assert-test pure-x11-gen::*resource-id-base* "Parsed initial reply resource ID base")
                   (let ((win (make-window :width 300 :height 200))
                         (wm-protocols (intern-atom "WM_PROTOCOLS"))
                         (wm-delete (intern-atom "WM_DELETE_WINDOW")))
                     (assert-test (numberp wm-protocols) "Interned WM_PROTOCOLS atom ID")
                     (assert-test (numberp wm-delete) "Interned WM_DELETE_WINDOW atom ID")
                     (change-property win wm-protocols 4 wm-delete)
                     (map-window win)
                     (assert-test t "Created, configured, and mapped live X11 window")))
               (error (e)
                 (format t "FAIL: Live X11 connection test failed with error: ~a~%" e)
                 (incf *test-failures*)))
             (format t "SKIP: DISPLAY not set, skipping live X11 integration test.~%"))))

     (defun test-translate-keycode ()
       (format t "--- Running test-translate-keycode ---~%")
       (let* ((map-array (make-array 500 :element-type '(unsigned-byte 32) :initial-element 0))
              (kb-map (list 8 2 map-array)))
         (setf (aref map-array 0) #xff09)
         (setf (aref map-array 2) #xff1b)
         (setf (aref map-array 4) #xffff)
         (setf (aref map-array 6) #xff50)
         (setf (aref map-array 8) #xff55)
         (setf (aref map-array 10) #xff56)
         (setf (aref map-array 12) #xff57)
         (setf (aref map-array 24) #xffbe)
         (setf (aref map-array 46) #xffc9)

         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 8 0) :tab) "Keycode 8 translates to :tab")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 9 0) :escape) "Keycode 9 translates to :escape")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 10 0) :delete) "Keycode 10 translates to :delete")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 11 0) :home) "Keycode 11 translates to :home")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 12 0) :page-up) "Keycode 12 translates to :page-up")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 13 0) :page-down) "Keycode 13 translates to :page-down")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 14 0) :end) "Keycode 14 translates to :end")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 20 0) :f1) "Keycode 20 translates to :f1")
         (assert-test (eq (pure-x11-gen::translate-keycode kb-map 31 0) :f12) "Keycode 31 translates to :f12")))

     (defun run-all-tests ()
       (setf *test-failures* 0)
       (test-parse-node)
       (test-collect-focusable)
       (test-hit-testing)
       (test-cone-focus-search)
       (test-widget-registry)
       (test-glue-solver)
       (test-bevel-coordinates)
       (test-dirty-widgets)
       (test-x11-opcodes)
       (test-event-handlers)
       (test-client-message-event)
       (test-put-image-big-req)
       (test-canvas-pixmap-cleanup)
       (test-live-x11-connection)
       (test-translate-keycode)
       (if (zerop *test-failures*)
           (format t "ALL TESTS PASSED!~%" )
           (progn
             (format t "SOME TESTS FAILED: ~a failures~%" *test-failures*)
             (sb-ext:exit :code 1)))))))
