;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 12:04:57
;; Git:       00385fef4be4ae6173ab71bf9a5948ee5858bdf4
(asdf/parse-defsystem:defsystem :expanse-combat
  :version
  "0.1.0"
  :description
  "Expanse-style 2D orbital tactical space combat simulation"
  :depends-on
  (:pure-x11-gen :hpipm)
  :serial
  t
  :components
  ((:file "package") (:file "physics") (:file "mpc") (:file "game")))