;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 11:43:28
;; Git:       98f766809ab37c5e92243355aebe4b891fc4872a
(asdf/parse-defsystem:defsystem :expanse-combat
  :version
  "0.1.0"
  :description
  "Expanse-style 2D orbital tactical space combat simulation"
  :depends-on
  (:pure-x11-gen :hpipm)
  :serial
  t
  :components
  ((:file "package") (:file "physics") (:file "mpc") (:file "game")))