;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 12:01:16
;; Git:       fbc2bca861b1b923c7cdec52528be72a414eea87
(asdf/parse-defsystem:defsystem :expanse-combat
  :version
  "0.1.0"
  :description
  "Expanse-style 2D orbital tactical space combat simulation"
  :depends-on
  (:pure-x11-gen :hpipm)
  :serial
  t
  :components
  ((:file "package") (:file "physics") (:file "mpc") (:file "game")))