;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 12:01:16
;; Git:       fbc2bca861b1b923c7cdec52528be72a414eea87
(defpackage :expanse-combat
  (:use :cl)
  (:export #:run-game))