;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 12:04:57
;; Git:       00385fef4be4ae6173ab71bf9a5948ee5858bdf4
(defpackage :expanse-combat
  (:use :cl)
  (:export #:run-game))