;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-22 20:27:39
;; Git:       170f4e4f7a40c7b0c400abd9ef1ad0e6d747fb59
(in-package :pure-x11-gen)

(defvar *window-width* 400)

(defvar *window-height* 300)

(defvar *focused-widget* nil)

(defvar *pressed-widget* nil)

(defvar *hovered-widget* nil)

(defvar *prev-focused* nil)

(defvar *prev-pressed* nil)

(defvar *prev-hovered* nil)

(defvar *wm-protocols-atom* nil)

(defvar *wm-delete-window-atom* nil)

(defun compute-dirty-widgets ()
  "Return list of widget names whose visual state changed since last render."
  (let ((dirty nil))
    (when (not (eq *focused-widget* *prev-focused*))
      (when *prev-focused*
        (push *prev-focused* dirty))
      (when *focused-widget*
        (push *focused-widget* dirty)))
    (when (not (eq *pressed-widget* *prev-pressed*))
      (when *prev-pressed*
        (push *prev-pressed* dirty))
      (when *pressed-widget*
        (push *pressed-widget* dirty)))
    (when (not (eq *hovered-widget* *prev-hovered*))
      (when *prev-hovered*
        (push *prev-hovered* dirty))
      (when *hovered-widget*
        (push *hovered-widget* dirty)))
    (remove-duplicates dirty)))

(defun save-visual-state ()
  "Snapshot current visual state for dirty tracking."
  (setf *prev-focused* *focused-widget*
        *prev-pressed* *pressed-widget*
        *prev-hovered* *hovered-widget*))

(defun full-redraw (layout)
  "Full render using window-wide double buffering to completely prevent flicker."
  (let ((pix (next-resource-id)) (win-id *window*))
    (with-buffered-output
     (create-pixmap pix *window-width* *window-height* :depth
      (or *root-depth* 24))
     (unwind-protect (progn
                       (let ((*window* pix))
                         (render-layout layout *focused-widget*
                          *pressed-widget* *hovered-widget*))
                       (copy-area pix win-id *gc-text* 0 0 0 0 *window-width*
                        *window-height*))
       (free-pixmap pix))))
  (save-visual-state))

(defun partial-redraw (layout dirty-names)
  "Re-render only the widgets in DIRTY-NAMES using offscreen pixmap double-buffering to eliminate flicker."
  (with-buffered-output
   (dolist (name dirty-names)
     (let ((w (find-widget-by-name layout name)))
       (when (and w (> (widget-w w) 0) (> (widget-h w) 0))
         (let* ((type (widget-type w)) (wx (widget-x w)) (wy (widget-y w))
                (ww (widget-w w)) (wh (widget-h w)))
           (if (eq type :canvas)
               (render-widget w *focused-widget* *pressed-widget*
                *hovered-widget*)
               (let ((pix (next-resource-id)) (win-id *window*))
                 (create-pixmap pix *window-width* *window-height* :depth
                  (or *root-depth* 24))
                 (unwind-protect (progn
                                   (let ((*window* pix))
                                     (poly-fill-rectangle
                                      (list (list wx wy ww wh)) :gc *gc-face*)
                                     (render-widget w *focused-widget*
                                      *pressed-widget* *hovered-widget*))
                                   (copy-area pix win-id *gc-text* wx wy wx wy
                                    ww wh))
                   (free-pixmap pix)))))))))
  (save-visual-state))

(defun smart-redraw (layout)
  "Compute dirty widgets and do a partial redraw, or skip if nothing changed."
  (let ((dirty (compute-dirty-widgets)))
    (when dirty
      (partial-redraw layout dirty))))

(defun handle-expose-event (layout)
  "Handle Expose event (code 12) by triggering a full redraw."
  (full-redraw layout))

(defun handle-configure-event (reply layout rebuild-layout-fn)
  "Handle ConfigureNotify (window resize, code 22) event."
  (multiple-value-bind (w h) (parse-configure-notify reply)
    (when (or (/= w *window-width*) (/= h *window-height*))
      (setf *window-width* w
            *window-height* h)
      (funcall rebuild-layout-fn)
      (full-redraw layout))))

(defun handle-motion-event (reply layout)
  "Handle MotionNotify (mouse motion, code 6) event."
  (multiple-value-bind (mx my state-mask time) (parse-motion-notify reply)
    (declare (ignorable state-mask time))
    (let* ((hit (find-widget-at layout mx my))
           (hit-name
            (when hit
              (widget-name hit))))
      (when (not (eq hit-name *hovered-widget*))
        (setf *hovered-widget* hit-name)
        (smart-redraw layout)))))

(defun handle-button-press-event (reply layout)
  "Handle ButtonPress (code 4) event."
  (multiple-value-bind (btn mx my state-mask time) (parse-button-press reply)
    (declare (ignorable state-mask time))
    (when (= btn 1)
      (let* ((hit (find-widget-at layout mx my))
             (hit-name
              (when hit
                (widget-name hit)))
             (hit-type
              (when hit
                (widget-type hit))))
        (when hit-name
          (setf *pressed-widget* hit-name)
          (if (member hit-type '(:button :checkbox :text-input) :test #'eq)
              (setf *focused-widget* hit-name)
              (setf *focused-widget* nil))
          (smart-redraw layout))))))

(defun handle-button-release-event (reply layout state update-fn
                                    rebuild-layout-fn)
  "Handle ButtonRelease (code 5) event. Returns updated state."
  (multiple-value-bind (btn mx my state-mask time) (parse-button-release reply)
    (declare (ignorable state-mask time))
    (let ((new-state state))
      (when (and (= btn 1) *pressed-widget*)
        (let* ((hit (find-widget-at layout mx my))
               (hit-name
                (when hit
                  (widget-name hit)))
               (layout-changed nil))
          (when (eq hit-name *pressed-widget*)
            (let ((w-struct (find-widget-by-name layout *pressed-widget*)))
              (when w-struct
                (let ((w-type (widget-type w-struct)))
                  (when (member w-type '(:button :checkbox) :test #'eq)
                    (let ((msg (getf (widget-props w-struct) :msg)))
                      (when msg
                        (setf new-state (funcall update-fn state msg))
                        (funcall rebuild-layout-fn)
                        (setf layout-changed t))))))))
          (setf *pressed-widget* nil)
          (if layout-changed
              (full-redraw layout)
              (smart-redraw layout))))
      new-state)))

(defun handle-key-press-event (reply layout state keyboard-map update-fn
                               rebuild-layout-fn)
  "Handle KeyPress (code 2) event. Returns updated state."
  (multiple-value-bind (detail mx my state-mask time) (parse-key-press reply)
    (declare (ignorable mx my time))
    (let* ((keysym (translate-keycode keyboard-map detail state-mask))
           (focused-is-text-input
            (and *focused-widget*
                 (let ((w (find-widget-by-name layout *focused-widget*)))
                   (and w (eq (widget-type w) :text-input))))))
      (cond
        ((eq keysym :tab)
         (let* ((widgets (collect-focusable-widgets layout))
                (names (mapcar #'widget-name widgets)))
           (when names
             (let* ((pos (position *focused-widget* names))
                    (next-name
                     (if pos
                         (nth (mod (1+ pos) (length names)) names)
                         (car names))))
               (setf *focused-widget* next-name)
               (smart-redraw layout))))
         state)
        ((and (member keysym '(:left :right :up :down))
              (not
               (and focused-is-text-input (member keysym '(:left :right)))))
         (let ((next-focus
                (find-nearest-widget layout *focused-widget* keysym)))
           (when next-focus
             (setf *focused-widget* next-focus)
             (smart-redraw layout)))
         state)
        ((and *focused-widget* focused-is-text-input)
         (let ((w-struct (find-widget-by-name layout *focused-widget*))
               (new-state state))
           (when w-struct
             (let ((current-text (getf (widget-props w-struct) :text ""))
                   (cursor-pos (getf (widget-props w-struct) :cursor-pos 0))
                   (msg-change (getf (widget-props w-struct) :msg-change)))
               (cond
                 ((eq keysym :left)
                  (let ((msg
                         (list :cursor-move *focused-widget*
                               (max 0 (1- cursor-pos)))))
                    (setf new-state (funcall update-fn state msg))
                    (funcall rebuild-layout-fn)
                    (full-redraw layout)))
                 ((eq keysym :right)
                  (let ((msg
                         (list :cursor-move *focused-widget*
                               (min (length current-text) (1+ cursor-pos)))))
                    (setf new-state (funcall update-fn state msg))
                    (funcall rebuild-layout-fn)
                    (full-redraw layout)))
                 ((eq keysym :backspace)
                  (when (> cursor-pos 0)
                    (let* ((new-text
                            (concatenate 'string
                                         (subseq current-text 0
                                                 (1- cursor-pos))
                                         (subseq current-text cursor-pos)))
                           (new-pos (1- cursor-pos))
                           (msg (append msg-change (list new-text new-pos))))
                      (setf new-state (funcall update-fn state msg))
                      (funcall rebuild-layout-fn)
                      (full-redraw layout))))
                 ((characterp keysym)
                  (let* ((new-text
                          (concatenate 'string
                                       (subseq current-text 0 cursor-pos)
                                       (string keysym)
                                       (subseq current-text cursor-pos)))
                         (new-pos (1+ cursor-pos))
                         (msg (append msg-change (list new-text new-pos))))
                    (setf new-state (funcall update-fn state msg))
                    (funcall rebuild-layout-fn)
                    (full-redraw layout))))))
           new-state))
        (t
         (let ((new-state (funcall update-fn state (list :key-press keysym))))
           (funcall rebuild-layout-fn)
           (full-redraw layout)
           new-state))))))

(defun handle-client-message-event (reply)
  "Handle ClientMessage (code 33) event. Returns :close if WM_DELETE_WINDOW was received."
  (multiple-value-bind (format win type data0 data1 data2 data3
                               data4) (parse-client-message reply)
    (declare (ignorable format win data1 data2 data3 data4))
    (when (and (numberp type) (numberp *wm-protocols-atom*)
               (= type *wm-protocols-atom*) (numberp data0)
               (numberp *wm-delete-window-atom*)
               (= data0 *wm-delete-window-atom*))
      :close)))

(defun run-gui (update-fn view-fn initial-state &key (tick-interval nil)
                (tick-msg '(:tick)) (init-fn nil))
  "Run the X11 GUI event loop using Model-Update-View (MUV)."
  (let ((*focused-widget* nil) (*pressed-widget* nil) (*hovered-widget* nil)
        (*prev-focused* nil) (*prev-pressed* nil) (*prev-hovered* nil)
        (*window-width* *window-width*) (*window-height* *window-height*))
    (format t "Connecting to X server...~%")
    (handler-case (connect)
      (error (c) (format t "Failed to connect to X server: ~a~%" c)
             (return-from run-gui nil)))
    (format t "Creating window...~%")
    (let ((win (make-window :width *window-width* :height *window-height*)))
      (format t "Window created with ID: ~a~%" win)
      (setf *wm-protocols-atom* (intern-atom "WM_PROTOCOLS")
            *wm-delete-window-atom* (intern-atom "WM_DELETE_WINDOW"))
      (change-property win *wm-protocols-atom* 4 *wm-delete-window-atom*)
      (when init-fn
        (funcall init-fn win))
      (let ((state initial-state) (layout nil)
            (keyboard-map
             (multiple-value-bind (map per-keycode) (get-keyboard-mapping 8 248)
               (list 8 per-keycode map))))
        (labels ((rebuild-layout nil
                  (let ((raw-layout
                         (funcall view-fn *window-width* *window-height*
                                  state)))
                    (setf layout
                            (resolve-layout raw-layout 0 0 *window-width*
                             *window-height*)))
                  (let ((focusable (collect-focusable-widgets layout)))
                    (when (and *focused-widget*
                               (not
                                (find *focused-widget* focusable :key
                                      #'widget-name)))
                      (setf *focused-widget*
                              (and focusable (widget-name (car focusable))))))))
          (rebuild-layout)
          (format t "Mapping window...~%")
          (map-window win)
          (format t "Entering event loop. Press Ctrl+C to exit.~%")
          (full-redraw layout)
          (let ((last-tick-time (get-internal-real-time)))
            (loop
             (let* ((reply nil) (timed-out-p nil))
               (cond
                 (*pending-events* (setf reply (pop *pending-events*)))
                 (tick-interval
                  (let* ((now (get-internal-real-time))
                         (elapsed
                          (/ (- now last-tick-time)
                             internal-time-units-per-second))
                         (remaining (- tick-interval elapsed)))
                    (if (<= remaining 0)
                        (setf timed-out-p t)
                        (let ((buf (read-reply-timeout remaining)))
                          (if buf
                              (setf reply buf)
                              (setf timed-out-p t))))))
                 (t (setf reply (read-reply-wait))))
               (cond
                 (timed-out-p (setf last-tick-time (get-internal-real-time))
                  (setf state (funcall update-fn state tick-msg))
                  (rebuild-layout) (full-redraw layout))
                 (reply
                  (let ((code (logand (aref reply 0) 127)))
                    (cond
                      ((= code 12) (handle-expose-event layout))
                      ((= code 22)
                       (handle-configure-event reply layout #'rebuild-layout))
                      ((= code 6) (handle-motion-event reply layout))
                      ((= code 4) (handle-button-press-event reply layout))
                      ((= code 5)
                       (setf state
                               (handle-button-release-event reply layout state
                                update-fn #'rebuild-layout)))
                      ((= code 2)
                       (setf state
                               (handle-key-press-event reply layout state
                                keyboard-map update-fn #'rebuild-layout)))
                      ((= code 33)
                       (when (eq (handle-client-message-event reply) :close)
                         (format t
                                 "Received WM_DELETE_WINDOW. Exiting event loop...~%")
                         (return-from run-gui t)))))))))))))))