;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 09:22:52
;; Git:       6d4748ba4a4c2503ee5ffe4ed53a735a7df77e97
(defpackage :pure-x11-gen/example
  (:use :cl :pure-x11-gen)
  (:export #:run-x11-example))

(in-package :pure-x11-gen/example)

(defstruct app-state
  (clicks 0)
  (input-buffer "Type here")
  (cursor-pos 9)
  (checkbox-val nil))

(defun update (state msg)
  "Pure state update function."
  (let ((clicks (app-state-clicks state)) (buf (app-state-input-buffer state))
        (pos (app-state-cursor-pos state)) (chk (app-state-checkbox-val state)))
    (case (car msg)
      (:increment
       (make-app-state :clicks (1+ clicks) :input-buffer buf :cursor-pos pos
        :checkbox-val chk))
      (:decrement
       (make-app-state :clicks (1- clicks) :input-buffer buf :cursor-pos pos
        :checkbox-val chk))
      (:toggle-checkbox
       (make-app-state :clicks clicks :input-buffer buf :cursor-pos pos
        :checkbox-val (not chk)))
      (:text-change
       (let ((new-text (cadr msg)) (new-pos (caddr msg)))
         (make-app-state :clicks clicks :input-buffer new-text :cursor-pos
          new-pos :checkbox-val chk)))
      (:cursor-move
       (let ((new-pos (caddr msg)))
         (make-app-state :clicks clicks :input-buffer buf :cursor-pos new-pos
          :checkbox-val chk)))
      (t state))))


 (defun view (w h state)
   "Pure layout render function returning the virtual DOM."
   (let ((clicks (app-state-clicks state))
         (buf (app-state-input-buffer state))
         (pos (app-state-cursor-pos state))
         (chk (app-state-checkbox-val state)))
     `(panel :name :root :x 0 :y 0 :w ,w :h ,h
        (vbox :name :main-vbox :x 10 :y 10 :w ,(- w 20) :h ,(- h 20) :padding 0 :spacing 10
          (label :name :title :text ,(format nil "Athena GUI Demo (Clicks: ~a)" clicks)
                 :glue (:natural 20 :stretch 0 :shrink 0))
          (hbox :name :buttons :glue (:natural 30 :stretch 0 :shrink 0) :spacing 10
            (button :name :btn-inc :text "Increment" :msg (:increment)
                    :glue (:natural 120 :stretch 1 :shrink 0))
            (button :name :btn-dec :text "Decrement" :msg (:decrement)
                    :glue (:natural 120 :stretch 1 :shrink 0)))
          (text-input :name :txt :text ,buf
                      :cursor-pos ,pos
                      :msg-change (:text-change)
                      :glue (:natural 30 :stretch 1 :shrink 0))
          (checkbox :name :chk :label "Enable Action Mode"
                    :checked-p ,chk
                    :msg (:toggle-checkbox)
                    :glue (:natural 24 :stretch 0 :shrink 0))))))
 

(defun run-x11-example ()
  "Connect to X11 and run the declarative GUI application."
  (run-gui #'update #'view (make-app-state)))