;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 11:01:37
;; Git:       5fe4b35eae52457480000b97e0538f3644b9afbb
(defpackage :pure-x11-gen
  (:use :cl :sb-bsd-sockets)
  (:export #:connect
           #:make-window
           #:map-window
           #:destroy-window
           #:change-window-attributes
           #:configure-window
           #:clear-area
           #:draw-window
           #:poly-rectangle
           #:poly-fill-rectangle
           #:poly-arc
           #:poly-fill-arc
           #:create-gc
           #:create-pixmap
           #:free-pixmap
           #:copy-area
           #:*root-depth*
           #:next-resource-id
           #:read-reply-timeout
           #:query-pointer
           #:imagetext8
           #:query-extension
           #:big-requests-enable
           #:put-image-big-req
           #:free-gc
           #:create-cursor
           #:open-font
           #:close-font
           #:grab-pointer
           #:ungrab-pointer
           #:get-keyboard-mapping
           #:read-reply-wait
           #:read-reply-packet
           #:*pending-events*
           #:run-gui
           #:parse-expose
           #:parse-motion-notify
           #:parse-button-press
           #:parse-button-release
           #:parse-key-press
           #:parse-configure-notify
           #:draw-line
           #:*s*
           #:*root*
           #:*window*
           #:*gc-light*
           #:*gc-face*
           #:*gc-shadow*
           #:*gc-dark*
           #:*gc-text*
           #:*packet-buffer*
           #:with-buffered-output
           #:flush-packets
           #:resolve-layout
           #:widget-p
           #:*big-request-opcode*))