;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 22:06:35
;; Git:       de1029b4417e8b947224662d19bc8fbcd764f7c3
(defpackage :pure-x11-gen
  (:use :cl :sb-bsd-sockets)
  (:export #:connect
           #:make-window
           #:map-window
           #:destroy-window
           #:change-window-attributes
           #:configure-window
           #:clear-area
           #:draw-window
           #:query-pointer
           #:imagetext8
           #:query-extension
           #:big-requests-enable
           #:put-image-big-req
           #:free-gc
           #:create-cursor
           #:open-font
           #:close-font
           #:grab-pointer
           #:ungrab-pointer
           #:get-keyboard-mapping
           #:read-reply-wait
           #:parse-expose
           #:parse-motion-notify
           #:parse-button-press
           #:parse-button-release
           #:parse-key-press
           #:*s*
           #:*root*
           #:*window*
           #:*gc*
           #:*gc2*
           #:*big-request-opcode*))