;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 05:03:31
;; Git:       8a7d91d0884f220ea1e233ab2242e710be8134b1
(defpackage :pure-x11-gen
  (:use :cl :sb-bsd-sockets)
  (:export #:connect
           #:make-window
           #:map-window
           #:destroy-window
           #:change-window-attributes
           #:configure-window
           #:clear-area
           #:draw-window
           #:poly-rectangle
           #:poly-fill-rectangle
           #:query-pointer
           #:imagetext8
           #:query-extension
           #:big-requests-enable
           #:put-image-big-req
           #:free-gc
           #:create-cursor
           #:open-font
           #:close-font
           #:grab-pointer
           #:ungrab-pointer
           #:get-keyboard-mapping
           #:read-reply-wait
           #:run-gui
           #:parse-expose
           #:parse-motion-notify
           #:parse-button-press
           #:parse-button-release
           #:parse-key-press
           #:parse-configure-notify
           #:draw-line
           #:*s*
           #:*root*
           #:*window*
           #:*gc-light*
           #:*gc-face*
           #:*gc-shadow*
           #:*gc-dark*
           #:*gc-text*
           #:*packet-buffer*
           #:with-buffered-output
           #:flush-packets
           #:resolve-layout
           #:widget-p
           #:*big-request-opcode*))