;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 04:13:02
;; Git:       b7561db1f6f9150bd60a6d700ff1a3602e63ead1
(asdf/parse-defsystem:defsystem :pure-x11-gen
  :version
  "0.1.0"
  :description
  "X11 client library generated dynamically via cl-cl-generator"
  :depends-on
  (:sb-bsd-sockets)
  :serial
  t
  :components
  ((:file "package") (:file "x11-core") (:file "widgets") (:file "example")
   (:file "tests")))