;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 23:06:00
;; Git:       d9814c1fa54fdf74c69c1a90093903f6b1dab0f0
(asdf/parse-defsystem:defsystem :pure-x11-gen
  :version
  "0.1.0"
  :description
  "X11 client library generated dynamically via cl-cl-generator"
  :depends-on
  (:sb-bsd-sockets)
  :serial
  t
  :components
  ((:file "package") (:file "x11-core") (:file "widgets")))