;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-22 20:11:25
;; Git:       dd18ff9f50eb967082d3e6d7df46e3863bf43548
(defpackage :pure-x11-gen/tests
  (:use :cl :pure-x11-gen)
  (:export #:run-all-tests))

(in-package :pure-x11-gen/tests)

(defparameter *test-failures* 0)

(defmacro assert-test (form &optional msg)
  `(if ,form
       (format t "PASS: ~a~%" ,(or msg (format nil "~s" form)))
       (progn
         (format t "FAIL: ~a~%" ,(or msg (format nil "~s" form)))
         (incf *test-failures*))))

(defun test-parse-node ()
  (format t "--- Running test-parse-node ---~%")
  (let ((w
         (pure-x11-gen::parse-node
          '(panel :name :main-panel :x 10 :y 20 :w 100 :h 200 :bg 123
            (button :name :b1)))))
    (assert-test
     (string-equal (symbol-name (pure-x11-gen::widget-type w)) "PANEL")
     "Widget type is PANEL")
    (assert-test (eq (pure-x11-gen::widget-name w) :main-panel)
     "Widget name is :main-panel")
    (assert-test (= (pure-x11-gen::widget-x w) 10) "Widget x is 10")
    (assert-test (= (pure-x11-gen::widget-y w) 20) "Widget y is 20")
    (assert-test (= (pure-x11-gen::widget-w w) 100) "Widget w is 100")
    (assert-test (= (pure-x11-gen::widget-h w) 200) "Widget h is 200")
    (assert-test
     (equal (pure-x11-gen::widget-children w) '((button :name :b1)))
     "Children parsed correctly")))

(defun test-collect-focusable ()
  (format t "--- Running test-collect-focusable ---~%")
  (let* ((layout
          '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
            (label :name :l1 :text "Title" :x 10 :y 10)
            (button :name :b1 :x 10 :y 30 :w 100 :h 30)
            (checkbox :name :c1 :x 10 :y 70 :w 100 :h 20)
            (text-input :name :t1 :x 10 :y 100 :w 100 :h 30)))
         (focusable
          (pure-x11-gen::collect-focusable-widgets
           (pure-x11-gen::resolve-layout layout))))
    (assert-test (= (length focusable) 3) "Found 3 focusable widgets")
    (assert-test (eq (pure-x11-gen::widget-name (first focusable)) :b1)
     "First is :b1")
    (assert-test (eq (pure-x11-gen::widget-name (second focusable)) :c1)
     "Second is :c1")
    (assert-test (eq (pure-x11-gen::widget-name (third focusable)) :t1)
     "Third is :t1")))

(defun test-hit-testing ()
  (format t "--- Running test-hit-testing ---~%")
  (let* ((layout
          (pure-x11-gen::resolve-layout
           '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
             (button :name :b1 :x 10 :y 30 :w 100 :h 30)
             (button :name :b2 :x 120 :y 30 :w 100 :h 30)))))
    (assert-test
     (eq
      (pure-x11-gen::widget-name (pure-x11-gen::find-widget-at layout 15 45))
      :b1)
     "Hit button 1")
    (assert-test
     (eq
      (pure-x11-gen::widget-name (pure-x11-gen::find-widget-at layout 150 45))
      :b2)
     "Hit button 2")
    (assert-test
     (eq (pure-x11-gen::widget-name (pure-x11-gen::find-widget-at layout 5 5))
         :main-panel)
     "Hit panel background")
    (assert-test (null (pure-x11-gen::find-widget-at layout 500 500))
     "No hit outside bounds")))

(defun test-cone-focus-search ()
  (format t "--- Running test-cone-focus-search ---~%")
  (let* ((layout
          (pure-x11-gen::resolve-layout
           '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
             (button :name :b1 :x 40 :y 40 :w 20 :h 20)
             (button :name :b2 :x 140 :y 40 :w 20 :h 20)
             (button :name :b3 :x 40 :y 140 :w 20 :h 20)))))
    (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b1 :right) :b2)
     "b1 -> right is b2")
    (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b1 :down) :b3)
     "b1 -> down is b3")
    (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b2 :left) :b1)
     "b2 -> left is b1")
    (assert-test (eq (pure-x11-gen::find-nearest-widget layout :b3 :up) :b1)
     "b3 -> up is b1")))

(defun test-widget-registry ()
  (format t "--- Running test-widget-registry ---~%")
  (let ((rendered-p nil))
    (pure-x11-gen::register-widget "MOCK"
     (lambda (w-struct focused pressed hovered)
       (declare (ignore focused pressed hovered))
       (setf rendered-p (eq (pure-x11-gen::widget-name w-struct) :my-mock))))
    (pure-x11-gen::render-layout
     (pure-x11-gen::resolve-layout '(mock :name :my-mock)) nil nil nil)
    (assert-test rendered-p "Mock widget renderer dispatched successfully")))

(defun test-glue-solver ()
  (format t "--- Running test-glue-solver ---~%")
  (let* ((glues
          (list (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)
                (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)
                (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)))
         (sizes1 (pure-x11-gen::solve-glue glues 300))
         (sizes2 (pure-x11-gen::solve-glue glues 600))
         (glues3
          (list (pure-x11-gen::make-glue :natural 100 :stretch 1 :shrink 0)
                (pure-x11-gen::make-glue :natural 100 :stretch 2 :shrink 0)))
         (sizes3 (pure-x11-gen::solve-glue glues3 300))
         (glues4
          (list (pure-x11-gen::make-glue :natural 200 :stretch 0 :shrink 1)
                (pure-x11-gen::make-glue :natural 200 :stretch 0 :shrink 1)))
         (sizes4 (pure-x11-gen::solve-glue glues4 300)))
    (assert-test (equal sizes1 '(100 100 100))
     "Stretched to 300: 100, 100, 100")
    (assert-test (equal sizes2 '(200 200 200))
     "Stretched to 600: 200, 200, 200")
    (assert-test (equal sizes3 '(133 167))
     "Proportional stretch 1:2: size is correct")
    (assert-test (equal sizes4 '(150 150)) "Shrunk to 300: 150, 150")))

(defun test-bevel-coordinates ()
  (format t "--- Running test-bevel-coordinates ---~%")
  (let ((pure-x11-gen::*window* 123) (pure-x11-gen::*gc-light* 1)
        (pure-x11-gen::*gc-face* 2) (pure-x11-gen::*gc-shadow* 3)
        (pure-x11-gen::*gc-dark* 4))
    (pure-x11-gen::with-buffered-output
     (pure-x11-gen::draw-bevel 10 10 100 50 :style :raised :bevel-width 2)
     (assert-test (= (length pure-x11-gen::*packet-buffer*) 8)
      "Buffered 8 draw-line packets for bevel"))))

(defun test-dirty-widgets ()
  (format t "--- Running test-dirty-widgets ---~%")
  (let ((pure-x11-gen::*focused-widget* :w1)
        (pure-x11-gen::*pressed-widget* nil)
        (pure-x11-gen::*hovered-widget* :w2) (pure-x11-gen::*prev-focused* nil)
        (pure-x11-gen::*prev-pressed* nil) (pure-x11-gen::*prev-hovered* nil))
    (let ((dirty (pure-x11-gen::compute-dirty-widgets)))
      (assert-test (member :w1 dirty) ":w1 is dirty (focus change)")
      (assert-test (member :w2 dirty) ":w2 is dirty (hover change)")
      (assert-test (= (length dirty) 2) "Only 2 dirty widgets")
      (pure-x11-gen::save-visual-state)
      (assert-test (eq pure-x11-gen::*prev-focused* :w1)
       "prev-focused snapshot correct")
      (assert-test (null (pure-x11-gen::compute-dirty-widgets))
       "No dirty widgets after save"))))

(defun test-x11-opcodes ()
  (format t "--- Running test-x11-opcodes ---~%")
  (let ((pure-x11-gen::*window* 123) (pure-x11-gen::*gc-text* 456))
    (pure-x11-gen::with-buffered-output
     (pure-x11-gen::poly-fill-rectangle '((10 20 100 200)))
     (pure-x11-gen::imagetext8 "Hello" :x 10 :y 20)
     (pure-x11-gen::poly-rectangle '((10 20 100 200)))
     (let* ((packets (reverse pure-x11-gen::*packet-buffer*))
            (p-fill-rect (first packets)) (p-imagetext (second packets))
            (p-rect (third packets)))
       (assert-test (= (aref p-fill-rect 0) 70)
        "poly-fill-rectangle major opcode is 70")
       (assert-test (= (aref p-imagetext 0) 76) "imagetext8 major opcode is 76")
       (assert-test (= (aref p-rect 0) 74)
        "poly-rectangle major opcode is 74"))))
  (defun test-event-handlers ()
    (format t "--- Running test-event-handlers ---~%")
    (let* ((layout
            (pure-x11-gen::resolve-layout
             '(panel :name :main-panel :x 0 :y 0 :w 400 :h 300
               (button :name :b1 :x 10 :y 30 :w 100 :h 30 :msg :b1-clicked))))
           (pure-x11-gen::*window* 123) (pure-x11-gen::*gc-light* 1)
           (pure-x11-gen::*gc-face* 2) (pure-x11-gen::*gc-shadow* 3)
           (pure-x11-gen::*gc-dark* 4) (pure-x11-gen::*gc-text* 5)
           (pure-x11-gen::*resource-id-base* 0)
           (pure-x11-gen::*resource-id-mask* 1048575)
           (pure-x11-gen::*resource-id-counter* 0)
           (pure-x11-gen::*hovered-widget* nil)
           (pure-x11-gen::*pressed-widget* nil)
           (pure-x11-gen::*focused-widget* nil))
      (let ((reply
             (make-array 32 :element-type '(unsigned-byte 8) :initial-element
                         0)))
        (setf (aref reply 0) 6)
        (setf (aref reply 24) 15)
        (setf (aref reply 26) 45)
        (pure-x11-gen::handle-motion-event reply layout)
        (assert-test (eq pure-x11-gen::*hovered-widget* :b1)
         "Motion event updates hovered widget to :b1"))
      (let ((reply
             (make-array 32 :element-type '(unsigned-byte 8) :initial-element
                         0)))
        (setf (aref reply 0) 4)
        (setf (aref reply 1) 1)
        (setf (aref reply 24) 15)
        (setf (aref reply 26) 45)
        (pure-x11-gen::handle-button-press-event reply layout)
        (assert-test (eq pure-x11-gen::*pressed-widget* :b1)
         "ButtonPress updates pressed widget to :b1")
        (assert-test (eq pure-x11-gen::*focused-widget* :b1)
         "ButtonPress updates focused widget to :b1"))
      (let ((reply
             (make-array 32 :element-type '(unsigned-byte 8) :initial-element
                         0))
            (state-updated nil))
        (setf (aref reply 0) 5)
        (setf (aref reply 1) 1)
        (setf (aref reply 24) 15)
        (setf (aref reply 26) 45)
        (let ((new-state
               (pure-x11-gen::handle-button-release-event reply layout
                :init-state
                (lambda (s msg)
                  (setf state-updated
                          (and (eq s :init-state) (eq msg :b1-clicked)))
                  :new-state)
                (lambda ()))))
          (assert-test state-updated
           "ButtonRelease dispatched update-fn with widget :msg")
          (assert-test (eq new-state :new-state)
           "ButtonRelease returned updated state")
          (assert-test (null pure-x11-gen::*pressed-widget*)
           "ButtonRelease cleared pressed widget")))
      (let ((reply
             (make-array 32 :element-type '(unsigned-byte 8) :initial-element
                         0))
            (rebuilt nil))
        (setf (aref reply 0) 22)
        (setf (aref reply 20) 100)
        (setf (aref reply 21) 1)
        (setf (aref reply 22) 44)
        (setf (aref reply 23) 1)
        (pure-x11-gen::handle-configure-event reply layout
         (lambda ()
           (setf rebuilt t)))
        (assert-test rebuilt "ConfigureNotify triggers layout rebuild"))
      (let ((reply
             (make-array 32 :element-type '(unsigned-byte 8) :initial-element
                         0)))
        (setf (aref reply 0) 12)
        (pure-x11-gen::handle-expose-event layout)
        (assert-test t "Expose event handled cleanly"))
      (let ((reply
             (make-array 32 :element-type '(unsigned-byte 8) :initial-element
                         0))
            (kb-map
             (make-array '(256 2) :element-type '(unsigned-byte 32)
                         :initial-element 0)))
        (setf (aref reply 0) 2)
        (setf (aref reply 1) 24)
        (setf (aref kb-map 24 0) 113)
        (pure-x11-gen::handle-key-press-event reply layout :state kb-map
         (lambda (s msg)
           (declare (ignore s msg))
           :new-state)
         (lambda ()))
        (assert-test t "KeyPress event handled cleanly"))))
  (defun test-client-message-event ()
    (format t "--- Running test-client-message-event ---~%")
    (let ((pure-x11-gen::*wm-protocols-atom* 42)
          (pure-x11-gen::*wm-delete-window-atom* 99)
          (buf
           (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
      (setf (aref buf 0) 33
            (aref buf 1) 32
            (aref buf 2) 1
            (aref buf 4) 100
            (aref buf 8) 42
            (aref buf 12) 99)
      (multiple-value-bind (fmt win type d0 d1 d2 d3
                            d4) (pure-x11-gen::parse-client-message buf)
        (declare (ignore fmt win d1 d2 d3 d4))
        (assert-test (= type 42) "ClientMessage parsed type 42")
        (assert-test (= d0 99) "ClientMessage parsed data0 99"))
      (assert-test (eq (pure-x11-gen::handle-client-message-event buf) :close)
       "ClientMessage with WM_DELETE_WINDOW returned :close")))
  (defun test-put-image-big-req ()
    (format t "--- Running test-put-image-big-req ---~%")
    (let ((pure-x11-gen::*s* (make-broadcast-stream))
          (pure-x11-gen::*window* 123) (pure-x11-gen::*gc-text* 1)
          (img
           (make-array '(10 10 4) :element-type '(unsigned-byte 8)
                       :initial-element 255)))
      (pure-x11-gen::with-buffered-output
       (pure-x11-gen::poly-fill-rectangle '((0 0 10 10)))
       (assert-test (= (length pure-x11-gen::*packet-buffer*) 1)
        "Initial packet buffered")
       (pure-x11-gen::put-image-big-req img :dst-x 0 :dst-y 0)
       (assert-test (zerop (length pure-x11-gen::*packet-buffer*))
        "Packet buffer flushed before big request stream write"))))
  (defun test-canvas-pixmap-cleanup ()
    (format t "--- Running test-canvas-pixmap-cleanup ---~%")
    (let ((pure-x11-gen::*s* (make-broadcast-stream))
          (pure-x11-gen::*window* 123) (pure-x11-gen::*gc-face* 1)
          (pure-x11-gen::*gc-light* 2) (pure-x11-gen::*gc-shadow* 3)
          (pure-x11-gen::*gc-dark* 4) (pure-x11-gen::*gc-text* 5)
          (pure-x11-gen::*resource-id-base* 0)
          (pure-x11-gen::*resource-id-mask* 1048575)
          (pure-x11-gen::*resource-id-counter* 0))
      (pure-x11-gen::with-buffered-output
       (let ((w
              (pure-x11-gen::resolve-layout
               '(canvas :name :c1 :x 0 :y 0 :w 100 :h 100))))
         (pure-x11-gen::render-widget w nil nil nil)
         (let ((free-pixmap-packets
                (remove-if-not
                 (lambda (p)
                   (= (aref p 0) 54))
                 pure-x11-gen::*packet-buffer*)))
           (assert-test (= (length free-pixmap-packets) 1)
            "FreePixmap opcode 54 emitted during canvas render cleanup"))))))
  (defun test-live-x11-connection ()
    (format t "--- Running test-live-x11-connection ---~%")
    (let ((display (uiop/os:getenv "DISPLAY")))
      (if (and display (string/= display ""))
          (handler-case (let ((s (pure-x11-gen::connect-x11 display)))
                          (assert-test s "Connected to live X server socket")
                          (let ((pure-x11-gen::*s* s))
                            (pure-x11-gen::parse-initial-reply s)
                            (assert-test pure-x11-gen::*resource-id-base*
                             "Parsed initial reply resource ID base")
                            (let ((win (pure-x11-gen::next-resource-id))
                                  (wm-protocols
                                   (pure-x11-gen::intern-atom "WM_PROTOCOLS"))
                                  (wm-delete
                                   (pure-x11-gen::intern-atom
                                    "WM_DELETE_WINDOW")))
                              (assert-test (numberp wm-protocols)
                               "Interned WM_PROTOCOLS atom ID")
                              (assert-test (numberp wm-delete)
                               "Interned WM_DELETE_WINDOW atom ID")
                              (pure-x11-gen::make-window win 10 10 300 200)
                              (pure-x11-gen::change-property win wm-protocols 4
                               32 (vector wm-delete))
                              (pure-x11-gen::map-window win)
                              (assert-test t
                               "Created, configured, and mapped live X11 window")
                              (close s))))
            (error (e)
                   (format t
                           "FAIL: Live X11 connection test failed with error: ~a~%"
                           e)
                   (incf pure-x11-gen::*test-failures*)))
          (format t
                  "SKIP: DISPLAY not set, skipping live X11 integration test.~%"))))
  (defun run-all-tests ()
    (setf *test-failures* 0)
    (test-parse-node)
    (test-collect-focusable)
    (test-hit-testing)
    (test-cone-focus-search)
    (test-widget-registry)
    (test-glue-solver)
    (test-bevel-coordinates)
    (test-dirty-widgets)
    (test-x11-opcodes)
    (test-event-handlers)
    (test-client-message-event)
    (test-put-image-big-req)
    (test-canvas-pixmap-cleanup)
    (test-live-x11-connection)
    (if (zerop *test-failures*)
        (format t "ALL TESTS PASSED!~%")
        (progn
          (format t "SOME TESTS FAILED: ~a failures~%" *test-failures*)
          (sb-ext:exit :code 1)))))