;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-04 11:41:16
;; Git:       98f766809ab37c5e92243355aebe4b891fc4872a
(in-package :pure-x11-gen)

(defstruct widget type name x y w h props children)

(defun parse-node (node)
  "Parse a layout node into properties and children."
  (let ((type (car node)) (name nil) (x nil) (y nil) (w nil) (h nil)
        (props nil) (tail (cdr node)))
    (loop while (and tail (keywordp (car tail)))
          do (let ((key (pop tail)) (val (pop tail)))
               (case key
                 (:name (setf name val))
                 (:x (setf x val))
                 (:y (setf y val))
                 (:w (setf w val))
                 (:h (setf h val))
                 (t (setf props (list* key val props))))))
    (make-widget :type type :name name :x x :y y :w w :h h :props props
     :children tail)))

(defun resolve-layout (node &optional (default-x 0) (default-y 0) (default-w 0)
                       (default-h 0))
  "Recursively parse raw layout S-expressions into widget structures and resolve all layout coordinates."
  (when (listp node)
    (let ((w-struct (parse-node node)))
      (unless (widget-x w-struct)
        (setf (widget-x w-struct) default-x))
      (unless (widget-y w-struct)
        (setf (widget-y w-struct) default-y))
      (unless (widget-w w-struct)
        (setf (widget-w w-struct) default-w))
      (unless (widget-h w-struct)
        (setf (widget-h w-struct) default-h))
      (let* ((type (widget-type w-struct))
             (type-name
              (and type (symbolp type) (string-upcase (symbol-name type)))))
        (cond
          ((string= type-name "HBOX")
           (let ((layout-results (compute-box-layout w-struct :x)))
             (setf (widget-children w-struct)
                     (mapcar
                      (lambda (item)
                        (resolve-layout (first item) (second item) (third item)
                         (fourth item) (fifth item)))
                      layout-results))))
          ((string= type-name "VBOX")
           (let ((layout-results (compute-box-layout w-struct :y)))
             (setf (widget-children w-struct)
                     (mapcar
                      (lambda (item)
                        (resolve-layout (first item) (second item) (third item)
                         (fourth item) (fifth item)))
                      layout-results))))
          (t
           (setf (widget-children w-struct)
                   (mapcar
                    (lambda (child)
                      (if (listp child)
                          (resolve-layout child (widget-x w-struct)
                           (widget-y w-struct) (widget-w w-struct)
                           (widget-h w-struct))
                          child))
                    (widget-children w-struct))))))
      w-struct)))

(defun collect-focusable-widgets (node)
  "Recursively traverse the widget tree to collect all focusable widgets."
  (let ((result nil))
    (labels ((traverse (w)
              (when (widget-p w)
                (let ((type (widget-type w)))
                  (when (and type (symbolp type)
                             (member (symbol-name type)
                                     '("BUTTON" "CHECKBOX" "TEXT-INPUT") :test
                                     #'string-equal))
                    (push w result))
                  (dolist (child (widget-children w))
                    (traverse child))))))
      (traverse node))
    (nreverse result)))

(defun find-widget-at (node mx my)
  "Recursively search the widget tree for the leaf widget enclosing the mouse coordinates (mx, my)."
  (let ((found nil))
    (labels ((search-layout (w)
              (when (widget-p w)
                (let ((x (widget-x w)) (y (widget-y w)) (w-val (widget-w w))
                      (h (widget-h w)))
                  (when (and (>= mx x) (< mx (+ x w-val)) (>= my y)
                             (< my (+ y h)))
                    (setf found w)
                    (dolist (child (widget-children w))
                      (search-layout child)))))))
      (search-layout node))
    found))

(defun find-widget-by-name (node target-name)
  "Find a widget in the widget tree by its name."
  (let ((found nil))
    (labels ((search-layout (w)
              (when (widget-p w)
                (if (eq (widget-name w) target-name)
                    (setf found w)
                    (dolist (child (widget-children w))
                      (search-layout child))))))
      (search-layout node))
    found))

(defun find-nearest-widget (node current-name direction)
  "Find the next widget to focus from current-name in direction (:up, :down, :left, :right)."
  (let* ((widgets (collect-focusable-widgets node))
         (current (find current-name widgets :key #'widget-name)) (best nil)
         (best-dist nil))
    (unless current
      (return-from find-nearest-widget
        (and widgets (widget-name (car widgets)))))
    (let ((cx (+ (widget-x current) (floor (widget-w current) 2)))
          (cy (+ (widget-y current) (floor (widget-h current) 2)))
          (dir-vec
           (ecase direction
             (:right '(1 0))
             (:left '(-1 0))
             (:down '(0 1))
             (:up '(0 -1)))))
      (dolist (w widgets)
        (unless (eq (widget-name w) current-name)
          (let* ((tx (+ (widget-x w) (floor (widget-w w) 2)))
                 (ty (+ (widget-y w) (floor (widget-h w) 2))) (dx (- tx cx))
                 (dy (- ty cy)) (dist (+ (* dx dx) (* dy dy))))
            (let* ((dot (+ (* dx (car dir-vec)) (* dy (cadr dir-vec)))))
              (when (> dot 0)
                (let* ((cross (- (* dx (cadr dir-vec)) (* dy (car dir-vec))))
                       (in-cone-p (>= dot (abs cross))))
                  (when in-cone-p
                    (when (or (null best-dist) (< dist best-dist))
                      (setf best-dist dist
                            best (widget-name w)))))))))))
    best))

(defun translate-keycode (keyboard-map keycode state-mask)
  "Translate X11 keycode and shift modifier state to a Lisp character or keyword symbol."
  (let* ((first-keycode (car keyboard-map))
         (keysy-per-keycode (cadr keyboard-map))
         (map-data (caddr keyboard-map)) (idx (- keycode first-keycode)))
    (when (and (>= idx 0) (< idx (floor (length map-data) keysy-per-keycode)))
      (let* ((offset (* idx keysy-per-keycode))
             (shift-p (/= 0 (logand state-mask 1)))
             (keysym-code
              (aref map-data
                    (+ offset
                       (if shift-p
                           1
                           0)))))
        (cond
          ((and (>= keysym-code 32) (<= keysym-code 126))
           (code-char keysym-code))
          ((= keysym-code 65288) :backspace)
          ((= keysym-code 65293) :return)
          ((= keysym-code 65361) :left)
          ((= keysym-code 65362) :up)
          ((= keysym-code 65363) :right)
          ((= keysym-code 65364) :down)
          (t nil))))))

(defvar *widget-renderers* (make-hash-table :test 'equal))

(defun register-widget (type-name render-fn)
  "Register a render function for widget TYPE-NAME (a string or symbol like \"BUTTON\").
        RENDER-FN is called as (funcall render-fn widget-struct focused pressed hovered)."
  (setf (gethash (string-upcase (string type-name)) *widget-renderers*)
          render-fn))

(defun render-widget (w-struct focused pressed hovered)
  "Dispatch rendering to the registered handler for this widget's type."
  (let* ((type (widget-type w-struct))
         (type-name
          (and type (symbolp type) (string-upcase (symbol-name type))))
         (renderer
          (when type-name
            (gethash type-name *widget-renderers*))))
    (when renderer
      (funcall renderer w-struct focused pressed hovered))))

(defun render-layout (layout focused pressed hovered)
  "Render the root of the resolved widget tree."
  (when (widget-p layout)
    (render-widget layout focused pressed hovered)))

(defun render-layout-children (children focused pressed hovered)
  "Render a list of child widgets."
  (dolist (child children)
    (when (widget-p child)
      (render-widget child focused pressed hovered))))

(defun draw-bevel (x y w h &key (style :raised) (bevel-width 2))
  "Draw Xaw3d-style 3D bevel around a rectangle.
        :raised = light top-left, dark bottom-right (normal state)
        :sunken = dark top-left, light bottom-right (pressed/inset state)
        BEVEL-WIDTH is the thickness in pixels (default 2 for classic Xaw3d look)."
  (let ((tl-outer
         (if (eq style :raised)
             *gc-light*
             *gc-dark*))
        (br-outer
         (if (eq style :raised)
             *gc-dark*
             *gc-light*))
        (tl-inner
         (if (eq style :raised)
             *gc-face*
             *gc-shadow*))
        (br-inner
         (if (eq style :raised)
             *gc-shadow*
             *gc-face*)))
    (draw-line x y (+ x w -2) y :gc tl-outer)
    (draw-line x y x (+ y h -2) :gc tl-outer)
    (draw-line (+ x w -1) y (+ x w -1) (+ y h -1) :gc br-outer)
    (draw-line x (+ y h -1) (+ x w -1) (+ y h -1) :gc br-outer)
    (when (>= bevel-width 2)
      (draw-line (1+ x) (1+ y) (+ x w -3) (1+ y) :gc tl-inner)
      (draw-line (1+ x) (1+ y) (1+ x) (+ y h -3) :gc tl-inner)
      (draw-line (+ x w -2) (1+ y) (+ x w -2) (+ y h -2) :gc br-inner)
      (draw-line (1+ x) (+ y h -2) (+ x w -2) (+ y h -2) :gc br-inner))))

(defstruct glue (natural 0) (stretch 0) (shrink 0))

(defun solve-glue (glue-items available-space)
  "Distribute AVAILABLE-SPACE among GLUE-ITEMS (list of glue structs).
        Returns a list of computed sizes (integers), one per item.
        Algorithm: TeX's glue distribution — excess space is distributed
        proportionally to stretch factors; deficit proportionally to shrink factors."
  (let* ((total-natural
          (loop for g in glue-items
                sum (glue-natural g)))
         (excess (- available-space total-natural)))
    (cond
      ((>= excess 0)
       (let ((total-stretch
              (loop for g in glue-items
                    sum (glue-stretch g))))
         (if (zerop total-stretch)
             (mapcar #'glue-natural glue-items)
             (mapcar
              (lambda (g)
                (+ (glue-natural g)
                   (round (* excess (/ (glue-stretch g) total-stretch)))))
              glue-items))))
      (t
       (let ((total-shrink
              (loop for g in glue-items
                    sum (glue-shrink g))))
         (if (zerop total-shrink)
             (mapcar #'glue-natural glue-items)
             (mapcar
              (lambda (g)
                (max 0
                     (+ (glue-natural g)
                        (round (* excess (/ (glue-shrink g) total-shrink))))))
              glue-items)))))))

(defun compute-box-layout (w-struct axis)
  "Compute absolute positions for children of an hbox (axis=:x) or vbox (axis=:y).
        Reads :glue, :padding, :spacing from widget props and children.
        Returns a list of (child-node x y w h) tuples with resolved positions."
  (let* ((props (widget-props w-struct)) (padding (or (getf props :padding) 0))
         (spacing (or (getf props :spacing) 0))
         (container-x (widget-x w-struct)) (container-y (widget-y w-struct))
         (container-w (widget-w w-struct)) (container-h (widget-h w-struct))
         (children (widget-children w-struct)) (n (length children))
         (total-spacing (* spacing (max 0 (1- n))))
         (main-available
          (-
           (if (eq axis :x)
               container-w
               container-h)
           (* 2 padding) total-spacing))
         (child-glues
          (mapcar
           (lambda (child)
             (if (listp child)
                 (let* ((cw (parse-node child))
                        (g (getf (widget-props cw) :glue)))
                   (if g
                       (make-glue :natural (or (getf g :natural) 0) :stretch
                        (or (getf g :stretch) 0) :shrink
                        (or (getf g :shrink) 0))
                       (make-glue :natural
                        (if (eq axis :x)
                            (or (widget-w cw) 0)
                            (or (widget-h cw) 0))
                        :stretch 0 :shrink 0)))
                 (make-glue)))
           children))
         (sizes (solve-glue child-glues main-available)) (result nil)
         (pos
          (+
           (if (eq axis :x)
               container-x
               container-y)
           padding)))
    (loop for child in children
          for size in sizes
          do (let* ((cx
                     (if (eq axis :x)
                         pos
                         (+ container-x padding)))
                    (cy
                     (if (eq axis :x)
                         (+ container-y padding)
                         pos))
                    (cw-val
                     (if (eq axis :x)
                         size
                         (- container-w (* 2 padding))))
                    (ch-val
                     (if (eq axis :x)
                         (- container-h (* 2 padding))
                         size)))
               (push (list child cx cy cw-val ch-val) result)
               (incf pos (+ size spacing))))
    (nreverse result)))