;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-22 20:11:25
;; Git:       dd18ff9f50eb967082d3e6d7df46e3863bf43548
(in-package :pure-x11-gen)

(register-widget "PANEL"
 (lambda (w-struct focused pressed hovered)
   (let ((x (widget-x w-struct)) (y (widget-y w-struct))
         (w (widget-w w-struct)) (h (widget-h w-struct)))
     (poly-fill-rectangle (list (list x y w h)) :gc *gc-face*)
     (draw-bevel x y w h :style :raised)
     (render-layout-children (widget-children w-struct) focused pressed
      hovered))))

(register-widget "HBOX"
 (lambda (w-struct focused pressed hovered)
   (render-layout-children (widget-children w-struct) focused pressed hovered)))

(register-widget "VBOX"
 (lambda (w-struct focused pressed hovered)
   (render-layout-children (widget-children w-struct) focused pressed hovered)))

(register-widget "LABEL"
 (lambda (w-struct focused pressed hovered)
   (let* ((props (widget-props w-struct)) (text (getf props :text ""))
          (x (widget-x w-struct)) (y (widget-y w-struct)))
     (imagetext8 text :x x :y y :gc *gc-text*))))

(register-widget "BUTTON"
 (lambda (w-struct focused pressed hovered)
   (let* ((x (widget-x w-struct)) (y (widget-y w-struct))
          (w (widget-w w-struct)) (h (widget-h w-struct))
          (name (widget-name w-struct)) (props (widget-props w-struct))
          (text (getf props :text "")) (is-pressed-p (eq name pressed))
          (text-x (+ x (floor (- w (* 6 (length text))) 2)))
          (text-y (+ y (floor h 2) 4)))
     (poly-fill-rectangle (list (list x y w h)) :gc *gc-face*)
     (if is-pressed-p
         (progn
           (draw-bevel x y w h :style :sunken)
           (imagetext8 text :x (1+ text-x) :y (1+ text-y) :gc *gc-text*))
         (progn
           (draw-bevel x y w h :style :raised)
           (imagetext8 text :x text-x :y text-y :gc *gc-text*))))))

(register-widget "CHECKBOX"
 (lambda (w-struct focused pressed hovered)
   (let* ((x (widget-x w-struct)) (y (widget-y w-struct))
          (w (widget-w w-struct)) (h (widget-h w-struct))
          (name (widget-name w-struct)) (props (widget-props w-struct))
          (label (getf props :label "")) (checked-p (getf props :checked-p))
          (is-focused-p (eq name focused)) (bx (+ x 2))
          (by (+ y (floor (- h 14) 2))) (text-x (+ x 22))
          (text-y (+ y (floor h 2) 4)))
     (poly-fill-rectangle (list (list (+ bx 2) (+ by 2) 10 10)) :gc *gc-light*)
     (draw-bevel bx by 14 14 :style :sunken :bevel-width 2)
     (when checked-p
       (imagetext8 "X" :x (+ bx 4) :y (+ by 11) :gc *gc-text*))
     (imagetext8 label :x text-x :y text-y :gc *gc-text*)
     (when is-focused-p
       (poly-rectangle
        (list (list (1- text-x) (- text-y 12) (+ (* 6 (length label)) 2) 16))
        :gc *gc-text*)))))

(register-widget "TEXT-INPUT"
 (lambda (w-struct focused pressed hovered)
   (let* ((x (widget-x w-struct)) (y (widget-y w-struct))
          (w (widget-w w-struct)) (h (widget-h w-struct))
          (name (widget-name w-struct)) (props (widget-props w-struct))
          (text (getf props :text "")) (cursor-pos (getf props :cursor-pos 0))
          (is-focused-p (eq name focused)) (text-x (+ x 6))
          (text-y (+ y (floor h 2) 4)))
     (poly-fill-rectangle (list (list (+ x 2) (+ y 2) (- w 4) (- h 4))) :gc
      *gc-light*)
     (draw-bevel x y w h :style :sunken :bevel-width 2)
     (imagetext8 text :x text-x :y text-y :gc *gc-text*)
     (when is-focused-p
       (let ((cx (+ text-x (* 6 cursor-pos))))
         (draw-line cx (+ y 4) cx (+ y h -4) :gc *gc-text*))))))

(defun power-of-ten-nice-spacing (val)
  "Find a nice tick spacing close to val (e.g. 0.1, 0.2, 0.5, 1.0, 2.0, 5.0...)."
  (if (<= val 0)
      1.0
      (let* ((pow (floor (log val 10))) (base (expt 10.0 pow))
             (ratio (/ val base)))
        (cond
          ((< ratio 1.5) base)
          ((< ratio 3.0) (* 2.0 base))
          ((< ratio 7.5) (* 5.0 base))
          (t (* 10.0 base))))))

(register-widget "CANVAS"
 (lambda (w-struct focused pressed hovered)
   (declare (ignore focused pressed hovered))
   (let ((x (widget-x w-struct)) (y (widget-y w-struct))
         (w (widget-w w-struct)) (h (widget-h w-struct))
         (props (widget-props w-struct)))
     (draw-bevel x y w h :style :sunken)
     (let* ((dw (- w 4)) (dh (- h 4)) (win-id *window*)
            (pix (next-resource-id)))
       (create-pixmap pix dw dh :depth (or *root-depth* 24))
       (unwind-protect (progn
                         (let ((*window* pix) (xmin (getf props :xmin -1.8))
                               (xmax (getf props :xmax 1.8))
                               (ymin (getf props :ymin -1.8))
                               (ymax (getf props :ymax 1.8))
                               (shapes (getf props :shapes nil))
                               (draw-axes-p (getf props :draw-axes-p t)))
                           (poly-fill-rectangle (list (list 0 0 dw dh)) :gc
                            *gc-light*)
                           (labels ((to-screen-x (wx)
                                     (round
                                      (* dw (/ (- wx xmin) (- xmax xmin)))))
                                    (to-screen-y (wy)
                                     (+ dh -1
                                        (round
                                         (* (- dh)
                                            (/ (- wy ymin) (- ymax ymin))))))
                                    (draw-world-line
                                     (x1 y1 x2 y2 &key (gc *gc-text*))
                                     (draw-line (to-screen-x x1)
                                      (to-screen-y y1) (to-screen-x x2)
                                      (to-screen-y y2) :gc gc))
                                    (draw-world-circle
                                     (cx cy r &key (gc *gc-text*) fill-p)
                                     (let* ((sx1 (to-screen-x (- cx r)))
                                            (sy1 (to-screen-y (+ cy r)))
                                            (sx2 (to-screen-x (+ cx r)))
                                            (sy2 (to-screen-y (- cy r)))
                                            (sw (- sx2 sx1)) (sh (- sy2 sy1)))
                                       (if fill-p
                                           (poly-fill-arc
                                            (list (list sx1 sy1 sw sh 0 23040))
                                            :gc gc)
                                           (poly-arc
                                            (list (list sx1 sy1 sw sh 0 23040))
                                            :gc gc)))))
                             (declare
                              (ignorable (function draw-world-line)
                               (function draw-world-circle)))
                             (let ((x-axis-y
                                    (if (<= ymin 0 ymax)
                                        0.0
                                        ymin))
                                   (y-axis-x
                                    (if (<= xmin 0 xmax)
                                        0.0
                                        xmin)))
                               (let* ((x-range (- xmax xmin))
                                      (x-spacing
                                       (power-of-ten-nice-spacing
                                        (/ x-range 8)))
                                      (start-x-tick
                                       (* (ceiling (/ xmin x-spacing))
                                          x-spacing)))
                                 (loop for tx = start-x-tick then (+ tx
                                                                     x-spacing)
                                       while (<= tx xmax)
                                       do (let ((tsx (to-screen-x tx)))
                                            (draw-line tsx 0 tsx dh :gc
                                             *gc-face*))))
                               (let* ((y-range (- ymax ymin))
                                      (y-spacing
                                       (power-of-ten-nice-spacing
                                        (/ y-range 8)))
                                      (start-y-tick
                                       (* (ceiling (/ ymin y-spacing))
                                          y-spacing)))
                                 (loop for ty = start-y-tick then (+ ty
                                                                     y-spacing)
                                       while (<= ty ymax)
                                       do (let ((tsy (to-screen-y ty)))
                                            (draw-line 0 tsy dw tsy :gc
                                             *gc-face*))))
                               (when draw-axes-p
                                 (draw-world-line xmin x-axis-y xmax x-axis-y
                                  :gc *gc-shadow*)
                                 (draw-world-line y-axis-x ymin y-axis-x ymax
                                  :gc *gc-shadow*)
                                 (let* ((x-range (- xmax xmin))
                                        (tick-spacing
                                         (power-of-ten-nice-spacing
                                          (/ x-range 8)))
                                        (start-tick
                                         (* (ceiling (/ xmin tick-spacing))
                                            tick-spacing)))
                                   (loop for tx = start-tick then (+ tx
                                                                     tick-spacing)
                                         while (<= tx xmax)
                                         do (let ((tsx (to-screen-x tx))
                                                  (tsy (to-screen-y x-axis-y)))
                                              (draw-line tsx (- tsy 4) tsx
                                               (+ tsy 4) :gc *gc-dark*)
                                              (let ((lbl
                                                     (format nil "~,2f" tx)))
                                                (imagetext8 lbl :x
                                                 (- tsx (* 3 (length lbl))) :y
                                                 (+ tsy 14) :gc *gc-text*)))))
                                 (let* ((y-range (- ymax ymin))
                                        (tick-spacing
                                         (power-of-ten-nice-spacing
                                          (/ y-range 8)))
                                        (start-tick
                                         (* (ceiling (/ ymin tick-spacing))
                                            tick-spacing)))
                                   (loop for ty = start-tick then (+ ty
                                                                     tick-spacing)
                                         while (<= ty ymax)
                                         do (unless (= 0 (round ty))
                                              (let ((tsx
                                                     (to-screen-x y-axis-x))
                                                    (tsy (to-screen-y ty)))
                                                (draw-line (- tsx 4) tsy
                                                 (+ tsx 4) tsy :gc *gc-dark*)
                                                (let ((lbl
                                                       (format nil "~,2f" ty)))
                                                  (imagetext8 lbl :x
                                                   (- tsx (* 6 (length lbl)) 6)
                                                   :y (+ tsy 4) :gc
                                                   *gc-text*))))))))
                             (dolist (shape shapes)
                               (when shape
                                 (let ((type (car shape)) (args (cdr shape)))
                                   (case type
                                     (:line
                                      (destructuring-bind (lx1 ly1 lx2 ly2 &key
                                                           (color
                                                            *gc-text*)) args
                                        (draw-world-line lx1 ly1 lx2 ly2 :gc
                                         color)))
                                     (:circle
                                      (destructuring-bind (cx cy r &key
                                                           (color
                                                            *gc-text*)) args
                                        (draw-world-circle cx cy r :gc color
                                         :fill-p nil)))
                                     (:disk
                                      (destructuring-bind (cx cy r &key
                                                           (color
                                                            *gc-text*)) args
                                        (draw-world-circle cx cy r :gc color
                                         :fill-p t)))
                                     (:text
                                      (destructuring-bind (str tx ty &key
                                                           (color
                                                            *gc-text*)) args
                                        (imagetext8 str :x (to-screen-x tx) :y
                                         (to-screen-y ty) :gc color)))
                                     (:poly-line
                                      (destructuring-bind (points &key
                                                           (color
                                                            *gc-text*)) args
                                        (loop for (p1 p2) on points by #'cdr
                                              while p2
                                              do (draw-world-line (car p1)
                                                  (cadr p1) (car p2) (cadr p2)
                                                  :gc color)))))))))))
         (copy-area pix win-id *gc-text* 0 0 (+ x 2) (+ y 2) dw dh))
       (free-pixmap pix)))))