;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 22:06:35
;; Git:       de1029b4417e8b947224662d19bc8fbcd764f7c3
(in-package :pure-x11-gen)

(defparameter *s* nil "Socket for communication with X server.")

(defparameter *resp* nil "Reply of the X server to a request")

(defparameter *root*
  nil
  "Root ID as extracted from the initial reply of the X server.")

(defparameter *window* nil)

(defparameter *gc* nil)

(defparameter *gc2* nil)

(defparameter *big-request-opcode* nil)

(defun pad (n)
  "Difference to next number that is divisible by 4."
  (if (= 0 (mod n 4))
      0
      (- (* 4 (1+ (floor n 4))) n)))

;; Macros for packet writing and reply reading

(defmacro with-packet (&body body)
  "Write values into a list of bytes and send over the socket *s*."
  `(let* ((l ()))
     (labels ((string8 (a)
                (declare (type string a))
                (loop for i below (length a) do
                  (push (char-code (aref a i)) l)))
              (card8 (a)
                (declare ((unsigned-byte 8) a))
                (push a l))
              (card16 (a)
                (declare ((unsigned-byte 16) a))
                (dotimes (i 2)
                  (push (ldb (byte 8 (* 8 i)) a) l)))
              (card32 (a)
                (declare ((unsigned-byte 32) a))
                (dotimes (i 4)
                  (push (ldb (byte 8 (* 8 i)) a) l))))
       ,@body
       (let ((buf (make-array (length l)
                              :element-type '(unsigned-byte 8)
                              :initial-contents (nreverse l))))
         (write-sequence buf *s*)
         (force-output *s*)))))



(defmacro with-reply (buf &body body)
  "Parse a socket reply buffer."
  (let ((r (gensym)))
    `(let ((,r ,buf)
           (current 0))
       (labels ((card8 ()
                  (prog1
                      (aref ,r current)
                    (incf current)))
                (card16 ()
                  (prog1
                      (+ (aref ,r current)
                         (* 256 (aref ,r (1+ current))))
                    (incf current 2)))
                (int16 ()
                  (let ((v (card16)))
                    (if (< v (ash 1 15))
                        v
                        (- v (ash 1 16)))))
                (card32 ()
                  (prog1
                      (+ (aref ,r current)
                         (* 256 (+ (aref ,r (1+ current))
                                   (* 256 (+ (aref ,r (+ 2 current))
                                             (* 256 (aref ,r (+ 3 current))))))))
                    (incf current 4)))
                (string8 (n)
                  (prog1
                      (map 'string #'code-char (subseq ,r current (+ current n)))
                    (incf current n)))
                (inc-current (n)
                  (incf current n)))
         ,@body))))


(defun read-reply-wait ()
  "Read standard 32-byte reply header and optional variable-length body from *s*."
  (let* ((buf (make-array 32 :element-type '(unsigned-byte 8))))
    (read-sequence buf *s*)
    (with-reply buf
     (let ((reply (card8)) (unused (card8)) (sequence-number (card16))
           (reply-length (card32)))
       (declare (ignorable reply unused))
       (if (or (= reply 0) (< 1 reply) (and (= reply 1) (= 0 reply-length)))
           (values buf sequence-number)
           (let ((m
                  (make-array (* 4 reply-length) :element-type
                              '(unsigned-byte 8))))
             (read-sequence m *s*)
             (values (concatenate '(vector (unsigned-byte 8)) buf m)
                     sequence-number)))))))

(defun read-connection-response ()
  "Read the initial connection response from X server."
  (let ((buf (make-array 8 :element-type '(unsigned-byte 8))))
    (sb-sys:read-n-bytes *s* buf 0 (length buf))
    (with-reply buf
     (let ((success-state (card8)) (length-of-reason (card8))
           (protocol-major-version (card16)) (protocol-minor-version (card16))
           (reply-length (card16)))
       (let ((m
              (make-array (+ 8 (* 4 reply-length)) :element-type
                          '(unsigned-byte 8))))
         (dotimes (i 8)
           (setf (aref m i) (aref buf i)))
         (sb-sys:read-n-bytes *s* m 8 (* 4 reply-length))
         (ecase success-state
           (0 (error "Connection failed"))
           (2 (error "Authentication required"))
           (1 m)))))))

(defun parse-initial-reply (r)
  "Extract connection constants and root ID from initial response."
  (with-reply r
   (let* ((success (card8)) (unused (card8)) (protocol-major (card16))
          (protocol-minor (card16)) (length (card16)) (release (card32))
          (resource-id-base (card32)) (resource-id-mask (card32))
          (motion-buffer-size (card32)) (length-of-vendor (card16))
          (maximum-request-length (card16)) (number-of-screens (card8))
          (number-of-formats (card8)) (image-byte-order (card8))
          (bitmap-format-bit-order (card8))
          (bitmap-format-scanline-unit (card8))
          (bitmap-format-scanline-pad (card8)) (min-keycode (card8))
          (max-keycode (card8)) (unused2 (card32))
          (vendor (string8 length-of-vendor))
          (unused3 (inc-current (pad length-of-vendor))))
     (unless (= 1 success)
       (error "Connection didn't succeed."))
     (defparameter *resource-id-base* resource-id-base)
     (defparameter *resource-id-mask* resource-id-mask)
     (dotimes (i number-of-formats)
       (let ((depth (card8)) (bpp (card8)) (scanline-pad (card8))
             (unused (inc-current 5)))
         (declare (ignorable depth bpp scanline-pad unused))))
     (dotimes (i number-of-screens)
       (let ((root (card32)) (default-colormap (card32)) (white-pixel (card32))
             (black-pixel (card32)) (current-input-mask (card32))
             (width (card16)) (height (card16)) (width-in-mm (card16))
             (height-in-mm (card16)) (min-installed-maps (card16))
             (max-installed-maps (card16)) (root-visual (card32))
             (backing-stores (card8)) (save-unders (card8))
             (root-depth (card8)) (number-of-allowed-depths (card8)))
         (declare
          (ignorable default-colormap white-pixel black-pixel
           current-input-mask width height width-in-mm height-in-mm
           min-installed-maps max-installed-maps root-visual backing-stores
           save-unders root-depth number-of-allowed-depths))
         (defparameter *root* root)
         (dotimes (i number-of-allowed-depths)
           (let ((depth (card8)) (unused (card8)) (number-of-visuals (card16))
                 (unused2 (card32)))
             (declare (ignorable depth unused number-of-visuals unused2))
             (dotimes (j number-of-visuals)
               (let ((visual-id (card32)) (class (card8))
                     (bits-per-rgb (card8)) (colormap-entries (card16))
                     (red-mask (card32)) (green-mask (card32))
                     (blue-mask (card32)) (unused (card32)))
                 (declare
                  (ignorable visual-id class bits-per-rgb colormap-entries
                   red-mask green-mask blue-mask unused)))))))))))

(defun connect (&key (ip #(127 0 0 1)) (filename nil) (port 6000))
  "Connect to the X server."
  (defparameter *s*
    (if filename
        (socket-make-stream
         (let ((s (make-instance 'local-socket :type :stream)))
           (socket-connect s filename)
           s)
         :element-type '(unsigned-byte 8) :input t :output t :buffering :none)
        (socket-make-stream
         (let ((s (make-instance 'inet-socket :type :stream :protocol :tcp)))
           (socket-connect s ip port)
           s)
         :element-type '(unsigned-byte 8) :input t :output t :buffering :none)))
  (with-packet (card8 108) (card8 0) (card16 11) (card16 0) (card16 0)
   (card16 0) (card16 0))
  (setf *resp* (read-connection-response))
  (parse-initial-reply *resp*)
  (big-requests-enable))

;; Flag and Option Lookups
(defparameter *set-of-value-mask*
  '((background-pixmap 1) (background-pixel 2) (border-pixmap 4)
    (border-pixel 8) (bit-gravity 16) (win-gravity 32) (backing-store 64)
    (backing-planes 128) (backing-pixel 256) (override-redirect 512)
    (save-under 1024) (event-mask 2048) (do-not-propagate-mask 4096)
    (colormap 8192) (cursor 16384)))

(defparameter *set-of-event*
  '((keypress 1) (keyrelease 2) (buttonpress 4) (buttonrelease 8)
    (enterwindow 16) (leavewindow 32) (pointermotion 64)
    (pointermotionhint 128) (button1motion 256) (button2motion 512)
    (button3motion 1024) (button4motion 2048) (button5motion 4096)
    (buttonmotion 8192) (keymapstate 16384) (exposure 32768)
    (visibilitychange 65536) (structurenotify 131072) (resizeredirect 262144)
    (substructurenotify 524288) (substructureredirect 1048576)
    (focuschange 2097152) (propertychange 4194304) (colormapchange 8388608)
    (ownergrabbutton 16777216)))

(defparameter *set-of-key-button*
  '((shift 1) (lock 2) (control 4) (mod1 8) (mod2 16) (mod3 32) (mod4 64)
    (mod5 128) (button1 256) (button2 512) (button3 1024) (button4 2048)
    (button5 4096)))

(defun value (es)
  (flet ((lookup (e) (cadr (assoc e *set-of-value-mask*))))
    (if (listp es)
        (loop for e in es
              sum (lookup e))
        (lookup es))))

(defun event (es)
  (flet ((lookup (e) (cadr (assoc e *set-of-event*))))
    (if (listp es)
        (loop for e in es
              sum (lookup e))
        (lookup es))))

(defun key-button (es)
  (flet ((lookup (e) (cadr (assoc e *set-of-key-button*))))
    (if (listp es)
        (loop for e in es
              sum (lookup e))
        (lookup es))))

;; Dynamically Generated Request APIs
(defun make-window (&key (width 512) (height 512) (x 0) (y 0) (border 1))
  "Create a window and map it, creating GCs for white/black pixel foregrounds."
  (let* ((window (logior *resource-id-base* (logand *resource-id-mask* 1)))
         (gc (logior *resource-id-base* (logand *resource-id-mask* 2)))
         (gc2 (logior *resource-id-base* (logand *resource-id-mask* 3)))
         (vals
          '(colormap backing-store event-mask bit-gravity border-pixel
            background-pixel))
         (n (length vals)))
    (with-packet (card8 1) (card8 0) (card16 (+ 8 n)) (card32 window)
     (card32 *root*) (card16 x) (card16 y) (card16 width) (card16 height)
     (card16 border) (card16 0) (card32 0) (card32 (value vals)) (card32 0)
     (card32 16777215) (card32 5) (card32 1)
     (card32 (event '(pointermotion buttonpress buttonrelease exposure)))
     (card32 0) (card8 55) (card8 0) (card16 6) (card32 gc) (card32 window)
     (card32 12) (card32 16777215) (card32 0) (card8 55) (card8 0) (card16 6)
     (card32 gc2) (card32 window) (card32 12) (card32 0) (card32 16777215)
     (card8 8) (card8 0) (card16 2) (card32 window))
    (defparameter *window* window)
    (defparameter *gc* gc)
    (defparameter *gc2* gc2)
    window))

(defun map-window (window)
  "Map the window, making it visible."
  (progn
    (with-packet (card8 8) (card8 0) (card16 2) (card32 window))))

(defun destroy-window (window)
  "Destroy the window."
  (progn
    (with-packet (card8 4) (card8 0) (card16 2) (card32 window))))

(defun change-window-attributes (window value-mask values)
  "Change attributes of the window."
  (progn
    (with-packet (card8 2) (card8 0) (card16 (+ 3 (length values)))
     (card32 window) (card32 value-mask)
     (dolist (v values)
       (card32 v)))))

(defun configure-window (window value-mask values)
  "Configure geometric and stacking parameters of the window."
  (progn
    (with-packet (card8 12) (card8 0) (card16 (+ 3 (length values)))
     (card32 window) (card16 value-mask) (card16 0)
     (dolist (v values)
       (card32 v)))))

(defun clear-area (&key (x 0) (y 0) (w 0) (h 0) (exposures 0))
  "Clear a rectangular area in the window."
  (progn
    (with-packet (card8 61) (card8 exposures) (card16 4) (card32 *window*)
     (card16 x) (card16 y) (card16 w) (card16 h))))

(defun draw-window (x1 y1 x2 y2 &key (gc '*gc*))
  "Draw a single line segment from (x1 y1) to (x2 y2)."
  (declare ((unsigned-byte 16) x1 y1 x2 y2))
  (let* ((segs (list (list x1 y1 x2 y2))))
    (with-packet (card8 66) (card8 0) (card16 (+ 3 (* 2 (length segs))))
     (card32 *window*) (card32 gc)
     (dolist (s segs)
       (dolist (p s)
         (card16 p))))))

(defun query-pointer ()
  "Query pointer coordinates and modifiers."
  (progn
    (with-packet (card8 38) (card8 0) (card16 2) (card32 *window*))
    (with-reply (read-reply-wait)
     (let* ((reply (card8)) (same-screen (card8)) (sequence-number (card16))
            (reply-length (card32)) (root (card32)) (child (card32))
            (root-x (card16)) (root-y (card16)) (win-x (card16))
            (win-y (card16)))
       (values root-x root-y win-x win-y)))))

(defun imagetext8 (str &key (x 0) (y 0))
  "Draw text string on the window."
  (let* ((n (length str)) (p (pad n)))
    (with-packet (card8 76) (card8 n) (card16 (+ 4 (/ (+ n p) 4)))
     (card32 *window*) (card32 *gc*) (card16 x) (card16 y) (string8 str)
     (dotimes (i p)
       (card8 0)))))

(defun query-extension (name)
  "Query if an extension is supported and get its major opcode."
  (declare (type string name))
  (let* ((n (length name)) (p (pad n)))
    (with-packet (card8 98) (card8 0) (card16 (+ 2 (floor (+ n p) 4)))
     (card16 n) (card16 0) (string8 name)
     (dotimes (i p)
       (card8 0)))
    (with-reply (read-reply-wait)
     (let* ((reply (card8)) (unused (card8)) (sequence-number (card16))
            (reply-length (card32)) (present (card8)) (major-opcode (card8))
            (first-event (card8)) (first-error (card8)))
       major-opcode))))

(defun big-requests-enable ()
  "Enable support for requests larger than 256KB."
  (let* ((opcode
          (unless *big-request-opcode*
            (setf *big-request-opcode* (query-extension "BIG-REQUESTS")))))
    (with-packet (card8 *big-request-opcode*) (card8 0) (card16 1))))

(defun put-image-big-req (img &key (dst-x 0) (dst-y 0))
  "Upload image data to the window using big requests."
  (declare (type (simple-array (unsigned-byte 8) 3) img)
           (type (unsigned-byte 16) dst-x dst-y))
  (let* ((h-w-c (array-dimensions img)) (h (first h-w-c)) (w (second h-w-c))
         (img1 (sb-ext:array-storage-vector img)) (n (length img1)) (p (pad n)))
    (with-packet (card8 72) (card8 2) (card16 0) (card32 (+ 7 (/ (+ n p) 4)))
     (card32 *window*) (card32 *gc*) (card16 w) (card16 h) (card16 dst-x)
     (card16 dst-y) (card8 0) (card8 24) (card16 0))
    (write-sequence img1 *s*)
    (dotimes (i p)
      (write-byte 0 *s*))
    (force-output *s*)))

(defun free-gc (gc)
  "Free a graphics context."
  (progn
    (with-packet (card8 60) (card8 0) (card16 2) (card32 gc))))

(defun create-cursor (cid source-font mask-font source-char mask-char &key
                      (fore-red 0) (fore-green 0) (fore-blue 0)
                      (back-red 65535) (back-green 65535) (back-blue 65535))
  "Create a cursor from source and mask font glyphs."
  (progn
    (with-packet (card8 94) (card8 0) (card16 8) (card32 cid)
     (card32 source-font) (card32 mask-font) (card16 source-char)
     (card16 mask-char) (card16 fore-red) (card16 fore-green)
     (card16 fore-blue) (card16 back-red) (card16 back-green)
     (card16 back-blue))))

(defun open-font (fid name)
  "Open a server-side font by name."
  (declare (type string name))
  (let* ((n (length name)) (p (pad n)))
    (with-packet (card8 45) (card8 0) (card16 (+ 3 (/ (+ n p) 4))) (card32 fid)
     (card16 n) (card16 0) (string8 name)
     (dotimes (i p)
       (card8 0)))))

(defun close-font (fid)
  "Close an opened font."
  (progn
    (with-packet (card8 46) (card8 0) (card16 2) (card32 fid))))

(defun grab-pointer (grab-window event-mask &key (owner-events 0)
                     (pointer-mode 1) (keyboard-mode 1) (confine-to 0)
                     (cursor 0) (time 0))
  "Actively grab control of the pointer."
  (progn
    (with-packet (card8 26) (card8 owner-events) (card16 6)
     (card32 grab-window) (card16 event-mask) (card8 pointer-mode)
     (card8 keyboard-mode) (card32 confine-to) (card32 cursor) (card32 time))
    (with-reply (read-reply-wait)
     (let* ((reply (card8)) (status (card8)) (sequence-number (card16))
            (reply-length (card32)) (unused (inc-current 24)))
       status))))

(defun ungrab-pointer (&key (time 0))
  "Release pointer grab."
  (progn
    (with-packet (card8 27) (card8 0) (card16 2) (card32 time))))

(defun get-keyboard-mapping (first-keycode count)
  "Query keyboard layout mapping."
  (progn
    (with-packet (card8 101) (card8 0) (card16 2) (card8 first-keycode)
     (card8 count) (card16 0))
    (let* ((num-keysyms (* count keysyms-per-keycode))
           (keysyms (make-array num-keysyms :element-type '(unsigned-byte 32))))
      (dotimes (i num-keysyms)
        (setf (aref keysyms i) (card32)))
      (values keysyms keysyms-per-keycode))
    (with-reply (read-reply-wait)
     (let* ((reply (card8)) (keysyms-per-keycode (card8))
            (sequence-number (card16)) (reply-length (card32))
            (unused (inc-current 24)))
       (values keysyms keysyms-per-keycode)))))

;; Dynamically Generated Event Parsers
(defun parse-expose (r)
  "Parse Expose event."
  (with-reply r
   (let* ((code (card8)) (unused (card8)) (sequence-number (card16))
          (window (card32)) (x (card16)) (y (card16)) (width (card16))
          (height (card16)) (count (card16)) (unused2 (inc-current 14)))
     (assert (= 12 code))
     (values sequence-number window x y width height count))))

(defun parse-motion-notify (r)
  "Parse MotionNotify event."
  (with-reply r
   (let* ((code (card8)) (detail (card8)) (sequence-number (card16))
          (time (card32)) (root-window (card32)) (event-window (card32))
          (child-window (card32)) (root-x (card16)) (root-y (card16))
          (event-x (card16)) (event-y (card16)) (state (card16))
          (same-screen-p (card8)) (unused (card8)))
     (assert (= 6 code))
     (values event-x event-y state time))))

(defun parse-button-press (r)
  "Parse ButtonPress event."
  (with-reply r
   (let* ((code (card8)) (detail (card8)) (sequence-number (card16))
          (time (card32)) (root-window (card32)) (event-window (card32))
          (child-window (card32)) (root-x (card16)) (root-y (card16))
          (event-x (card16)) (event-y (card16)) (state (card16))
          (same-screen-p (card8)) (unused (card8)))
     (assert (= 4 code))
     (values detail event-x event-y state time))))

(defun parse-button-release (r)
  "Parse ButtonRelease event."
  (with-reply r
   (let* ((code (card8)) (detail (card8)) (sequence-number (card16))
          (time (card32)) (root-window (card32)) (event-window (card32))
          (child-window (card32)) (root-x (card16)) (root-y (card16))
          (event-x (card16)) (event-y (card16)) (state (card16))
          (same-screen-p (card8)) (unused (card8)))
     (assert (= 5 code))
     (values detail event-x event-y state time))))

(defun parse-key-press (r)
  "Parse KeyPress event."
  (with-reply r
   (let* ((code (card8)) (detail (card8)) (sequence-number (card16))
          (time (card32)) (root-window (card32)) (event-window (card32))
          (child-window (card32)) (root-x (card16)) (root-y (card16))
          (event-x (card16)) (event-y (card16)) (state (card16))
          (same-screen-p (card8)) (unused (card8)))
     (assert (= 2 code))
     (values detail event-x event-y state time))))