// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
mod shapes;

use crate::shapes::{total_area, Circle, Rect, Shape};

trait WidgetDyn {
    fn widget(&self) -> &Widget;

    fn widget_mut(&mut self) -> &mut Widget;

    fn width(&self) -> f64;

    fn kind(&self) -> String;
}

#[derive(Debug, Clone)]
struct Widget {
    x: f64,
    y: f64,
}

impl WidgetDyn for Widget {
    fn widget(&self) -> &Widget {
        self
    }

    fn widget_mut(&mut self) -> &mut Widget {
        self
    }

    fn width(&self) -> f64 {
        widget_width(self)
    }

    fn kind(&self) -> String {
        widget_kind(self)
    }
}

fn widget_width(_this: &dyn WidgetDyn) -> f64 {
    1.0
}

fn widget_kind(_this: &dyn WidgetDyn) -> String {
    "widget".to_string()
}

fn widget_render(this: &dyn WidgetDyn) -> String {
    format!(
        "{} at ({:.1}, {:.1}) width {:.1}",
        this.kind(),
        this.widget().x,
        this.widget().y,
        this.width()
    )
}

fn widget_move_to(this: &mut dyn WidgetDyn, nx: f64, ny: f64) {
    this.widget_mut().x = nx;
    this.widget_mut().y = ny;
}

trait ButtonDyn: WidgetDyn {
    fn button(&self) -> &Button;
}

#[derive(Debug, Clone)]
struct Button {
    base: Widget,
    caption: String,
}

impl ButtonDyn for Button {
    fn button(&self) -> &Button {
        self
    }
}

impl WidgetDyn for Button {
    fn widget(&self) -> &Widget {
        &self.base
    }

    fn widget_mut(&mut self) -> &mut Widget {
        &mut self.base
    }

    fn width(&self) -> f64 {
        button_width(self)
    }

    fn kind(&self) -> String {
        button_kind(self)
    }
}

fn button_width(this: &dyn ButtonDyn) -> f64 {
    widget_width(this) + this.button().caption.chars().count() as i64 as f64
}

fn button_kind(this: &dyn ButtonDyn) -> String {
    format!("button '{}'", this.button().caption)
}

fn main() {
    {
        let items: Vec<Box<dyn Shape>> = vec![
            Box::new(Circle { r: 2.0 }),
            Box::new(Rect { w: 3.0, h: 4.0 }),
        ];
        for s in &items {
            println!("{}", s.describe());
        }
        println!("total area = {:.2}", total_area(&items));
    }
    let mut ui: Vec<Box<dyn WidgetDyn>> = vec![
        Box::new(Widget { x: 0.0, y: 0.0 }),
        Box::new(Button {
            base: Widget { x: 0.0, y: 0.0 },
            caption: "OK".to_string(),
        }),
    ];
    for i in 0..ui.len() as i64 {
        widget_move_to(ui[i as usize].as_mut(), (10 * i) as f64, 5.0);
    }
    for w in &ui {
        println!("{}", widget_render(w.as_ref()));
    }
}
