// Code generated by polyglot-generator. DO NOT EDIT.
// Source: project.lisp (git blob f2715e5101)
//! Module shapes.

/// Something with an area.
pub trait Shape {
    fn area(&self) -> f64;

    fn label(&self) -> String;

    fn describe(&self) -> String {
        format!("{} with area {:.2}", self.label(), self.area())
    }
}

#[derive(Debug, Clone)]
pub struct Circle {
    pub r: f64,
}

impl Shape for Circle {
    fn area(&self) -> f64 {
        3.0 * self.r * self.r
    }

    fn label(&self) -> String {
        "circle".to_string()
    }
}

#[derive(Debug, Clone)]
pub struct Rect {
    pub w: f64,
    pub h: f64,
}

impl Shape for Rect {
    fn area(&self) -> f64 {
        self.w * self.h
    }

    fn label(&self) -> String {
        "rect".to_string()
    }
}

/// Sum of the areas of all shapes.
pub fn total_area(items: &[Box<dyn Shape>]) -> f64 {
    let mut sum = 0.0;
    for s in items {
        sum += s.area();
    }
    sum
}
