;;;; 24-items.lisp --- parser: items (defun, defstruct, defclass, ...)

(in-package :polyglot)

(defun item-head (form)
  (and (consp form) (form-name (car form))))

(defun require-name (form)
  (let ((name (second form)))
    (unless (and name (symbolp name) (not (keywordp name)))
      (dsl-error form "~a needs a name" (item-head form)))
    (spelling name)))

(defun parse-defun (form)
  (check-arg-count form 2 nil)
  (let* ((name (require-name form))
         (params (parse-lambda-list form (third form))))
    (multiple-value-bind (info body doc) (split-declares (cdddr form))
      (check-declare-kinds form info '(:types :values :modes :borrows-from :outlives :flags))
      (check-declared-names form info params)
      (when (intersection (decl-info-flags info) '(:virtual :override :abstract))
        (dsl-error form "virtual/override/abstract only apply to methods"))
      (make-function-item :name name :doc doc
                          :params (make-params form params info :require-types t)
                          :ret (if (decl-info-ret-p info) (decl-info-ret info) :void)
                          :body (parse-stmts body)
                          :flags (decl-info-flags info)
                          :borrows-from (decl-info-borrows-from info)
                          :outlives (decl-info-outlives info)
                          :source form))))

(defun parse-receiver (form spec owner)
  "Receiver spec: name | (name) | (name :mode) | (name type) | (name type :mode).
Returns (values var-def owner-spelling)."
  (let* ((parts (alexandria:ensure-list spec))
         (name (first parts))
         (rest (rest parts))
         (ty (when (and rest (symbolp (first rest)) (not (keywordp (first rest))))
               (spelling (pop rest))))
         (mode (or (pop rest) :in)))
    (unless (and name (symbolp name) (not (keywordp name)) (null rest))
      (dsl-error form "malformed method receiver ~s" spec))
    (unless (member mode '(:in :inout :sink))
      (dsl-error form "receiver mode must be :in, :inout or :sink"))
    (when (and ty owner (string/= ty owner))
      (dsl-error form "receiver type ~a does not match enclosing type ~a" ty owner))
    (let ((owner (or ty owner)))
      (unless owner
        (dsl-error form "defmethod outside a type needs a receiver type: ((x type :in) ...)"))
      (values (make-var-def :name (spelling name) :kind :receiver :receiver-p t :mode mode
                            :declared-ty (list :named owner) :source spec)
              owner))))

(defun parse-method (form owner &key interface-p)
  (check-arg-count form 2 nil)
  (let ((name (require-name form))
        (ll (third form)))
    (unless (and (consp ll) (car ll))
      (dsl-error form "method needs a receiver as first parameter"))
    (multiple-value-bind (receiver owner) (parse-receiver form (car ll) owner)
      (let ((params (parse-lambda-list form (cdr ll))))
        (multiple-value-bind (info body doc) (split-declares (cdddr form))
          (check-declare-kinds form info '(:types :values :modes :borrows-from :outlives :flags))
          (check-declared-names form info params)
          (let ((flags (decl-info-flags info)))
            (when (and interface-p (null body))
              (pushnew :abstract flags))
            (when (and (member :abstract flags) body)
              (dsl-error form "abstract method ~a must not have a body" name))
            (make-method-item :name name :doc doc :owner owner
                              :params (cons receiver (make-params form params info :require-types t))
                              :ret (if (decl-info-ret-p info) (decl-info-ret info) :void)
                              :ret-declared (decl-info-ret-p info)
                              :body (parse-stmts body) :flags flags
                              :borrows-from (decl-info-borrows-from info)
                              :outlives (decl-info-outlives info)
                              :source form)))))))

(defun parse-field (form spec owner)
  (unless (and (consp spec) (symbolp (car spec)) (<= 2 (length spec) 3))
    (dsl-error form "malformed field ~s, expected (name type [default])" spec))
  (make-field-def :name (spelling (first spec)) :ty (parse-type (second spec))
                  :default (when (cddr spec) (parse-expr (third spec)))
                  :owner owner :source spec))

(defun parse-type-body (form name elements)
  "Fields, methods and options of defstruct/defclass. Returns
(values fields methods implements doc)."
  (let ((fields '()) (methods '()) (implements '()) (doc nil))
    (dolist (e elements)
      (cond ((stringp e) (setf doc e))
            ((and (consp e) (eq (car e) :implements))
             (setf implements (append implements (mapcar #'spelling (cdr e)))))
            ((and (consp e) (keywordp (car e)))
             (dsl-error form "unknown option ~s" (car e)))
            ((and (consp e) (form-is (car e) "defmethod"))
             (push (parse-method e name) methods))
            (t (push (parse-field form e name) fields))))
    (values (nreverse fields) (nreverse methods) implements doc)))

(defun parse-defstruct (form)
  (let ((name (require-name form)))
    (multiple-value-bind (fields methods implements doc) (parse-type-body form name (cddr form))
      (make-struct-item :name name :fields fields :methods methods :implements implements
                        :doc doc :source form))))

(defun parse-defclass (form)
  (let ((name (require-name form))
        (bases (third form)))
    (unless (listp bases)
      (dsl-error form "defclass needs a list of base classes"))
    (when (cdr bases)
      (error 'unsupported-construct :form form
             :message "multiple inheritance is only available target specific"))
    (multiple-value-bind (fields methods implements doc) (parse-type-body form name (cdddr form))
      (make-struct-item :name name :fields fields :methods methods :implements implements
                        :class-p t :base (when bases (spelling (car bases)))
                        :doc doc :source form))))

(defun parse-definterface (form)
  (let ((name (require-name form)) (extends '()) (methods '()) (doc nil))
    (dolist (e (cddr form))
      (cond ((stringp e) (setf doc e))
            ((and (consp e) (eq (car e) :extends)) (setf extends (mapcar #'spelling (cdr e))))
            ((and (consp e) (form-is (car e) "defmethod"))
             (push (parse-method e name :interface-p t) methods))
            (t (dsl-error form "unexpected element ~s in definterface" e))))
    (make-interface-item :name name :extends extends :methods (nreverse methods)
                         :doc doc :source form)))

(defun parse-defconst (form)
  (check-arg-count form 3)
  (make-const-item :name (require-name form) :ty (parse-type (third form))
                   :value (parse-expr (fourth form)) :source form))
