;;;; p05_modes --- parameter modes :in/:inout/:sink, optional + if-let,
;;;; mutability inference (K1)

(in-package :polyglot-user)
(in-dsl)

(defmodule modes (:entry t)
           (defstruct point (x :i64 0) (y :i64 0)
                      (defmethod shift ((p :inout) dx dy)
                        (declare (type :i64 dx dy))
                        (incf (dot p x) dx)
                        (incf (dot p y) dy))
                      (defmethod manhattan ((p :in))
                        (declare (values :i64))
                        (+ (abs (dot p x)) (abs (dot p y)))))

           (defstruct polygon (name :string "") (points (vec point) nil))

           (defun add-point (poly p)
             (declare (type polygon poly) (mode :inout poly) (type point p) (mode :sink p))
             (push (move p) (dot poly points)))

           (defun find-first-far (poly limit)
             (declare (type polygon poly) (type :i64 limit) (values (optional point)))
             (dolist (p (dot poly points))
               (when (> (manhattan p) limit)
                 (return (some (clone p)))))
             nil)

           (defun total (poly)
             (declare (type polygon poly) (values :i64))
             (let ((sum 0))
               (dolist (p (dot poly points))
                 (incf sum (manhattan p)))
               sum))

           (defun describe-point (p)
             (declare (type point p) (values :string))
             (format-string "({}, {})" (dot p x) (dot p y)))

           (defun main ()
             (let ((poly (make-polygon :name "tri"))
                   (a (make-point :x 1 :y 2)))
               (shift a 10 -1)
               (print-line (format-string "a = {}" (describe-point a)))
               (add-point poly (move a))
               (add-point poly (make-point :x -3 :y 4))
               (add-point poly (make-point))
               (print-line (format-string "{} has {} points" (dot poly name) (length (dot poly points))))
               (print-line (format-string "total = {}" (total poly)))
               (if-let (far (find-first-far poly 6))
                   (print-line (format-string "far: {}" (describe-point far)))
                 (print-line "far: none"))
               (if-let (far (find-first-far poly 100))
                   (print-line (format-string "far: {}" (describe-point far)))
                 (print-line "far: none"))
               (let ((b (make-point :x 5 :y -5)))
                 (print-line (format-string "b = {} |b| = {}" (describe-point b) (manhattan b)))))))

(defproject modes (:modules modes) (:entry modes))
