;;;; items.lisp --- Python backend: functions, dataclasses, ABCs, constants

(in-package :polyglot)

(defun py-param (p)
  (format nil "~a: ~a" (ir-target-name p) (py-type (ir-ty p))))

(defun py-signature (fn &key method)
  (let ((params (if method (rest (ir-params fn)) (ir-params fn))))
    (format nil "def ~a(~{~a~^, ~}) -> ~a:" (ir-target-name fn)
            (append (when method (list (ir-target-name (first (ir-params fn)))))
                    (mapcar #'py-param params))
            (py-type (ir-ret fn)))))

(defun py-docstring (item)
  (when (ir-doc item)
    (with-indent () (emit-line "\"\"\"~a\"\"\"" (escape-string (ir-doc item) :python)))))

(defun py-function (fn &key method)
  (emit-line (py-signature fn :method method))
  (py-docstring fn)
  (if (and (null (ir-body fn)) (ir-doc fn))
      nil
      (py-body (ir-body fn))))

(defun py-abstract-method (m)
  (note-import (list :from "abc" "abstractmethod"))
  (emit-line "@abstractmethod")
  (emit-line (py-signature m :method t))
  (with-indent () (emit-line "...")))

(defun py-methods (item)
  (dolist (m (ir-methods item))
    (emit-blank-line)
    (if (function-flag-p m :abstract)
        (py-abstract-method m)
        (py-function m :method t))))

(defun py-field-default (f)
  (let ((d (ir-default f)) (ty (ir-ty f)))
    (cond ((and d (not (typep d '(or vec-expr map-expr make-expr))) (not (member (type-head ty) '(:vec :map))))
           (ex-str d))
          ((or d (member (type-head ty) '(:vec :map :named)))
           (note-import (list :from "dataclasses" "field"))
           (format nil "field(default_factory=~a)"
                   (cond ((typep d 'make-expr) (format nil "lambda: ~a" (ex-str d)))
                         ((and d (not (and (typep d 'lit-expr) (eq :nil (ir-kind d)))))
                          (format nil "lambda: ~a" (ex-str d)))
                         ((eq :vec (type-head ty)) "list")
                         ((eq :map (type-head ty)) "dict")
                         (t (py-ref (type-item ty))))))
          (t (py-zero-value ty)))))

(defun py-zero-value (ty)
  (cond ((int-type-p ty) "0")
        ((float-type-p ty) "0.0")
        ((eq ty :bool) "False")
        ((member ty '(:string :char)) "\"\"")
        (t "None")))

(defun py-class-bases (item)
  (let ((bases (append (when (ir-base-item item) (list (py-ref (ir-base-item item))))
                       (mapcar #'py-ref (ir-implements-items item)))))
    (if bases (format nil "(~{~a~^, ~})" bases) "")))

(defun py-struct (item)
  (note-import (list :from "dataclasses" "dataclass"))
  (emit-line "@dataclass")
  (emit-line "class ~a~a:" (ir-target-name item) (py-class-bases item))
  (with-indent ()
    (when (ir-doc item) (emit-line "\"\"\"~a\"\"\"" (escape-string (ir-doc item) :python)))
    (dolist (f (ir-fields item))
      (emit-line "~a: ~a = ~a" (ir-target-name f) (py-type (ir-ty f)) (py-field-default f)))
    (when (and (null (ir-fields item)) (null (ir-methods item)) (null (ir-doc item)))
      (emit-line "pass"))
    (py-methods item)))

(defun py-interface (item)
  (note-import (list :from "abc" "ABC"))
  (emit-line "class ~a(~{~a~^, ~}):" (ir-target-name item)
             (or (mapcar #'py-ref (ir-extends-items item)) (list "ABC")))
  (with-indent ()
    (when (ir-doc item) (emit-line "\"\"\"~a\"\"\"" (escape-string (ir-doc item) :python)))
    (if (ir-methods item)
        (py-methods item)
        (emit-line "pass"))))

(defmethod emit-item ((b python-backend) item)
  (etypecase item
    (function-item (py-function item))
    (struct-item (py-struct item))
    (interface-item (py-interface item))
    (const-item (emit-line "~a: ~a = ~a" (ir-target-name item) (py-type (ir-ty item))
                           (ex-str (ir-value item))))
    (extern-item nil)))
