;;;; p03_control --- cond, while with break/continue, dotimes, dolist,
;;;; shadowing in nested let (E3), if/let as value (E9), empty blocks (E2)

(in-package :polyglot-user)
(in-dsl)

(defmodule control (:entry t)
           (defun classify (n)
             (declare (type :i64 n) (values :string))
             (cond ((< n 0) "negative")
                   ((= n 0) "zero")
                   ((< n 10) "small")
                   (t "large")))

           (defun main ()
             (dolist (n (vec-of :i64 -5 0 7 42))
               (print-line (format-string "{} is {}" n (classify n))))
             (let ((i 0) (total 0))
               (while (< i 10)
                 (incf i)
                 (when (= (mod i 2) 0)
                   (continue))
                 (when (> i 7)
                   (break))
                 (incf total i))
               (print-line (format-string "odd sum below 8 = {}" total)))
             (dotimes (k 3)
               (print-line (format-string "k = {}" k)))
             (let ((x 1))
               (let ((x (+ x 10)))
                 (let ((x (* x 2)))
                   (print-line (format-string "inner x = {}" x)))
                 (print-line (format-string "middle x = {}" x)))
               (print-line (format-string "outer x = {}" x)))
             (let* ((v 5)
                    (label (if (> v 3) "big" "small")))
               (print-line (format-string "label = {}" label)))
             (let* ((w 4)
                    (size (if (> w 3) (let ((d (* w 2))) (+ d 1)) 0)))
               (print-line (format-string "size = {}" size)))
             (dotimes (j 2)
               (comment "intentionally empty loop body (E2)"))
             (print-line "done")))

(defproject control (:modules control) (:entry control))
