;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 18:26:51
;; Git:       6d7c236b32faa713eed921c78ef8bd2269e05b55
(in-package :hpipm)

;; --- Foreign library loading ---
(cffi:define-foreign-library libhpipm
  (:unix "libhpipm.so")
  (t (:default "libhpipm")))

(cffi:use-foreign-library libhpipm)

;; --- Constants ---
(defconstant +hpipm-struct-size+
  4096
  "Upper bound for HPIPM struct allocation (bytes). Use cffi-grovel for exact size.")

(defconstant +hpipm-mode-speed+ 0)

(defconstant +hpipm-mode-balance+ 1)

(defconstant +hpipm-mode-robust+ 2)

;; --- Double-precision (d) lifecycle functions ---
(cffi:defcfun ("d_ocp_qp_dim_memsize" d-ocp-qp-dim-memsize)
    :int
  (n :int))

(cffi:defcfun ("d_ocp_qp_dim_create" d-ocp-qp-dim-create)
    :void
  (n :int)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("d_ocp_qp_memsize" d-ocp-qp-memsize)
    :int
  (dim :pointer))

(cffi:defcfun ("d_ocp_qp_create" d-ocp-qp-create)
    :void
  (dim :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("d_ocp_qp_sol_memsize" d-ocp-qp-sol-memsize)
    :int
  (dim :pointer))

(cffi:defcfun ("d_ocp_qp_sol_create" d-ocp-qp-sol-create)
    :void
  (dim :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("d_ocp_qp_ipm_arg_memsize" d-ocp-qp-ipm-arg-memsize)
    :int
  (dim :pointer))

(cffi:defcfun ("d_ocp_qp_ipm_arg_create" d-ocp-qp-ipm-arg-create)
    :void
  (dim :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("d_ocp_qp_ipm_ws_memsize" d-ocp-qp-ipm-ws-memsize)
    :int
  (dim :pointer)
  (arg :pointer))

(cffi:defcfun ("d_ocp_qp_ipm_ws_create" d-ocp-qp-ipm-ws-create)
    :void
  (dim :pointer)
  (arg :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("d_ocp_qp_dim_set" d-ocp-qp-dim-set)
    :void
  (field :string)
  (stage :int)
  (value :int)
  (dim :pointer))

(cffi:defcfun ("d_ocp_qp_set" d-ocp-qp-set)
    :void
  (field :string)
  (stage :int)
  (value :pointer)
  (qp :pointer))

(cffi:defcfun ("d_ocp_qp_sol_get" d-ocp-qp-sol-get)
    :void
  (field :string)
  (stage :int)
  (sol :pointer)
  (value :pointer))

(cffi:defcfun ("d_ocp_qp_ipm_arg_set_default" d-ocp-qp-ipm-arg-set-default)
    :void
  (mode :int)
  (arg :pointer))

(cffi:defcfun ("d_ocp_qp_ipm_solve" d-ocp-qp-ipm-solve)
    :void
  (qp :pointer)
  (qp-sol :pointer)
  (arg :pointer)
  (ws :pointer))

;; --- Single-precision (s) lifecycle functions ---
(cffi:defcfun ("s_ocp_qp_dim_memsize" s-ocp-qp-dim-memsize)
    :int
  (n :int))

(cffi:defcfun ("s_ocp_qp_dim_create" s-ocp-qp-dim-create)
    :void
  (n :int)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("s_ocp_qp_memsize" s-ocp-qp-memsize)
    :int
  (dim :pointer))

(cffi:defcfun ("s_ocp_qp_create" s-ocp-qp-create)
    :void
  (dim :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("s_ocp_qp_sol_memsize" s-ocp-qp-sol-memsize)
    :int
  (dim :pointer))

(cffi:defcfun ("s_ocp_qp_sol_create" s-ocp-qp-sol-create)
    :void
  (dim :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("s_ocp_qp_ipm_arg_memsize" s-ocp-qp-ipm-arg-memsize)
    :int
  (dim :pointer))

(cffi:defcfun ("s_ocp_qp_ipm_arg_create" s-ocp-qp-ipm-arg-create)
    :void
  (dim :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("s_ocp_qp_ipm_ws_memsize" s-ocp-qp-ipm-ws-memsize)
    :int
  (dim :pointer)
  (arg :pointer))

(cffi:defcfun ("s_ocp_qp_ipm_ws_create" s-ocp-qp-ipm-ws-create)
    :void
  (dim :pointer)
  (arg :pointer)
  (struct-ptr :pointer)
  (mem :pointer))

(cffi:defcfun ("s_ocp_qp_dim_set" s-ocp-qp-dim-set)
    :void
  (field :string)
  (stage :int)
  (value :int)
  (dim :pointer))

(cffi:defcfun ("s_ocp_qp_set" s-ocp-qp-set)
    :void
  (field :string)
  (stage :int)
  (value :pointer)
  (qp :pointer))

(cffi:defcfun ("s_ocp_qp_sol_get" s-ocp-qp-sol-get)
    :void
  (field :string)
  (stage :int)
  (sol :pointer)
  (value :pointer))

(cffi:defcfun ("s_ocp_qp_ipm_arg_set_default" s-ocp-qp-ipm-arg-set-default)
    :void
  (mode :int)
  (arg :pointer))

(cffi:defcfun ("s_ocp_qp_ipm_solve" s-ocp-qp-ipm-solve)
    :void
  (qp :pointer)
  (qp-sol :pointer)
  (arg :pointer)
  (ws :pointer))