;;;; hpipm.asd — Auto-generated by cl-cl-generator
;;;; Generated: 2026-07-03 18:46:10

(defsystem :hpipm
  :description "CFFI bindings for the HPIPM OCP QP solver"
  :depends-on (:cffi)
  :serial t
  :components ((:file "package")
               (:file "hpipm-cffi")
               (:file "hpipm-wrappers")
               (:file "mpc-demo")
               (:file "pendulum-demo")))
