;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 18:46:10
;; Git:       125a9f9ff0688d9ac58aa3b30a61d9bc681094ba
(in-package :hpipm)

(defun align-pointer (ptr alignment)
  "Align pointer PTR to ALIGNMENT boundary."
  (let* ((addr (cffi-sys:pointer-address ptr))
         (aligned-addr (* (ceiling addr alignment) alignment)))
    (cffi-sys:make-pointer aligned-addr)))

;; --- Double-precision call-with-* allocation helpers ---
(defun call-with-d-ocp-qp-dim (n fn)
  "Allocate Double-precision ocp_qp_dim, call FN with struct pointer, then free."
  (let* ((mem-size (d-ocp-qp-dim-memsize n))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (d-ocp-qp-dim-create n aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-d-ocp-qp (dim fn)
  "Allocate Double-precision ocp_qp, call FN with struct pointer, then free."
  (let* ((mem-size (d-ocp-qp-memsize dim))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (d-ocp-qp-create dim aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-d-ocp-qp-sol (dim fn)
  "Allocate Double-precision ocp_qp_sol, call FN with struct pointer, then free."
  (let* ((mem-size (d-ocp-qp-sol-memsize dim))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (d-ocp-qp-sol-create dim aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-d-ocp-qp-ipm-arg (dim fn)
  "Allocate Double-precision ocp_qp_ipm_arg, call FN with struct pointer, then free."
  (let* ((mem-size (d-ocp-qp-ipm-arg-memsize dim))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (d-ocp-qp-ipm-arg-create dim aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-d-ocp-qp-ipm-ws (dim arg fn)
  "Allocate Double-precision ocp_qp_ipm_ws, call FN with struct pointer, then free."
  (let* ((mem-size (d-ocp-qp-ipm-ws-memsize dim arg))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (d-ocp-qp-ipm-ws-create dim arg aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

;; --- Double-precision with-* convenience macros ---
(defmacro with-d-ocp-qp-dim ((var n) &body body)
  "Allocate HPIPM ocp_qp_dim, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-d-ocp-qp-dim ,n #',fn-sym))))

(defmacro with-d-ocp-qp ((var dim) &body body)
  "Allocate HPIPM ocp_qp, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-d-ocp-qp ,dim #',fn-sym))))

(defmacro with-d-ocp-qp-sol ((var dim) &body body)
  "Allocate HPIPM ocp_qp_sol, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-d-ocp-qp-sol ,dim #',fn-sym))))

(defmacro with-d-ocp-qp-ipm-arg ((var dim) &body body)
  "Allocate HPIPM ocp_qp_ipm_arg, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-d-ocp-qp-ipm-arg ,dim #',fn-sym))))

(defmacro with-d-ocp-qp-ipm-ws ((var dim arg) &body body)
  "Allocate HPIPM ocp_qp_ipm_ws, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-d-ocp-qp-ipm-ws ,dim ,arg #',fn-sym))))

;; --- Double-precision dimension setter wrappers ---
(defun d-ocp-qp-dim-set-nx (stage value dim)
  "Number of states per stage"
  (d-ocp-qp-dim-set "nx" stage value dim))

(defun d-ocp-qp-dim-set-nu (stage value dim)
  "Number of inputs per stage"
  (d-ocp-qp-dim-set "nu" stage value dim))

(defun d-ocp-qp-dim-set-nbx (stage value dim)
  "Number of state box constraints per stage"
  (d-ocp-qp-dim-set "nbx" stage value dim))

(defun d-ocp-qp-dim-set-nbu (stage value dim)
  "Number of input box constraints per stage"
  (d-ocp-qp-dim-set "nbu" stage value dim))

(defun d-ocp-qp-dim-set-ng (stage value dim)
  "Number of general constraints per stage"
  (d-ocp-qp-dim-set "ng" stage value dim))

(defun d-ocp-qp-dim-set-ns (stage value dim)
  "Number of soft constraint slacks per stage"
  (d-ocp-qp-dim-set "ns" stage value dim))

(defun d-ocp-qp-dim-set-nbxe (stage value dim)
  "Number of state box equality constraints"
  (d-ocp-qp-dim-set "nbxe" stage value dim))

(defun d-ocp-qp-dim-set-nbue (stage value dim)
  "Number of input box equality constraints"
  (d-ocp-qp-dim-set "nbue" stage value dim))

(defun d-ocp-qp-dim-set-nge (stage value dim)
  "Number of general equality constraints"
  (d-ocp-qp-dim-set "nge" stage value dim))

;; --- Double-precision QP data setter wrappers ---
(defun d-ocp-qp-set-a (stage value qp)
  "Dynamics matrix A_k (state to state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :double :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :double (+ (* j rows) i))
                                  (coerce (aref value i j) 'double-float))))
                      (d-ocp-qp-set "A" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-b (stage value qp)
  "Dynamics matrix B_k (input to state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :double :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :double (+ (* j rows) i))
                                  (coerce (aref value i j) 'double-float))))
                      (d-ocp-qp-set "B" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-q (stage value qp)
  "Cost Hessian Q_k (state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :double :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :double (+ (* j rows) i))
                                  (coerce (aref value i j) 'double-float))))
                      (d-ocp-qp-set "Q" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-r (stage value qp)
  "Cost Hessian R_k (input)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :double :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :double (+ (* j rows) i))
                                  (coerce (aref value i j) 'double-float))))
                      (d-ocp-qp-set "R" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-s (stage value qp)
  "Cost cross-term S_k (state x input)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :double :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :double (+ (* j rows) i))
                                  (coerce (aref value i j) 'double-float))))
                      (d-ocp-qp-set "S" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-c (stage value qp)
  "General constraint matrix C_k (state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :double :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :double (+ (* j rows) i))
                                  (coerce (aref value i j) 'double-float))))
                      (d-ocp-qp-set "C" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-d (stage value qp)
  "General constraint matrix D_k (input)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :double :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :double (+ (* j rows) i))
                                  (coerce (aref value i j) 'double-float))))
                      (d-ocp-qp-set "D" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-b-vec (stage value qp)
  "Dynamics offset vector b_k"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "b" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-q-vec (stage value qp)
  "Cost gradient q_k (state)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "q" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-r-vec (stage value qp)
  "Cost gradient r_k (input)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "r" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lbu (stage value qp)
  "Lower bound on inputs"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-ubu (stage value qp)
  "Upper bound on inputs"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "ubu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lbx (stage value qp)
  "Lower bound on states"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-ubx (stage value qp)
  "Upper bound on states"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "ubx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lbu-mask (stage value qp)
  "Mask for lower input box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lbu_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-ubu-mask (stage value qp)
  "Mask for upper input box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "ubu_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lbx-mask (stage value qp)
  "Mask for lower state box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lbx_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-ubx-mask (stage value qp)
  "Mask for upper state box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "ubx_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lg (stage value qp)
  "Lower bound on general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lg" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-ug (stage value qp)
  "Upper bound on general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "ug" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lg-mask (stage value qp)
  "Mask for lower general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lg_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-ug-mask (stage value qp)
  "Mask for upper general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "ug_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-zl (stage value qp)
  "Soft constraint Hessian (lower)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "Zl" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-zu (stage value qp)
  "Soft constraint Hessian (upper)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "Zu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-zl (stage value qp)
  "Soft constraint gradient (lower)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "zl" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-zu (stage value qp)
  "Soft constraint gradient (upper)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "zu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lls (stage value qp)
  "Lower bound on lower slack"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lls" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lus (stage value qp)
  "Lower bound on upper slack"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lus" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lls-mask (stage value qp)
  "Mask for lower slack bound"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lls_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-lus-mask (stage value qp)
  "Mask for upper slack bound"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :double i)
                                (coerce (elt value i) 'double-float)))
                      (d-ocp-qp-set "lus_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxb (stage value qp)
  "Indices of box-constrained variables"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxb" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxbx (stage value qp)
  "Indices of box-constrained states"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxbu (stage value qp)
  "Indices of box-constrained inputs"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxs (stage value qp)
  "Indices of soft-constrained variables"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxs" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxs-rev (stage value qp)
  "Reverse mapping of soft constraint indices"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxs_rev" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxe (stage value qp)
  "Indices of equality constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxe" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxbue (stage value qp)
  "Indices of input box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxbue" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxbxe (stage value qp)
  "Indices of state box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxbxe" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-idxge (stage value qp)
  "Indices of general equality constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "idxge" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jbx (stage value qp)
  "Selection matrix for state box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jbu (stage value qp)
  "Selection matrix for input box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jsbu (stage value qp)
  "Selection matrix for input soft constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jsbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jsbx (stage value qp)
  "Selection matrix for state soft constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jsbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jsg (stage value qp)
  "Selection matrix for general soft constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jsg" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jbue (stage value qp)
  "Selection matrix for input box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jbue" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jbxe (stage value qp)
  "Selection matrix for state box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jbxe" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-jge (stage value qp)
  "Selection matrix for general equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (d-ocp-qp-set "Jge" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-set-diag-h-flag (stage value qp)
  "Flag indicating diagonal Hessian"
  (cffi:with-foreign-object (ptr :int)
    (setf (cffi:mem-ref ptr :int) value)
    (d-ocp-qp-set "diag_H_flag" stage ptr qp)))

;; --- Double-precision solution getter wrappers ---
(defun d-ocp-qp-sol-get-u (stage n sol)
  "Optimal inputs N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "u" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-x (stage n sol)
  "Optimal states N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "x" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-sl (stage n sol)
  "Lower slack variables N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "sl" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-su (stage n sol)
  "Upper slack variables N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "su" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-pi (stage n sol)
  "Dual variables (dynamics equality) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "pi" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-lb (stage n sol)
  "Lagrange multipliers (box lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_lb" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-ub (stage n sol)
  "Lagrange multipliers (box upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_ub" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-lbu (stage n sol)
  "Lagrange multipliers (input lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_lbu" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-ubu (stage n sol)
  "Lagrange multipliers (input upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_ubu" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-lbx (stage n sol)
  "Lagrange multipliers (state lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_lbx" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-ubx (stage n sol)
  "Lagrange multipliers (state upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_ubx" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-lg (stage n sol)
  "Lagrange multipliers (general lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_lg" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun d-ocp-qp-sol-get-lam-ug (stage n sol)
  "Lagrange multipliers (general upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :double :count n)))
    (unwind-protect (progn
                      (d-ocp-qp-sol-get "lam_ug" stage sol ptr)
                      (let ((result (make-array n :element-type 'double-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :double i)))
                        result))
      (cffi-sys:foreign-free ptr))))

;; --- Single-precision call-with-* allocation helpers ---
(defun call-with-s-ocp-qp-dim (n fn)
  "Allocate Single-precision ocp_qp_dim, call FN with struct pointer, then free."
  (let* ((mem-size (s-ocp-qp-dim-memsize n))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (s-ocp-qp-dim-create n aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-s-ocp-qp (dim fn)
  "Allocate Single-precision ocp_qp, call FN with struct pointer, then free."
  (let* ((mem-size (s-ocp-qp-memsize dim))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (s-ocp-qp-create dim aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-s-ocp-qp-sol (dim fn)
  "Allocate Single-precision ocp_qp_sol, call FN with struct pointer, then free."
  (let* ((mem-size (s-ocp-qp-sol-memsize dim))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (s-ocp-qp-sol-create dim aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-s-ocp-qp-ipm-arg (dim fn)
  "Allocate Single-precision ocp_qp_ipm_arg, call FN with struct pointer, then free."
  (let* ((mem-size (s-ocp-qp-ipm-arg-memsize dim))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (s-ocp-qp-ipm-arg-create dim aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

(defun call-with-s-ocp-qp-ipm-ws (dim arg fn)
  "Allocate Single-precision ocp_qp_ipm_ws, call FN with struct pointer, then free."
  (let* ((mem-size (s-ocp-qp-ipm-ws-memsize dim arg))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (s-ocp-qp-ipm-ws-create dim arg aligned-ptr aligned-backing)
    (unwind-protect (funcall fn aligned-ptr)
      (cffi-sys:foreign-free ptr)
      (cffi-sys:foreign-free backing))))

;; --- Single-precision with-* convenience macros ---
(defmacro with-s-ocp-qp-dim ((var n) &body body)
  "Allocate HPIPM ocp_qp_dim, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-s-ocp-qp-dim ,n #',fn-sym))))

(defmacro with-s-ocp-qp ((var dim) &body body)
  "Allocate HPIPM ocp_qp, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-s-ocp-qp ,dim #',fn-sym))))

(defmacro with-s-ocp-qp-sol ((var dim) &body body)
  "Allocate HPIPM ocp_qp_sol, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-s-ocp-qp-sol ,dim #',fn-sym))))

(defmacro with-s-ocp-qp-ipm-arg ((var dim) &body body)
  "Allocate HPIPM ocp_qp_ipm_arg, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-s-ocp-qp-ipm-arg ,dim #',fn-sym))))

(defmacro with-s-ocp-qp-ipm-ws ((var dim arg) &body body)
  "Allocate HPIPM ocp_qp_ipm_ws, bind to VAR, execute BODY, then free."
  (let ((fn-sym (gensym "FN-")))
    `(flet ((,fn-sym (,var) ,@body))
       (call-with-s-ocp-qp-ipm-ws ,dim ,arg #',fn-sym))))

;; --- Single-precision dimension setter wrappers ---
(defun s-ocp-qp-dim-set-nx (stage value dim)
  "Number of states per stage"
  (s-ocp-qp-dim-set "nx" stage value dim))

(defun s-ocp-qp-dim-set-nu (stage value dim)
  "Number of inputs per stage"
  (s-ocp-qp-dim-set "nu" stage value dim))

(defun s-ocp-qp-dim-set-nbx (stage value dim)
  "Number of state box constraints per stage"
  (s-ocp-qp-dim-set "nbx" stage value dim))

(defun s-ocp-qp-dim-set-nbu (stage value dim)
  "Number of input box constraints per stage"
  (s-ocp-qp-dim-set "nbu" stage value dim))

(defun s-ocp-qp-dim-set-ng (stage value dim)
  "Number of general constraints per stage"
  (s-ocp-qp-dim-set "ng" stage value dim))

(defun s-ocp-qp-dim-set-ns (stage value dim)
  "Number of soft constraint slacks per stage"
  (s-ocp-qp-dim-set "ns" stage value dim))

(defun s-ocp-qp-dim-set-nbxe (stage value dim)
  "Number of state box equality constraints"
  (s-ocp-qp-dim-set "nbxe" stage value dim))

(defun s-ocp-qp-dim-set-nbue (stage value dim)
  "Number of input box equality constraints"
  (s-ocp-qp-dim-set "nbue" stage value dim))

(defun s-ocp-qp-dim-set-nge (stage value dim)
  "Number of general equality constraints"
  (s-ocp-qp-dim-set "nge" stage value dim))

;; --- Single-precision QP data setter wrappers ---
(defun s-ocp-qp-set-a (stage value qp)
  "Dynamics matrix A_k (state to state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :float :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :float (+ (* j rows) i))
                                  (coerce (aref value i j) 'single-float))))
                      (s-ocp-qp-set "A" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-b (stage value qp)
  "Dynamics matrix B_k (input to state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :float :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :float (+ (* j rows) i))
                                  (coerce (aref value i j) 'single-float))))
                      (s-ocp-qp-set "B" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-q (stage value qp)
  "Cost Hessian Q_k (state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :float :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :float (+ (* j rows) i))
                                  (coerce (aref value i j) 'single-float))))
                      (s-ocp-qp-set "Q" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-r (stage value qp)
  "Cost Hessian R_k (input)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :float :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :float (+ (* j rows) i))
                                  (coerce (aref value i j) 'single-float))))
                      (s-ocp-qp-set "R" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-s (stage value qp)
  "Cost cross-term S_k (state x input)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :float :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :float (+ (* j rows) i))
                                  (coerce (aref value i j) 'single-float))))
                      (s-ocp-qp-set "S" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-c (stage value qp)
  "General constraint matrix C_k (state)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :float :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :float (+ (* j rows) i))
                                  (coerce (aref value i j) 'single-float))))
                      (s-ocp-qp-set "C" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-d (stage value qp)
  "General constraint matrix D_k (input)"
  (let* ((rows (array-dimension value 0)) (cols (array-dimension value 1))
         (ptr (cffi:foreign-alloc :float :count (* rows cols))))
    (unwind-protect (progn
                      (dotimes (j cols)
                        (dotimes (i rows)
                          (setf (cffi:mem-aref ptr :float (+ (* j rows) i))
                                  (coerce (aref value i j) 'single-float))))
                      (s-ocp-qp-set "D" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-b-vec (stage value qp)
  "Dynamics offset vector b_k"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "b" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-q-vec (stage value qp)
  "Cost gradient q_k (state)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "q" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-r-vec (stage value qp)
  "Cost gradient r_k (input)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "r" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lbu (stage value qp)
  "Lower bound on inputs"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-ubu (stage value qp)
  "Upper bound on inputs"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "ubu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lbx (stage value qp)
  "Lower bound on states"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-ubx (stage value qp)
  "Upper bound on states"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "ubx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lbu-mask (stage value qp)
  "Mask for lower input box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lbu_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-ubu-mask (stage value qp)
  "Mask for upper input box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "ubu_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lbx-mask (stage value qp)
  "Mask for lower state box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lbx_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-ubx-mask (stage value qp)
  "Mask for upper state box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "ubx_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lg (stage value qp)
  "Lower bound on general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lg" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-ug (stage value qp)
  "Upper bound on general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "ug" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lg-mask (stage value qp)
  "Mask for lower general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lg_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-ug-mask (stage value qp)
  "Mask for upper general constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "ug_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-zl (stage value qp)
  "Soft constraint Hessian (lower)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "Zl" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-zu (stage value qp)
  "Soft constraint Hessian (upper)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "Zu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-zl (stage value qp)
  "Soft constraint gradient (lower)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "zl" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-zu (stage value qp)
  "Soft constraint gradient (upper)"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "zu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lls (stage value qp)
  "Lower bound on lower slack"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lls" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lus (stage value qp)
  "Lower bound on upper slack"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lus" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lls-mask (stage value qp)
  "Mask for lower slack bound"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lls_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-lus-mask (stage value qp)
  "Mask for upper slack bound"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :float i)
                                (coerce (elt value i) 'single-float)))
                      (s-ocp-qp-set "lus_mask" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxb (stage value qp)
  "Indices of box-constrained variables"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxb" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxbx (stage value qp)
  "Indices of box-constrained states"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxbu (stage value qp)
  "Indices of box-constrained inputs"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxs (stage value qp)
  "Indices of soft-constrained variables"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxs" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxs-rev (stage value qp)
  "Reverse mapping of soft constraint indices"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxs_rev" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxe (stage value qp)
  "Indices of equality constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxe" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxbue (stage value qp)
  "Indices of input box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxbue" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxbxe (stage value qp)
  "Indices of state box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxbxe" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-idxge (stage value qp)
  "Indices of general equality constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "idxge" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jbx (stage value qp)
  "Selection matrix for state box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jbu (stage value qp)
  "Selection matrix for input box constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jsbu (stage value qp)
  "Selection matrix for input soft constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jsbu" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jsbx (stage value qp)
  "Selection matrix for state soft constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jsbx" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jsg (stage value qp)
  "Selection matrix for general soft constraints"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jsg" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jbue (stage value qp)
  "Selection matrix for input box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jbue" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jbxe (stage value qp)
  "Selection matrix for state box equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jbxe" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-jge (stage value qp)
  "Selection matrix for general equalities"
  (let* ((n (length value)) (ptr (cffi:foreign-alloc :int :count n)))
    (unwind-protect (progn
                      (dotimes (i n)
                        (setf (cffi:mem-aref ptr :int i) (elt value i)))
                      (s-ocp-qp-set "Jge" stage ptr qp))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-set-diag-h-flag (stage value qp)
  "Flag indicating diagonal Hessian"
  (cffi:with-foreign-object (ptr :int)
    (setf (cffi:mem-ref ptr :int) value)
    (s-ocp-qp-set "diag_H_flag" stage ptr qp)))

;; --- Single-precision solution getter wrappers ---
(defun s-ocp-qp-sol-get-u (stage n sol)
  "Optimal inputs N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "u" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-x (stage n sol)
  "Optimal states N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "x" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-sl (stage n sol)
  "Lower slack variables N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "sl" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-su (stage n sol)
  "Upper slack variables N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "su" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-pi (stage n sol)
  "Dual variables (dynamics equality) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "pi" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-lb (stage n sol)
  "Lagrange multipliers (box lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_lb" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-ub (stage n sol)
  "Lagrange multipliers (box upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_ub" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-lbu (stage n sol)
  "Lagrange multipliers (input lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_lbu" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-ubu (stage n sol)
  "Lagrange multipliers (input upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_ubu" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-lbx (stage n sol)
  "Lagrange multipliers (state lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_lbx" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-ubx (stage n sol)
  "Lagrange multipliers (state upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_ubx" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-lg (stage n sol)
  "Lagrange multipliers (general lower) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_lg" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))

(defun s-ocp-qp-sol-get-lam-ug (stage n sol)
  "Lagrange multipliers (general upper) N is the number of elements to retrieve."
  (let ((ptr (cffi:foreign-alloc :float :count n)))
    (unwind-protect (progn
                      (s-ocp-qp-sol-get "lam_ug" stage sol ptr)
                      (let ((result (make-array n :element-type 'single-float)))
                        (dotimes (i n)
                          (setf (aref result i) (cffi:mem-aref ptr :float i)))
                        result))
      (cffi-sys:foreign-free ptr))))