;; Auto-generated by cl-cl-generator (High-level API) — do not edit manually.
;; Generated: 2026-07-03 20:29:49
;; Git:       8b1a709f5be52303faf4a78d13929db1732945d3
(in-package :hpipm)

;; --- Solver Data Structure ---
(defstruct mpc-solver
  "Encapsulates all 5 HPIPM workspace and data pointers."
  precision
  horizon
  nx
  nu
  ns
  dim-ptr
  qp-ptr
  sol-ptr
  arg-ptr
  ws-ptr
  allocations)

;; --- Helper for Aligned Struct Allocation ---
(defun allocate-hpipm-struct (memsize-fn create-fn create-args)
  "Calculate HPIPM struct memsize, allocate aligned buffers, create struct."
  (let* ((mem-size (apply memsize-fn create-args))
         (backing (cffi:foreign-alloc :char :count (+ mem-size 64)))
         (aligned-backing (align-pointer backing 64))
         (ptr (cffi:foreign-alloc :char :count (+ +hpipm-struct-size+ 64)))
         (aligned-ptr (align-pointer ptr 64)))
    (apply create-fn (append create-args (list aligned-ptr aligned-backing)))
    (values aligned-ptr ptr backing)))

;; --- Stage Resolution Helper ---
(defun expand-stage-spec (spec horizon type)
  "Expand symbolic stage spec (like :all, :terminal, :path) or integer into concrete stage list."
  (let ((n horizon))
    (cond
      ((integerp spec) (list spec))
      ((eq spec :all)
       (if (eq type :input)
           (loop for k from 0 below n
                 collect k)
           (loop for k from 0 to n
                 collect k)))
      ((eq spec :terminal) (list n))
      ((eq spec :path)
       (loop for k from 0 below n
             collect k))
      (t (error "Invalid stage specification: ~a" spec)))))

;; --- Constructor and Destructor ---
(defun make-mpc-solver (&key (horizon 20) (nx 4) (nu 1) (nbu 0) (nbx 0) (ng 0)
                        (precision :double) (mode :balance) soft-constraints)
  "Create, allocate, and initialize an MPC solver object."
  (let* ((nx-list
          (if (integerp nx)
              (make-list (+ horizon 1) :initial-element nx)
              (coerce nx 'list)))
         (nu-list
          (if (integerp nu)
              (append (make-list horizon :initial-element nu) (list 0))
              (coerce nu 'list)))
         (nbu-list
          (if (integerp nbu)
              (append (make-list horizon :initial-element nbu) (list 0))
              (coerce nbu 'list)))
         (nbx-list
          (if (integerp nbx)
              (cons (elt nx-list 0) (make-list horizon :initial-element nbx))
              (coerce nbx 'list)))
         (ng-list
          (if (integerp ng)
              (make-list (+ horizon 1) :initial-element ng)
              (coerce ng 'list)))
         (soft-by-stage (make-array (+ horizon 1) :initial-element nil))
         (allocations nil))
    (dolist (sc soft-constraints)
      (let* ((stage-spec (getf sc :stage)) (sc-type (getf sc :type))
             (stages (expand-stage-spec stage-spec horizon sc-type)))
        (dolist (st stages)
          (push sc (aref soft-by-stage st)))))
    (dotimes (k (+ horizon 1))
      (setf (aref soft-by-stage k) (nreverse (aref soft-by-stage k))))
    (flet ((register-alloc (aligned original backing)
            (push original allocations) (push backing allocations) aligned))
      (multiple-value-bind (dim-ptr dim-orig dim-back) (ecase precision
                                                         (:double
                                                          (allocate-hpipm-struct
                                                           #'d-ocp-qp-dim-memsize
                                                           #'d-ocp-qp-dim-create
                                                           (list horizon)))
                                                         (:single
                                                          (allocate-hpipm-struct
                                                           #'s-ocp-qp-dim-memsize
                                                           #'s-ocp-qp-dim-create
                                                           (list horizon))))
        (register-alloc dim-ptr dim-orig dim-back)
        (dotimes (k (+ horizon 1))
          (let ((stage-nx (elt nx-list k)) (stage-nu (elt nu-list k))
                (stage-nbx (elt nbx-list k)) (stage-nbu (elt nbu-list k))
                (stage-ng (elt ng-list k))
                (stage-ns (length (aref soft-by-stage k))))
            (ecase precision
              (:double
               (d-ocp-qp-dim-set-nx k stage-nx dim-ptr)
               (d-ocp-qp-dim-set-nu k stage-nu dim-ptr)
               (d-ocp-qp-dim-set-nbx k stage-nbx dim-ptr)
               (d-ocp-qp-dim-set-nbu k stage-nbu dim-ptr)
               (d-ocp-qp-dim-set-ng k stage-ng dim-ptr)
               (d-ocp-qp-dim-set-ns k stage-ns dim-ptr))
              (:single
               (s-ocp-qp-dim-set-nx k stage-nx dim-ptr)
               (s-ocp-qp-dim-set-nu k stage-nu dim-ptr)
               (s-ocp-qp-dim-set-nbx k stage-nbx dim-ptr)
               (s-ocp-qp-dim-set-nbu k stage-nbu dim-ptr)
               (s-ocp-qp-dim-set-ng k stage-ng dim-ptr)
               (s-ocp-qp-dim-set-ns k stage-ns dim-ptr)))))
        (multiple-value-bind (qp-ptr qp-orig qp-back) (ecase precision
                                                        (:double
                                                         (allocate-hpipm-struct
                                                          #'d-ocp-qp-memsize
                                                          #'d-ocp-qp-create
                                                          (list dim-ptr)))
                                                        (:single
                                                         (allocate-hpipm-struct
                                                          #'s-ocp-qp-memsize
                                                          #'s-ocp-qp-create
                                                          (list dim-ptr))))
          (register-alloc qp-ptr qp-orig qp-back)
          (dotimes (k (+ horizon 1))
            (let* ((scs (aref soft-by-stage k)) (ns (length scs))
                   (nbu (elt nbu-list k)) (nbx (elt nbx-list k)))
              (when (> ns 0)
                (let ((idxs (make-array ns :element-type 'integer))
                      (zl-weight (make-array ns :element-type 'double-float))
                      (zu-weight (make-array ns :element-type 'double-float))
                      (zl-grad (make-array ns :element-type 'double-float))
                      (zu-grad (make-array ns :element-type 'double-float))
                      (lls
                       (make-array ns :element-type 'double-float
                                   :initial-element 0.0d0))
                      (lus
                       (make-array ns :element-type 'double-float
                                   :initial-element 0.0d0)))
                  (dotimes (i ns)
                    (let* ((sc (elt scs i)) (sc-type (getf sc :type))
                           (idx (getf sc :index))
                           (c-idx
                            (ecase sc-type
                              (:input idx)
                              (:state (+ nbu idx))
                              (:general (+ nbu nbx idx)))))
                      (setf (aref idxs i) c-idx)
                      (setf (aref zl-weight i)
                              (coerce (or (getf sc :z) 1000.0d0) 'double-float))
                      (setf (aref zu-weight i)
                              (coerce (or (getf sc :z) 1000.0d0) 'double-float))
                      (setf (aref zl-grad i)
                              (coerce (or (getf sc :z) 0.0d0) 'double-float))
                      (setf (aref zu-grad i)
                              (coerce (or (getf sc :z) 0.0d0) 'double-float))))
                  (ecase precision
                    (:double
                     (d-ocp-qp-set-idxs k (coerce idxs 'list) qp-ptr)
                     (d-ocp-qp-set-zl-mat k zl-weight qp-ptr)
                     (d-ocp-qp-set-zu-mat k zu-weight qp-ptr)
                     (d-ocp-qp-set-zl-vec k zl-grad qp-ptr)
                     (d-ocp-qp-set-zu-vec k zu-grad qp-ptr)
                     (d-ocp-qp-set-lls k lls qp-ptr)
                     (d-ocp-qp-set-lus k lus qp-ptr))
                    (:single
                     (s-ocp-qp-set-idxs k (coerce idxs 'list) qp-ptr)
                     (s-ocp-qp-set-zl-mat k
                      (map 'simple-vector
                           (lambda (x)
                             (coerce x 'single-float))
                           zl-weight)
                      qp-ptr)
                     (s-ocp-qp-set-zu-mat k
                      (map 'simple-vector
                           (lambda (x)
                             (coerce x 'single-float))
                           zu-weight)
                      qp-ptr)
                     (s-ocp-qp-set-zl-vec k
                      (map 'simple-vector
                           (lambda (x)
                             (coerce x 'single-float))
                           zl-grad)
                      qp-ptr)
                     (s-ocp-qp-set-zu-vec k
                      (map 'simple-vector
                           (lambda (x)
                             (coerce x 'single-float))
                           zu-grad)
                      qp-ptr)
                     (s-ocp-qp-set-lls k
                      (map 'simple-vector
                           (lambda (x)
                             (coerce x 'single-float))
                           lls)
                      qp-ptr)
                     (s-ocp-qp-set-lus k
                      (map 'simple-vector
                           (lambda (x)
                             (coerce x 'single-float))
                           lus)
                      qp-ptr)))))))
          (multiple-value-bind (sol-ptr sol-orig sol-back) (ecase precision
                                                             (:double
                                                              (allocate-hpipm-struct
                                                               #'d-ocp-qp-sol-memsize
                                                               #'d-ocp-qp-sol-create
                                                               (list dim-ptr)))
                                                             (:single
                                                              (allocate-hpipm-struct
                                                               #'s-ocp-qp-sol-memsize
                                                               #'s-ocp-qp-sol-create
                                                               (list dim-ptr))))
            (register-alloc sol-ptr sol-orig sol-back)
            (multiple-value-bind (arg-ptr arg-orig arg-back) (ecase precision
                                                               (:double
                                                                (allocate-hpipm-struct
                                                                 #'d-ocp-qp-ipm-arg-memsize
                                                                 #'d-ocp-qp-ipm-arg-create
                                                                 (list
                                                                  dim-ptr)))
                                                               (:single
                                                                (allocate-hpipm-struct
                                                                 #'s-ocp-qp-ipm-arg-memsize
                                                                 #'s-ocp-qp-ipm-arg-create
                                                                 (list
                                                                  dim-ptr))))
              (register-alloc arg-ptr arg-orig arg-back)
              (let ((mode-const
                     (case mode
                       (:speed +hpipm-mode-speed+)
                       (:balance +hpipm-mode-balance+)
                       (:robust +hpipm-mode-robust+)
                       (t mode))))
                (ecase precision
                  (:double (d-ocp-qp-ipm-arg-set-default mode-const arg-ptr))
                  (:single (s-ocp-qp-ipm-arg-set-default mode-const arg-ptr))))
              (multiple-value-bind (ws-ptr ws-orig ws-back) (ecase precision
                                                              (:double
                                                               (allocate-hpipm-struct
                                                                #'d-ocp-qp-ipm-ws-memsize
                                                                #'d-ocp-qp-ipm-ws-create
                                                                (list dim-ptr
                                                                      arg-ptr)))
                                                              (:single
                                                               (allocate-hpipm-struct
                                                                #'s-ocp-qp-ipm-ws-memsize
                                                                #'s-ocp-qp-ipm-ws-create
                                                                (list dim-ptr
                                                                      arg-ptr))))
                (register-alloc ws-ptr ws-orig ws-back)
                (make-mpc-solver :precision precision :horizon horizon :nx
                 nx-list :nu nu-list :ns
                 (loop for k from 0 to horizon
                       collect (length (aref soft-by-stage k)))
                 :dim-ptr dim-ptr :qp-ptr qp-ptr :sol-ptr sol-ptr :arg-ptr
                 arg-ptr :ws-ptr ws-ptr :allocations allocations)))))))))

(defun free-mpc-solver (solver)
  "Free all allocated foreign memory for SOLVER."
  (dolist (ptr (mpc-solver-allocations solver))
    (cffi-sys:foreign-free ptr))
  (setf (mpc-solver-allocations solver) nil))

(defmacro with-mpc-solver ((solver-var &rest make-args) &body body)
  "Create an MPC solver, bind to SOLVER-VAR, run BODY, and ensure it is freed."
  `(let ((,solver-var (make-mpc-solver ,@make-args)))
     (unwind-protect (progn
                       ,@body)
       (free-mpc-solver ,solver-var))))

;; --- Setter Functions ---
(defun set-solver-stage-dynamics (solver stage a b)
  "Set dynamics transition matrix A and input matrix B for a specific STAGE."
  (let ((prec (mpc-solver-precision solver)) (qp (mpc-solver-qp-ptr solver)))
    (ecase prec
      (:double (d-ocp-qp-set-a stage a qp) (d-ocp-qp-set-b stage b qp))
      (:single (s-ocp-qp-set-a stage a qp) (s-ocp-qp-set-b stage b qp)))))

(defun set-solver-dynamics (solver a b)
  "Set uniform dynamics matrices A and B across all stages 0..N-1."
  (dotimes (k (mpc-solver-horizon solver))
    (set-solver-stage-dynamics solver k a b)))

(defun set-solver-stage-cost (solver stage q r &key s)
  "Set quadratic stage cost Hessian matrices Q (states) and R (inputs), and optional cross-term S."
  (let ((prec (mpc-solver-precision solver)) (qp (mpc-solver-qp-ptr solver)))
    (ecase prec
      (:double
       (when q
         (d-ocp-qp-set-q stage q qp))
       (when r
         (d-ocp-qp-set-r stage r qp))
       (when s
         (d-ocp-qp-set-s stage s qp)))
      (:single
       (when q
         (s-ocp-qp-set-q stage q qp))
       (when r
         (s-ocp-qp-set-r stage r qp))
       (when s
         (s-ocp-qp-set-s stage s qp))))))

(defun set-solver-cost (solver q r &key terminal-q)
  "Set uniform cost matrices Q and R for stages 0..N-1, and TERMINAL-Q (defaults to Q) for stage N."
  (let ((n (mpc-solver-horizon solver)))
    (dotimes (k n)
      (set-solver-stage-cost solver k q r))
    (set-solver-stage-cost solver n (or terminal-q q) nil)))

(defun set-control-bounds (solver index min max)
  "Set uniform control input bounds for control channel INDEX to range [MIN, MAX] across stages 0..N-1."
  (let ((prec (mpc-solver-precision solver)) (qp (mpc-solver-qp-ptr solver))
        (n (mpc-solver-horizon solver)))
    (dotimes (k n)
      (ecase prec
        (:double
         (d-ocp-qp-set-idxbu k (list index) qp)
         (d-ocp-qp-set-lbu k (list min) qp)
         (d-ocp-qp-set-ubu k (list max) qp))
        (:single
         (s-ocp-qp-set-idxbu k (list index) qp)
         (s-ocp-qp-set-lbu k (list min) qp)
         (s-ocp-qp-set-ubu k (list max) qp))))))

(defun set-state-bounds (solver stage indices min-values max-values)
  "Set state bounds at a specific STAGE for state INDICES (list of integers) to [MIN-VALUES, MAX-VALUES] (lists)."
  (let ((prec (mpc-solver-precision solver)) (qp (mpc-solver-qp-ptr solver)))
    (ecase prec
      (:double
       (d-ocp-qp-set-idxbx stage indices qp)
       (d-ocp-qp-set-lbx stage min-values qp)
       (d-ocp-qp-set-ubx stage max-values qp))
      (:single
       (s-ocp-qp-set-idxbx stage indices qp)
       (s-ocp-qp-set-lbx stage min-values qp)
       (s-ocp-qp-set-ubx stage max-values qp)))))

;; --- General Constraints Setters ---
(defun set-general-constraints (solver stage c d lg ug)
  "Set general linear constraints: lg <= C*x + D*u <= ug at a specific STAGE.
       If C or D are nil, they default to zero matrices of the correct dimensions."
  (let* ((prec (mpc-solver-precision solver)) (qp (mpc-solver-qp-ptr solver))
         (nx (elt (mpc-solver-nx solver) stage))
         (nu (elt (mpc-solver-nu solver) stage)) (ng (length lg))
         (element-type
          (ecase prec (:double 'double-float) (:single 'single-float)))
         (zero-val (ecase prec (:double 0.0d0) (:single 0.0)))
         (actual-c
          (or c
              (make-array (list ng nx) :element-type element-type
                          :initial-element zero-val)))
         (actual-d
          (or d
              (make-array (list ng nu) :element-type element-type
                          :initial-element zero-val))))
    (ecase prec
      (:double
       (d-ocp-qp-set-c stage actual-c qp)
       (d-ocp-qp-set-d stage actual-d qp)
       (d-ocp-qp-set-lg stage lg qp)
       (d-ocp-qp-set-ug stage ug qp))
      (:single
       (s-ocp-qp-set-c stage actual-c qp)
       (s-ocp-qp-set-d stage actual-d qp)
       (s-ocp-qp-set-lg stage
        (map 'list
             (lambda (x)
               (coerce x 'single-float))
             lg)
        qp)
       (s-ocp-qp-set-ug stage
        (map 'list
             (lambda (x)
               (coerce x 'single-float))
             ug)
        qp)))))

(defun set-solver-general-constraints (solver c d lg ug)
  "Set uniform general linear constraints across all stages 0..N-1."
  (dotimes (k (mpc-solver-horizon solver))
    (set-general-constraints solver k c d lg ug)))

;; --- Solver Call ---
(defun solve-mpc (solver x0)
  "Lock the initial state at stage 0 to X0, solve, and return (values u-trajectory x-trajectory status iterations sl-trajectory su-trajectory)."
  (let ((prec (mpc-solver-precision solver)) (qp (mpc-solver-qp-ptr solver))
        (sol (mpc-solver-sol-ptr solver)) (arg (mpc-solver-arg-ptr solver))
        (ws (mpc-solver-ws-ptr solver)) (n (mpc-solver-horizon solver))
        (nx (elt (mpc-solver-nx solver) 0)) (nu-list (mpc-solver-nu solver))
        (nx-list (mpc-solver-nx solver)) (ns-list (mpc-solver-ns solver)))
    (let ((indices
           (loop for i from 0 below nx
                 collect i)))
      (set-state-bounds solver 0 indices x0 x0))
    (ecase prec
      (:double (d-ocp-qp-ipm-solve qp sol arg ws))
      (:single (s-ocp-qp-ipm-solve qp sol arg ws)))
    (let ((status
           (ecase prec
             (:double (d-ocp-qp-ipm-get-status-val ws))
             (:single (s-ocp-qp-ipm-get-status-val ws))))
          (iterations
           (ecase prec
             (:double (d-ocp-qp-ipm-get-iter-val ws))
             (:single (s-ocp-qp-ipm-get-iter-val ws))))
          (u-traj (make-array n)) (x-traj (make-array (+ n 1)))
          (sl-traj (make-array (+ n 1))) (su-traj (make-array (+ n 1))))
      (dotimes (k n)
        (let ((nu (elt nu-list k)))
          (setf (aref u-traj k)
                  (ecase prec
                    (:double (d-ocp-qp-sol-get-u k nu sol))
                    (:single (s-ocp-qp-sol-get-u k nu sol))))))
      (dotimes (k (+ n 1))
        (let ((nx (elt nx-list k)))
          (setf (aref x-traj k)
                  (ecase prec
                    (:double (d-ocp-qp-sol-get-x k nx sol))
                    (:single (s-ocp-qp-sol-get-x k nx sol))))))
      (dotimes (k (+ n 1))
        (let ((ns (elt ns-list k)))
          (setf (aref sl-traj k)
                  (if (> ns 0)
                      (ecase prec
                        (:double (d-ocp-qp-sol-get-sl k ns sol))
                        (:single (s-ocp-qp-sol-get-sl k ns sol)))
                      #()))
          (setf (aref su-traj k)
                  (if (> ns 0)
                      (ecase prec
                        (:double (d-ocp-qp-sol-get-su k ns sol))
                        (:single (s-ocp-qp-sol-get-su k ns sol)))
                      #()))))
      (values u-traj x-traj status iterations sl-traj su-traj))))