;; Auto-generated by cl-cl-generator (High-level API) — do not edit manually.
;; Generated: 2026-07-03 20:44:23
;; Git:       cb3c813766ff0be29dac48dc8ce6cf9703d35977
;; ================================================================================
;;  MPC Demo with Soft-Constraints: Coupled Mass-Spring-Damper System
;; ================================================================================
(defpackage :hpipm-soft-demo
  (:use :cl :hpipm)
  (:export :run-soft-demo))

(in-package :hpipm-soft-demo)

(defun run-soft-demo ()
  "Run mass-spring-damper MPC simulation showing how soft constraints handle otherwise infeasible bounds."
  (let* ((n 20) (nx 4) (nu 1)
         (ad
          (make-array '(4 4) :element-type 'double-float :initial-contents
                      (list (list 1.0d0 0.1d0 0.0d0 0.0d0)
                            (list -0.2d0 0.98d0 0.1d0 0.010000000000000002d0)
                            (list 0.0d0 0.0d0 1.0d0 0.1d0)
                            (list 0.1d0 0.010000000000000002d0 -0.1d0
                                  0.99d0))))
         (bd
          (make-array '(4 1) :element-type 'double-float :initial-contents
                      (list (list 0.0d0) (list 0.1d0) (list 0.0d0)
                            (list 0.0d0))))
         (q
          (make-array '(4 4) :element-type 'double-float :initial-contents
                      '((1.0d0 0.0d0 0.0d0 0.0d0) (0.0d0 0.1d0 0.0d0 0.0d0)
                        (0.0d0 0.0d0 1.0d0 0.0d0) (0.0d0 0.0d0 0.0d0 0.1d0))))
         (r
          (make-array '(1 1) :element-type 'double-float :initial-contents
                      '((0.01d0))))
         (u-max 5.0d0) (x0 '(1.0d0 0.0d0 0.5d0 0.0d0))
         (soft-specs
          '((:stage :all :type :state :index 0 :z-weight 10000.0 :z-grad 0.0))))
    (format t "~%=== HPIPM MPC Soft-Constraints Demo ===~%")
    (format t "Horizon N=~a, nx=~a, nu=~a~%" n nx nu)
    (format t "Initial state: ~a~%" x0)
    (format t
            "Target: Restrict mass 2 position x2 <= 0.4m (softened with weight Z=1e4)~%")
    (with-mpc-solver
     (solver :horizon n :nx nx :nu nu :nbx 1 :precision :double
      :soft-constraints soft-specs)
     (set-solver-dynamics solver ad bd) (set-solver-cost solver q r)
     (set-control-bounds solver 0 (- u-max) u-max)
     (dotimes (k n)
       (set-state-bounds solver (+ k 1) '(2) '(-2.0d0) '(0.4d0)))
     (multiple-value-bind (u-traj x-traj status iterations sl-traj
                           su-traj) (solve-mpc solver x0)
       (format t "~%Solver finished with status ~a after ~a iterations.~%"
               status iterations)
       (format t "~%Optimal state trajectory x* & slacks s_u* at mass 2:~%")
       (dotimes (k (+ n 1))
         (let* ((xk (aref x-traj k)) (suk (aref su-traj k))
                (slack-val
                 (if (> (length suk) 0)
                     (aref suk 0)
                     0.0d0)))
           (format t "  Stage ~2d | x2 = ~8,4f m | upper slack = ~8,4f m~%" k
                   (aref xk 2) slack-val)))
       (format t "~%MPC soft-constraints demo complete.~%")))))