;; Auto-generated by cl-cl-generator (High-level API) — do not edit manually.
;; Generated: 2026-07-03 20:17:44
;; Git:       e885acae92ca1a275a0fca3e434c2a21a1ff383b
;; ================================================================================
;;  MPC Demo (High-Level API): Coupled Mass-Spring-Damper System
;; ================================================================================
(defpackage :hpipm-demo-high
  (:use :cl :hpipm)
  (:export :run-mpc-demo))

(in-package :hpipm-demo-high)

(defun run-mpc-demo ()
  "Run the coupled mass-spring-damper MPC simulation using the high-level API."
  (let* ((n 20) (nx 4) (nu 1)
         (ad
          (make-array '(4 4) :element-type 'double-float :initial-contents
                      (list (list 1.0d0 0.1d0 0.0d0 0.0d0)
                            (list -0.2d0 0.98d0 0.1d0 0.010000000000000002d0)
                            (list 0.0d0 0.0d0 1.0d0 0.1d0)
                            (list 0.1d0 0.010000000000000002d0 -0.1d0
                                  0.99d0))))
         (bd
          (make-array '(4 1) :element-type 'double-float :initial-contents
                      (list (list 0.0d0) (list 0.1d0) (list 0.0d0)
                            (list 0.0d0))))
         (q
          (make-array '(4 4) :element-type 'double-float :initial-contents
                      '((1.0d0 0.0d0 0.0d0 0.0d0) (0.0d0 0.1d0 0.0d0 0.0d0)
                        (0.0d0 0.0d0 1.0d0 0.0d0) (0.0d0 0.0d0 0.0d0 0.1d0))))
         (r
          (make-array '(1 1) :element-type 'double-float :initial-contents
                      '((0.01d0))))
         (u-max 5.0d0) (x0 '(1.0d0 0.0d0 0.5d0 0.0d0)))
    (format t "~%=== HPIPM MPC Demo (High-Level API): Mass-Spring-Damper ===~%")
    (format t "Horizon N=~a, nx=~a, nu=~a~%" n nx nu)
    (format t "Initial state: ~a~%" x0)
    (with-mpc-solver
     (solver :horizon n :nx nx :nu nu :precision :double :mode :balance)
     (set-solver-dynamics solver ad bd) (set-solver-cost solver q r)
     (set-control-bounds solver 0 (- u-max) u-max)
     (multiple-value-bind (u-traj x-traj status iterations) (solve-mpc solver
                                                             x0)
       (format t "~%Solver finished with status ~a after ~a iterations.~%"
               status iterations)
       (format t "~%Optimal control force input trajectory u* (Newtons):~%")
       (dotimes (k n)
         (format t "  u[~2d] = ~8,4f~%" k (aref (aref u-traj k) 0)))
       (format t
               "~%Optimal state trajectory x* (predicted positions & velocities):~%")
       (dotimes (k (+ n 1))
         (let ((xk (aref x-traj k)))
           (format t
                   "  x[~2d] = [pos1:~8,4f vel1:~8,4f pos2:~8,4f vel2:~8,4f]~%"
                   k (aref xk 0) (aref xk 1) (aref xk 2) (aref xk 3))))
       (format t "~%MPC demo complete.~%")))))