;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 18:26:51
;; Git:       6d7c236b32faa713eed921c78ef8bd2269e05b55
;; MPC demo: two coupled masses with spring and damper
;; System: m1*a1 = -2k*x1 + k*x2 - 2c*v1 + c*v2 + u
;;          m2*a2 =  k*x1 - k*x2 + c*v1 - c*v2
;; State: [x1 v1 x2 v2], Input: [F], Horizon: N=20
(defpackage :hpipm-demo
  (:use :cl :hpipm)
  (:export :run-mpc-demo))

(in-package :hpipm-demo)

(defun run-mpc-demo ()
  (let* ((n 20)
          (nx 4)
          (nu 1)
          (nbu 1)
          (nbx-0 4)
          ;; Discrete-time system matrices (Euler, dt=0.1)
          (ad
           (make-array '(4 4) :element-type 'double-float :initial-contents
                       (list (list 1.0d0 0.1d0 0.0d0 0.0d0)
                             (list -0.2d0 0.98d0 0.1d0 0.010000000000000002d0)
                             (list 0.0d0 0.0d0 1.0d0 0.1d0)
                             (list 0.1d0 0.010000000000000002d0 -0.1d0
                                   0.99d0))))
          (bd
           (make-array '(4 1) :element-type 'double-float :initial-contents
                       (list (list 0.0d0) (list 0.1d0) (list 0.0d0)
                             (list 0.0d0))))
          ;; Cost matrices
          (q
           (make-array '(4 4) :element-type 'double-float :initial-contents
                       '((1.0d0 0.0d0 0.0d0 0.0d0) (0.0d0 0.1d0 0.0d0 0.0d0)
                         (0.0d0 0.0d0 1.0d0 0.0d0) (0.0d0 0.0d0 0.0d0 0.1d0))))
          (r
           (make-array '(1 1) :element-type 'double-float :initial-contents
                       '((0.01d0))))
          ;; Constraints and initial state
          (u-max 5.0d0)
          (x0 '(1.0d0 0.0d0 0.5d0 0.0d0)))
    (format t "~%=== HPIPM MPC Demo: Mass-Spring-Damper ===~%")
    (format t "Horizon N=~a, nx=~a, nu=~a~%" n nx nu)
    (format t "Initial state: ~a~%" x0)
    ;; 1. Set up dimensions
    (call-with-d-ocp-qp-dim n
     (lambda (dim)
       (dotimes (k (+ n 1))
         (d-ocp-qp-dim-set-nx k nx dim)
         (if (< k n)
             (progn
               (d-ocp-qp-dim-set-nu k nu dim)
               (d-ocp-qp-dim-set-nbu k nbu dim))
             (progn
               (d-ocp-qp-dim-set-nu k 0 dim)
               (d-ocp-qp-dim-set-nbu k 0 dim)))
         (if (= k 0)
             (d-ocp-qp-dim-set-nbx k nbx-0 dim)
             (d-ocp-qp-dim-set-nbx k 0 dim)))
       ;; 2. Set up QP data
       (call-with-d-ocp-qp dim
        (lambda (qp)
          (dotimes (k n)
            (d-ocp-qp-set-a k ad qp)
            (d-ocp-qp-set-b k bd qp)
            (d-ocp-qp-set-q k q qp)
            (d-ocp-qp-set-r k r qp)
            (d-ocp-qp-set-idxbu k '(0) qp)
            (d-ocp-qp-set-lbu k (list (- u-max)) qp)
            (d-ocp-qp-set-ubu k (list u-max) qp))
          ;; Terminal cost
          (d-ocp-qp-set-q n q qp)
          ;; Initial state constraint: lbx[0] = ubx[0] = x0
          (d-ocp-qp-set-idxbx 0 '(0 1 2 3) qp)
          (d-ocp-qp-set-lbx 0 x0 qp)
          (d-ocp-qp-set-ubx 0 x0 qp)
          ;; 3. Create solution struct
          (call-with-d-ocp-qp-sol dim
           (lambda (sol)
             ;; 4. Create solver arguments
             (call-with-d-ocp-qp-ipm-arg dim
              (lambda (arg)
                (d-ocp-qp-ipm-arg-set-default +hpipm-mode-balance+ arg)
                ;; 5. Create workspace and solve
                (call-with-d-ocp-qp-ipm-ws dim arg
                 (lambda (ws)
                   (d-ocp-qp-ipm-solve qp sol arg ws)
                   ;; 6. Extract and print results
                   (format t "~%Optimal inputs u*:~%")
                   (dotimes (k n)
                     (let ((uk (d-ocp-qp-sol-get-u k nu sol)))
                       (format t "  u[~2d] = ~8,4f~%" k (aref uk 0))))
                   (format t "~%Optimal states x*:~%")
                   (dotimes (k (+ n 1))
                     (let ((xk (d-ocp-qp-sol-get-x k nx sol)))
                       (format t "  x[~2d] = [~{~8,4f~^ ~}]~%" k
                               (coerce xk 'list))))
                   (format t "~%MPC demo complete.~%")))))))))))))