;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 20:17:13
;; Git:       e885acae92ca1a275a0fca3e434c2a21a1ff383b
;; ================================================================================
;;  MPC Demo: Coupled Mass-Spring-Damper System Stabilizer
;; ================================================================================
;;  This file contains a complete, self-contained Model Predictive Control (MPC)
;;  simulation using the HPIPM high-performance QP solver.
;; System Description:
;;   We simulate two unit masses (m1 = m2 = 1.0 kg) connected to each other and to the
;;   walls via springs (stiffness k = 1.0 N/m) and dampers (damping c = 0.1 N/m/s).
;;   An actuator applies a force 'u' (in Newtons) directly to mass 1.
;;
;; State Vector Layout (nx = 4):
;;   x[0] = x1 : position of mass 1 (meters)
;;   x[1] = v1 : velocity of mass 1 (meters/second)
;;   x[2] = x2 : position of mass 2 (meters)
;;   x[3] = v2 : velocity of mass 2 (meters/second)
;;
;; Control Vector Layout (nu = 1):
;;   u[0] = F  : force applied to mass 1 (Newtons)
;;
;; Continuous-Time System Equations (Ac & Bc):
;;   dx1/dt = v1
;;   dv1/dt = -2*k*x1 - 2*c*v1 + k*x2 + c*v2 + F
;;   dx2/dt = v2
;;   dv2/dt = k*x1 + c*v1 - k*x2 - c*v2
;;
;; Discrete-Time System Equations (Ad & Bd):
;;   Derived using Euler integration with sampling time dt = 0.1 seconds:
;;   x(k+1) = Ad * x(k) + Bd * u(k)
;;
;; Optimal Control Problem Formulation (solved at each step):
;;   minimize   Sum_{k=0..N-1} (x(k)^T * Q * x(k) + u(k)^T * R * u(k)) + x(N)^T * Q_term * x(N)
;;   subject to x(k+1) = Ad * x(k) + Bd * u(k)
;;              x(0)   = x0 (current measured state)
;;              -u_max <= u(k) <= u_max (actuator force constraints)
;;
;; HPIPM Lifecycle Steps demonstrated here:
;;   1. Allocate/initialize OCP QP Dimensions (dim)
;;   2. Allocate/initialize OCP QP Problem Data (qp) and set matrices (A, B, Q, R, bounds)
;;   3. Allocate/initialize OCP QP Solution structure (sol)
;;   4. Allocate/initialize Solver Settings (ipm_arg) and set defaults
;;   5. Allocate/initialize Solver Workspace (ipm_ws)
;;   6. Run the solver (d_ocp_qp_ipm_solve)
;;   7. Extract the optimal controls and predicted trajectories
;; ================================================================================
(defpackage :hpipm-demo
  (:use :cl :hpipm)
  (:export :run-mpc-demo))

(in-package :hpipm-demo)

(defun run-mpc-demo ()
  "Run the coupled mass-spring-damper MPC simulation."
  (let* ((n 20)
          ;; Prediction horizon (20 steps * 0.1s = 2.0 seconds look-ahead)
          (nx 4)
          ;; Number of states
          (nu 1)
          ;; Number of inputs
          (nbu 1)
          ;; Number of bounded control inputs (u is bounded)
          (nbx-0 4)
          ;; Number of bounded states at stage 0 (used to lock initial state x0)
          ;; Discretized dynamics transition matrix Ad
          (ad
           (make-array '(4 4) :element-type 'double-float :initial-contents
                       (list (list 1.0d0 0.1d0 0.0d0 0.0d0)
                             (list -0.2d0 0.98d0 0.1d0 0.010000000000000002d0)
                             (list 0.0d0 0.0d0 1.0d0 0.1d0)
                             (list 0.1d0 0.010000000000000002d0 -0.1d0
                                   0.99d0))))
          ;; Discretized dynamics input matrix Bd
          (bd
           (make-array '(4 1) :element-type 'double-float :initial-contents
                       (list (list 0.0d0) (list 0.1d0) (list 0.0d0)
                             (list 0.0d0))))
          ;; State cost weighting matrix Q (penalizes deviations from zero)
          (q
           (make-array '(4 4) :element-type 'double-float :initial-contents
                       '((1.0d0 0.0d0 0.0d0 0.0d0)
                          ;; Penalize mass 1 position displacement
                          (0.0d0 0.1d0 0.0d0 0.0d0)
                          ;; Subtle penalty on mass 1 velocity to damp oscillations
                          (0.0d0 0.0d0 1.0d0 0.0d0)
                          ;; Penalize mass 2 position displacement
                          (0.0d0 0.0d0 0.0d0 0.1d0))))
          ;; Subtle penalty on mass 2 velocity
          ;; Control cost weighting matrix R (penalizes actuator effort)
          (r
           (make-array '(1 1) :element-type 'double-float :initial-contents
                       '((0.01d0))))
          ;; Constraints: maximum absolute force allowed (Newtons)
          (u-max 5.0d0)
          ;; Initial state: mass 1 at +1.0m, mass 2 at +0.5m, both stationary
          (x0 '(1.0d0 0.0d0 0.5d0 0.0d0)))
    (format t "~%=== HPIPM MPC Demo: Mass-Spring-Damper ===~%")
    (format t "Horizon N=~a, nx=~a, nu=~a~%" n nx nu)
    (format t "Initial state: ~a~%" x0)
    ;; ----------------------------------------------------------------
    ;;  Step 1: Set up OCP QP dimensions
    ;; ----------------------------------------------------------------
    (call-with-d-ocp-qp-dim n
     (lambda (dim)
       ;; Loop over all stages to define state, control, and constraint counts
       (dotimes (k (+ n 1))
         (d-ocp-qp-dim-set-nx k nx dim)
         (if (< k n)
             (progn
               (d-ocp-qp-dim-set-nu k nu dim)
               ;; We place box constraints on control inputs at stages 0..N-1
               (d-ocp-qp-dim-set-nbu k nbu dim))
             (progn
               (d-ocp-qp-dim-set-nu k 0 dim)
               (d-ocp-qp-dim-set-nbu k 0 dim)))
         ;; We place box constraints on state ONLY at stage 0 (to enforce x0)
         (if (= k 0)
             (d-ocp-qp-dim-set-nbx k nbx-0 dim)
             (d-ocp-qp-dim-set-nbx k 0 dim)))
       ;; ----------------------------------------------------------------
       ;;  Step 2: Set up OCP QP problem data
       ;; ----------------------------------------------------------------
       (call-with-d-ocp-qp dim
        (lambda (qp)
          ;; Set dynamics transition, input, and cost matrices for stage 0..N-1
          (dotimes (k n)
            (d-ocp-qp-set-a k ad qp)
            (d-ocp-qp-set-b k bd qp)
            (d-ocp-qp-set-q k q qp)
            (d-ocp-qp-set-r k r qp)
            ;; Enforce bounds on control: index 0 (u) is bounded by [-u-max, u-max]
            (d-ocp-qp-set-idxbu k '(0) qp)
            (d-ocp-qp-set-lbu k (list (- u-max)) qp)
            (d-ocp-qp-set-ubu k (list u-max) qp))
          ;; Set terminal cost at stage N
          (d-ocp-qp-set-q n q qp)
          ;; Enforce initial state constraints: x(0) must equal x0
          ;; We lock all 4 states (indices 0, 1, 2, 3) to the initial value x0
          (d-ocp-qp-set-idxbx 0 '(0 1 2 3) qp)
          (d-ocp-qp-set-lbx 0 x0 qp)
          (d-ocp-qp-set-ubx 0 x0 qp)
          ;; ----------------------------------------------------------------
          ;;  Step 3: Create solution structure
          ;; ----------------------------------------------------------------
          (call-with-d-ocp-qp-sol dim
           (lambda (sol)
             ;; ----------------------------------------------------------------
             ;;  Step 4: Create solver settings / arguments
             ;; ----------------------------------------------------------------
             (call-with-d-ocp-qp-ipm-arg dim
              (lambda (arg)
                ;; Choose balance mode (trade-off between speed and accuracy)
                (d-ocp-qp-ipm-arg-set-default +hpipm-mode-balance+ arg)
                ;; ----------------------------------------------------------------
                ;;  Step 5 & 6: Create solver workspace and solve the QP
                ;; ----------------------------------------------------------------
                (call-with-d-ocp-qp-ipm-ws dim arg
                 (lambda (ws)
                   (d-ocp-qp-ipm-solve qp sol arg ws)
                   ;; ----------------------------------------------------------------
                   ;;  Step 7: Extract and print the optimal solution trajectory
                   ;; ----------------------------------------------------------------
                   (format t
                           "~%Optimal control force input trajectory u* (Newtons):~%")
                   (dotimes (k n)
                     (let ((uk (d-ocp-qp-sol-get-u k nu sol)))
                       (format t "  u[~2d] = ~8,4f~%" k (aref uk 0))))
                   (format t
                           "~%Optimal state trajectory x* (predicted positions & velocities):~%")
                   (dotimes (k (+ n 1))
                     (let ((xk (d-ocp-qp-sol-get-x k nx sol)))
                       (format t
                               "  x[~2d] = [pos1:~8,4f vel1:~8,4f pos2:~8,4f vel2:~8,4f]~%"
                               k (aref xk 0) (aref xk 1) (aref xk 2)
                               (aref xk 3))))
                   (format t "~%MPC demo complete.~%")))))))))))))