;; Auto-generated by cl-cl-generator — do not edit manually.
;; Generated: 2026-07-03 20:29:34
;; Git:       8b1a709f5be52303faf4a78d13929db1732945d3
;; ================================================================================
;;  MPC Demo: Inverted Pendulum on a Cart Stabilizer
;; ================================================================================
;;  This file contains a complete, self-contained Model Predictive Control (MPC)
;;  simulation to balance an unstable inverted pendulum on a moving cart.
;; System Description:
;;   An unstable pendulum is mounted on a cart. We want to stabilize the pendulum in the
;;   upright position (theta = 0) and keep the cart at position x = 0 by applying a force
;;   actuator 'u' directly to the cart.
;;
;; State Vector Layout (nx = 4):
;;   x[0] = p     : cart position (meters)
;;   x[1] = v     : cart velocity (meters/second)
;;   x[2] = theta : pendulum angle (radians, 0 is upright, positive is tilted right)
;;   x[3] = omega : pendulum angular velocity (radians/second)
;;
;; Control Vector Layout (nu = 1):
;;   u[0] = F     : force applied to the cart (Newtons)
;;
;; Linearized continuous dynamics (around theta=0) with parameters:
;;   M = 1.0 kg, m = 0.1 kg, l = 0.5 m, g = 9.81 m/s^2, b = 0.1 N/m/s
;;
;; Discrete-Time dynamics (Ad & Bd):
;;   Euler discretized with sampling time dt = 0.05 seconds (20 Hz controller rate)
;;
;; Cost Function Weights:
;;   Penalizes angular deviation heavily to force stabilization, with minor penalty
;;   on cart position to slowly drift back to center.
;; ================================================================================
(defpackage :hpipm-pendulum-demo
  (:use :cl :hpipm)
  (:export :run-pendulum-demo))

(in-package :hpipm-pendulum-demo)

(defun run-pendulum-demo ()
  "Run the unstable inverted pendulum MPC stabilization simulation."
  (let* ((n 30)
          ;; Prediction horizon (30 steps * 0.05s = 1.5 seconds look-ahead)
          (nx 4)
          ;; Number of states
          (nu 1)
          ;; Number of inputs
          (nbu 1)
          ;; Number of bounded control inputs (force on cart)
          (nbx-0 4)
          ;; Number of bounded states at stage 0 (locked to initial condition)
          ;; Discrete dynamics transition matrix Ad
          (ad
           (make-array '(4 4) :element-type 'double-float :initial-contents
                       (list (list 1.0d0 0.05d0 0.0d0 0.0d0)
                             (list 0.0d0 0.99512195d0 0.03589024d0 0.0d0)
                             (list 0.0d0 0.0d0 1.0d0 0.05d0)
                             (list 0.0d0 -0.00731707d0 0.78958537d0 1.0d0))))
          ;; Discrete dynamics input matrix Bd
          (bd
           (make-array '(4 1) :element-type 'double-float :initial-contents
                       (list (list 0.0d0) (list 0.04878049d0) (list 0.0d0)
                             (list 0.07317073d0))))
          ;; State cost matrix Q: penalizes state deviation from center/upright
          (q
           (make-array '(4 4) :element-type 'double-float :initial-contents
                       '((10.0d0 0.0d0 0.0d0 0.0d0)
                          ;; Moderate weight on cart position (keep near 0)
                          (0.0d0 1.0d0 0.0d0 0.0d0)
                          ;; Subtle weight on cart velocity
                          (0.0d0 0.0d0 100.0d0 0.0d0)
                          ;; HEAVY weight on pendulum angle (vital for stabilization!)
                          (0.0d0 0.0d0 0.0d0 10.0d0))))
          ;; Moderate weight on angular velocity
          ;; Control cost matrix R: penalizes high force usage
          (r
           (make-array '(1 1) :element-type 'double-float :initial-contents
                       '((0.1d0))))
          ;; Constraint bounds: absolute force on cart limited to 10 Newtons
          (u-max 10.0d0)
          ;; Initial state x0: Cart centered, stationary. Pendulum tilted right by 0.2 rad (approx 11.5 deg).
          (x0 '(0.0d0 0.0d0 0.2d0 0.0d0)))
    (format t "~%=== HPIPM MPC Demo: Inverted Pendulum on Cart ===~%")
    (format t "Horizon N=~a, nx=~a, nu=~a~%" n nx nu)
    (format t "Initial state: ~a (tilted by ~5,2f deg)~%" x0
            (* 0.2d0 (/ 180.0d0 pi)))
    ;; 1. Set up dimensions
    (call-with-d-ocp-qp-dim n
     (lambda (dim)
       (dotimes (k (+ n 1))
         (d-ocp-qp-dim-set-nx k nx dim)
         (if (< k n)
             (progn
               (d-ocp-qp-dim-set-nu k nu dim)
               (d-ocp-qp-dim-set-nbu k nbu dim))
             (progn
               (d-ocp-qp-dim-set-nu k 0 dim)
               (d-ocp-qp-dim-set-nbu k 0 dim)))
         (if (= k 0)
             (d-ocp-qp-dim-set-nbx k nbx-0 dim)
             (d-ocp-qp-dim-set-nbx k 0 dim)))
       ;; 2. Set up QP data
       (call-with-d-ocp-qp dim
        (lambda (qp)
          (dotimes (k n)
            (d-ocp-qp-set-a k ad qp)
            (d-ocp-qp-set-b k bd qp)
            (d-ocp-qp-set-q k q qp)
            (d-ocp-qp-set-r k r qp)
            (d-ocp-qp-set-idxbu k '(0) qp)
            (d-ocp-qp-set-lbu k (list (- u-max)) qp)
            (d-ocp-qp-set-ubu k (list u-max) qp))
          (d-ocp-qp-set-q n q qp)
          ;; Lock initial state constraints at stage 0
          (d-ocp-qp-set-idxbx 0 '(0 1 2 3) qp)
          (d-ocp-qp-set-lbx 0 x0 qp)
          (d-ocp-qp-set-ubx 0 x0 qp)
          ;; 3. Create solution struct
          (call-with-d-ocp-qp-sol dim
           (lambda (sol)
             ;; 4. Create solver arguments
             (call-with-d-ocp-qp-ipm-arg dim
              (lambda (arg)
                (d-ocp-qp-ipm-arg-set-default +hpipm-mode-balance+ arg)
                ;; 5. Create workspace and solve
                (call-with-d-ocp-qp-ipm-ws dim arg
                 (lambda (ws)
                   (d-ocp-qp-ipm-solve qp sol arg ws)
                   ;; 6. Extract and print results
                   (format t "~%Optimal force trajectory u* (Newtons):~%")
                   (dotimes (k n)
                     (let ((uk (d-ocp-qp-sol-get-u k nu sol)))
                       (format t "  u[~2d] = ~8,4f~%" k (aref uk 0))))
                   (format t
                           "~%Optimal state trajectory x* (predicted cart position & pole angle):~%")
                   (dotimes (k (+ n 1))
                     (let ((xk (d-ocp-qp-sol-get-x k nx sol)))
                       (format t
                               "  x[~2d] = [cart_pos:~8,4f cart_vel:~8,4f pole_ang:~8,4f pole_vel:~8,4f]~%"
                               k (aref xk 0) (aref xk 1) (aref xk 2)
                               (aref xk 3))))
                   (format t
                           "~%Inverted pendulum stabilization complete.~%")))))))))))))