;; Auto-generated by cl-cl-generator (High-level API) — do not edit manually.
;; Generated: 2026-07-03 20:29:49
;; Git:       8b1a709f5be52303faf4a78d13929db1732945d3
;; ================================================================================
;;  MPC Demo (High-Level API): Inverted Pendulum on a Cart
;; ================================================================================
(defpackage :hpipm-pendulum-demo-high
  (:use :cl :hpipm)
  (:export :run-pendulum-demo))

(in-package :hpipm-pendulum-demo-high)

(defun run-pendulum-demo ()
  "Run the unstable inverted pendulum MPC stabilization simulation using the high-level API."
  (let* ((n 30) (nx 4) (nu 1)
         (ad
          (make-array '(4 4) :element-type 'double-float :initial-contents
                      (list (list 1.0d0 0.05d0 0.0d0 0.0d0)
                            (list 0.0d0 0.99512195d0 0.03589024d0 0.0d0)
                            (list 0.0d0 0.0d0 1.0d0 0.05d0)
                            (list 0.0d0 -0.00731707d0 0.78958537d0 1.0d0))))
         (bd
          (make-array '(4 1) :element-type 'double-float :initial-contents
                      (list (list 0.0d0) (list 0.04878049d0) (list 0.0d0)
                            (list 0.07317073d0))))
         (q
          (make-array '(4 4) :element-type 'double-float :initial-contents
                      '((10.0d0 0.0d0 0.0d0 0.0d0) (0.0d0 1.0d0 0.0d0 0.0d0)
                        (0.0d0 0.0d0 100.0d0 0.0d0)
                        (0.0d0 0.0d0 0.0d0 10.0d0))))
         (r
          (make-array '(1 1) :element-type 'double-float :initial-contents
                      '((0.1d0))))
         (u-max 10.0d0) (x0 '(0.0d0 0.0d0 0.2d0 0.0d0)))
    (format t
            "~%=== HPIPM MPC Demo (High-Level API): Inverted Pendulum on Cart ===~%")
    (format t "Horizon N=~a, nx=~a, nu=~a~%" n nx nu)
    (format t "Initial state: ~a (tilted by ~5,2f deg)~%" x0
            (* 0.2d0 (/ 180.0d0 pi)))
    (with-mpc-solver
     (solver :horizon n :nx nx :nu nu :precision :double :mode :balance)
     (set-solver-dynamics solver ad bd) (set-solver-cost solver q r)
     (set-control-bounds solver 0 (- u-max) u-max)
     (multiple-value-bind (u-traj x-traj status iterations sl-traj
                           su-traj) (solve-mpc solver x0)
       (declare (ignore sl-traj su-traj))
       (format t "~%Solver finished with status ~a after ~a iterations.~%"
               status iterations)
       (format t "~%Optimal force trajectory u* (Newtons):~%")
       (dotimes (k n)
         (format t "  u[~2d] = ~8,4f~%" k (aref (aref u-traj k) 0)))
       (format t
               "~%Optimal state trajectory x* (predicted cart position & pole angle):~%")
       (dotimes (k (+ n 1))
         (let ((xk (aref x-traj k)))
           (format t
                   "  x[~2d] = [cart_pos:~8,4f cart_vel:~8,4f pole_ang:~8,4f pole_vel:~8,4f]~%"
                   k (aref xk 0) (aref xk 1) (aref xk 2) (aref xk 3))))
       (format t "~%Inverted pendulum stabilization complete.~%")))))