;; Auto-generated by cl-cl-generator (High-level API) — do not edit manually.
;; Generated: 2026-07-03 20:44:23
;; Git:       cb3c813766ff0be29dac48dc8ce6cf9703d35977
;; ================================================================================
;;  MPC Demo (High-Level API): 3D Spacecraft Rendezvous and Docking
;; ================================================================================
(defpackage :hpipm-spacecraft-demo
  (:use :cl :hpipm)
  (:export :run-spacecraft-demo))

(in-package :hpipm-spacecraft-demo)

;; --- Helper for Matrix-Vector Multiplication ---
(defun mat-vec-mult (a x)
  (let* ((n (array-dimension a 0)) (m (array-dimension a 1))
         (y (make-array n :element-type 'double-float :initial-element 0.0d0)))
    (dotimes (i n)
      (let ((sum 0.0d0))
        (dotimes (j m)
          (incf sum (* (aref a i j) (coerce (elt x j) 'double-float))))
        (setf (aref y i) sum)))
    y))

(defun propagate-state (ad bd x u)
  (let ((x-next (mat-vec-mult ad x)) (bu (mat-vec-mult bd u)))
    (dotimes (i (length x-next))
      (incf (aref x-next i) (aref bu i)))
    x-next))

;; --- Helper to Compute analytical CW system discretization ---
(defun compute-cw-matrices (n dt)
  (let* ((nt (* n dt)) (c (cos nt)) (s (sin nt))
         (ad
          (make-array '(6 6) :element-type 'double-float :initial-element
                      0.0d0))
         (bd
          (make-array '(6 3) :element-type 'double-float :initial-element
                      0.0d0)))
    (setf (aref ad 0 0) (- 4.0d0 (* 3.0d0 c)))
    (setf (aref ad 0 3) (/ s n))
    (setf (aref ad 0 4) (/ (* 2.0d0 (- 1.0d0 c)) n))
    (setf (aref ad 1 0) (* 6.0d0 (- s nt)))
    (setf (aref ad 1 1) 1.0d0)
    (setf (aref ad 1 3) (/ (* -2.0d0 (- 1.0d0 c)) n))
    (setf (aref ad 1 4) (/ (- (* 4.0d0 s) (* 3.0d0 nt)) n))
    (setf (aref ad 2 2) c)
    (setf (aref ad 2 5) (/ s n))
    (setf (aref ad 3 0) (* 3.0d0 n s))
    (setf (aref ad 3 3) c)
    (setf (aref ad 3 4) (* 2.0d0 s))
    (setf (aref ad 4 0) (* -6.0d0 n (- 1.0d0 c)))
    (setf (aref ad 4 3) (* -2.0d0 s))
    (setf (aref ad 4 4) (- (* 4.0d0 c) 3.0d0))
    (setf (aref ad 5 2) (- (* n s)))
    (setf (aref ad 5 5) c)
    (let ((n2 (* n n)))
      (setf (aref bd 0 0) (/ (- 1.0d0 c) n2))
      (setf (aref bd 0 1) (/ (* 2.0d0 (- nt s)) n2))
      (setf (aref bd 1 0) (/ (* -2.0d0 (- nt s)) n2))
      (setf (aref bd 1 1) (/ (- (* 4.0d0 (- 1.0d0 c)) (* 1.5d0 nt nt)) n2))
      (setf (aref bd 2 2) (/ (- 1.0d0 c) n2))
      (setf (aref bd 3 0) (/ s n))
      (setf (aref bd 3 1) (/ (* 2.0d0 (- 1.0d0 c)) n))
      (setf (aref bd 4 0) (/ (* -2.0d0 (- 1.0d0 c)) n))
      (setf (aref bd 4 1) (/ (- (* 4.0d0 s) (* 3.0d0 nt)) n))
      (setf (aref bd 5 2) (/ s n)))
    (values ad bd)))

;; --- ASCII Renderer for Along-Track vs Off-Axis Plane ---
(defun render-ascii-plane (history current-state state-idx label)
  (let* ((width 51) (height 17)
         (grid
          (make-array (list height width) :element-type 'character
                      :initial-element #\ )))
    (dotimes (c width)
      (let* ((y (- (* c 3.0d0) 150.0d0)) (lim (* -0.5d0 y))
             (upper-row (round (/ (- 48.0d0 lim) 6.0d0)))
             (lower-row (round (/ (- 48.0d0 (- lim)) 6.0d0))))
        (loop for r from (max 0 (1+ upper-row)) to (min (1- height)
                                                        (1- lower-row))
              do (setf (aref grid r c) #\.))
        (when (and (>= upper-row 0) (< upper-row height))
          (setf (aref grid upper-row c) #\\))
        (when (and (>= lower-row 0) (< lower-row height))
          (setf (aref grid lower-row c) #\/))))
    (setf (aref grid 8 50) #\>)
    (dolist (st history)
      (let* ((y (elt st 1)) (val (elt st state-idx))
             (c (round (/ (+ y 150.0d0) 3.0d0)))
             (r (round (/ (- 48.0d0 val) 6.0d0))))
        (when (and (>= c 0) (< c width) (>= r 0) (< r height))
          (setf (aref grid r c) #\o))))
    (let* ((y (elt current-state 1)) (val (elt current-state state-idx))
           (c (round (/ (+ y 150.0d0) 3.0d0)))
           (r (round (/ (- 48.0d0 val) 6.0d0))))
      (when (and (>= c 0) (< c width) (>= r 0) (< r height))
        (setf (aref grid r c) #\*)))
    (format t
            "~%--- ~a plane (Along-track [horizontal] vs Off-axis [vertical]) ---~%"
            label)
    (format t " +---------------------------------------------------+~%")
    (dotimes (r height)
      (format t " |")
      (dotimes (c width)
        (write-char (aref grid r c)))
      (format t "|~%"))
    (format t " +---------------------------------------------------+~%")
    (format t
            " -150m                                              0m (Docking Port)~%")))

;; --- Main Demo Function ---
(defun run-spacecraft-demo ()
  "Run the closed-loop 3D spacecraft docking MPC simulation."
  (let* ((n 30) (nx 6) (nu 3) (nbu 3) (nbx 0) (ng 4) (dt 10.0d0)
         (mean-motion 0.001107d0) (u-limit 0.05d0)
         (x0
          (make-array 6 :element-type 'double-float :initial-contents
                      '(50.0d0 -150.0d0 25.0d0 0.0d0 0.0d0 0.0d0)))
         (q
          (make-array '(6 6) :element-type 'double-float :initial-contents
                      '((1.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0)
                        (0.0d0 1.0d0 0.0d0 0.0d0 0.0d0 0.0d0)
                        (0.0d0 0.0d0 1.0d0 0.0d0 0.0d0 0.0d0)
                        (0.0d0 0.0d0 0.0d0 10.0d0 0.0d0 0.0d0)
                        (0.0d0 0.0d0 0.0d0 0.0d0 10.0d0 0.0d0)
                        (0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 10.0d0))))
         (r
          (make-array '(3 3) :element-type 'double-float :initial-contents
                      '((100.0d0 0.0d0 0.0d0) (0.0d0 100.0d0 0.0d0)
                        (0.0d0 0.0d0 100.0d0))))
         (soft-specs
          '((:stage :all :type :general :index 0 :z-weight 1000.0d0 :z-grad
             0.0d0)
            (:stage :all :type :general :index 1 :z-weight 1000.0d0 :z-grad
             0.0d0)
            (:stage :all :type :general :index 2 :z-weight 1000.0d0 :z-grad
             0.0d0)
            (:stage :all :type :general :index 3 :z-weight 1000.0d0 :z-grad
             0.0d0))))
    (multiple-value-bind (ad bd) (compute-cw-matrices mean-motion dt)
      (format t "~%=== HPIPM Closed-Loop MPC Demo: 3D Spacecraft Docking ===~%")
      (format t "LEO Mean Motion n = ~a rad/s, Sampling time dt = ~a s~%"
              mean-motion dt)
      (format t "Docking Corridor half-angle: ~a degrees~%"
              (* (atan 0.5d0) (/ 180.0d0 pi)))
      (format t "Initial State (x=~a, y=~a, z=~a) meters~%" (aref x0 0)
              (aref x0 1) (aref x0 2))
      (format t "Thruster limit: +/- ~a m/s^2~%~%" u-limit)
      (with-mpc-solver
       (solver :horizon n :nx nx :nu nu :nbu nbu :nbx nbx :ng ng :precision
        :double :soft-constraints soft-specs)
       (set-solver-dynamics solver ad bd)
       (let ((q-term
              (make-array '(6 6) :element-type 'double-float :initial-element
                          0.0d0)))
         (dotimes (i 6)
           (dotimes (j 6)
             (setf (aref q-term i j) (* 10.0d0 (aref q i j)))))
         (set-solver-cost solver q r :terminal-q q-term))
       (set-control-bounds-all-stages solver '(0 1 2)
        (list (- u-limit) (- u-limit) (- u-limit))
        (list u-limit u-limit u-limit))
       (let ((c
              (make-array '(4 6) :element-type 'double-float :initial-element
                          0.0d0))
             (d
              (make-array '(4 3) :element-type 'double-float :initial-element
                          0.0d0))
             (lg (list 0.0d0 -100000.0d0 0.0d0 -100000.0d0))
             (ug (list 100000.0d0 0.0d0 100000.0d0 0.0d0)))
         (setf (aref c 0 0) 1.0d0)
         (setf (aref c 0 1) -0.5d0)
         (setf (aref c 1 0) 1.0d0)
         (setf (aref c 1 1) 0.5d0)
         (setf (aref c 2 2) 1.0d0)
         (setf (aref c 2 1) -0.5d0)
         (setf (aref c 3 2) 1.0d0)
         (setf (aref c 3 1) 0.5d0)
         (dotimes (k n)
           (set-general-constraints solver k c d lg ug))
         (set-general-constraints solver n c nil lg ug))
       (let ((x
              (make-array 6 :element-type 'double-float :initial-contents x0))
             (history nil))
         (format t
                 " k |    x (m)   |    y (m)   |    z (m)   |   ux (m/s2) |   uy (m/s2) |   uz (m/s2) | iter | status~%")
         (format t
                 "---+------------+------------+------------+-------------+-------------+-------------+------+--------~%")
         (dotimes (step 31)
           (multiple-value-bind (u-traj x-pred status iterations sl-traj
                                 su-traj) (solve-mpc solver x)
             (declare (ignore x-pred))
             (let* ((ux (aref (aref u-traj 0) 0)) (uy (aref (aref u-traj 0) 1))
                    (uz (aref (aref u-traj 0) 2))
                    (u
                     (make-array 3 :element-type 'double-float
                                 :initial-contents (list ux uy uz))))
               (format t
                       "~2d | ~10,4f | ~10,4f | ~10,4f | ~11,6f | ~11,6f | ~11,6f |  ~2d  |   ~a~%"
                       step (aref x 0) (aref x 1) (aref x 2) ux uy uz
                       iterations status)
               (push (coerce x 'list) history)
               (if (and (/= status 0) (/= status 1))
                   (progn
                     (format t
                             "Solver failed with status ~a at step ~a. Aborting simulation.~%"
                             status step)
                     (return))
                   (setf x (propagate-state ad bd x u))))))
         (setf history (nreverse history))
         (render-ascii-plane history (car (last history)) 0 "y-x (Radial)")
         (render-ascii-plane history (car (last history)) 2
          "y-z (Cross-Track)"))))))