;;;; test-driver.lisp --- write-project idempotence, formatter registry, UTF-8

(in-package :polyglot.tests)

(def-suite :polyglot.unit.driver :in :polyglot.unit)
(in-suite :polyglot.unit.driver)

(defclass driver-test-backend (backend) ())
(defmethod backend-config ((b driver-test-backend)) '())
(defmethod module-artifacts ((b driver-test-backend) module)
  (list (make-artifact :path (format nil "~a.py" (ir-name module)) :kind :source
                       :content (format nil "x = \"~a äöü\"~%" (ir-name module)))
        (make-artifact :path (format nil "~a.zzz" (ir-name module)) :kind :source
                       :content "plain")))
(register-backend (make-instance 'driver-test-backend :key :driver-test))

(defun driver-project ()
  (make-project-item :name "d" :entry "one"
                     :modules (list (parse-module-form (read-dsl "(defmodule one (:entry t))")))))

(defun temp-out ()
  (uiop:ensure-directory-pathname
   (format nil "/tmp/polyglot-driver-test-~d-~d/" (get-universal-time) (random 100000))))

(test second-run-unchanged
  (let* ((out (temp-out))
         (first (write-project (driver-project) :targets '(:driver-test) :out out :format nil))
         (path (car (first first)))
         (mtime (file-write-date path)))
    (sleep 1.1)
    (let ((second (write-project (driver-project) :targets '(:driver-test) :out out :format nil)))
      (is (every (lambda (r) (eq :written (cdr r))) first))
      (is (every (lambda (r) (eq :unchanged (cdr r))) second))
      (is (= mtime (file-write-date path))))
    (uiop:delete-directory-tree out :validate t)))

(test header-and-utf8
  (let* ((out (temp-out))
         (res (write-project (driver-project) :targets '(:driver-test) :out out :format nil))
         (text (uiop:read-file-string (car (first res)) :external-format :utf-8)))
    (is (search "# Code generated by polyglot-generator. DO NOT EDIT." text))
    (is (search "äöü" text))
    (is (string= "plain" (uiop:read-file-string (car (second res)))))
    (uiop:delete-directory-tree out :validate t)))

(test missing-formatter-warns-once
  (let ((old (gethash "py" *formatters*))
        (warnings 0)
        (out (temp-out)))
    (register-formatter "py" '("no-such-formatter-xyz"))
    (unwind-protect
         (handler-bind ((dsl-warning (lambda (w) (incf warnings) (muffle-warning w))))
           (let ((res (write-project (make-project-item
                                      :name "d" :entry "one"
                                      :modules (list (parse-module-form (read-dsl "(defmodule one)"))
                                                     (parse-module-form (read-dsl "(defmodule two)"))))
                                     :targets '(:driver-test) :out out)))
             (is (= 4 (length res)))
             (is (probe-file (car (first res))))))
      (register-formatter "py" old)
      (uiop:delete-directory-tree out :validate t :if-does-not-exist :ignore))
    (is (= 1 warnings))))

(test formatter-runs-when-available
  (when (find-executable "ruff")
    (is (string= (format nil "x = 1~%")
                 (format-artifact-text (make-artifact :path "a.py") (format nil "x=1~%"))))))

(test unknown-backend
  (signals unsupported-construct (find-backend :no-such-language)))
